const fs=require('fs'),assert=require('assert'),path=require('path');const root=process.argv[2]||path.resolve(__dirname,'../..');const L=require(path.join(root,'dev/load-engine.js'));L.loadEngine();global.showToast=()=>{};global.saveAll=()=>{};global.syncUI=()=>{};global.addMsg=()=>({});global.busy=false;
let passed=0,failed=0;const cases=[];const started=Date.now();
function check(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.log('FAIL '+name+' :: '+e.message);}}
function fixture(inventory,wants){L.makeTestWorld();worldState.kind='village';worldState.world.location='The Village';worldState.world.sublocation=null;worldState.character.name='Silas';worldState.character.coin=2500;worldState.clock={min:12*MIN_PER_DAY+10*60,schedule:[]};memory.map.nodes['The Village']={firstVisit:1,visits:1,parent:null,npcs:[],items:[],size:'small'};importVillageResidents([{name:'Frizwick',gender:'F',cls:'Rogue'}]);worldState.world.sublocation='the trading post';const key='The Village|the trading post',node={firstVisit:1,visits:1,parent:'The Village',npcs:[],items:[],size:'small',keeper:'Frizwick',wares:[],wanted:[]};memory.map.nodes[key]=node;memory.npcs.Frizwick.lastSeenAt=key;worldState.character.inventory=inventory.slice();for(const w of wants)fileWanted(w[0],w[1],'Frizwick',worldState.turn,{key});assert(shopTradeCatalog().ok,'fixture must open actual shop');return node;}
function state(){return JSON.stringify({ws:worldState,m:memory});}function wants(n){return n.wanted.map(w=>w.item);}function sell(m){return shopTradeApply({sell:m,buy:{}});}function capture(name,v){cases.push({name,...v});console.log('OBS '+name+' '+JSON.stringify(v));}
const ringNames=['Warded ring','Warded ring — taken from the crypt','Warded ring (cracked)'];
{
const n=fixture(['Warded ring x2',...ringNames.slice(1)],[['Warded ring','40 gp']]),cat=shopTradeCatalog();check('three decorated rows share one offer key',()=>assert.deepStrictEqual(cat.sell.map(r=>r.want.key),['warded ring','warded ring','warded ring']));
const marks=Object.fromEntries(ringNames.map(x=>[x.toLowerCase(),1]));const before=state(),p=shopTradePlan(cat,{sell:marks}),r=sell(marks);capture('three marks',{plan:p,result:r});check('three marks refuse with named reason',()=>assert(!p.ok&&!r.ok&&/Frizwick.*Warded ring.*once/.test(r.reason)));check('refusal full world+memory unchanged',()=>assert.strictEqual(state(),before));
const b2=state(),r2=sell({'warded ring':2});check('stack qty2 refuses atomically',()=>assert(!r2.ok&&state()===b2));
const one=sell({'warded ring (cracked)':1});capture('one then subsequent',{result:one,coin:worldState.character.coin,wants:wants(n),inventory:worldState.character.inventory});check('one variant pays exactly4000 and retires offer',()=>assert(one.ok&&worldState.character.coin===6500&&wants(n).length===0));check('only selected variant leaves',()=>assert.deepStrictEqual(worldState.character.inventory,['Warded ring x2','Warded ring — taken from the crypt']));const before3=state(),r3=sell({'warded ring':1});check('subsequent unpriced ring refuses unchanged',()=>assert(!r3.ok&&state()===before3));
}
for(const name of ringNames){const n=fixture(ringNames,[['Warded ring','40 gp']]);const r=sell({[name.toLowerCase()]:1});check('one mark selects only '+name,()=>assert(r.ok&&r.plan.lines.length===1&&worldState.character.coin===6500&&!worldState.character.inventory.includes(name)&&worldState.character.inventory.length===2&&n.wanted.length===0));}
{
const n=fixture(['Warded ring x3'],[['Warded ring','40 gp']]);worldState.itemBible={'warded ring':{category:'treasure',effect:'N/A',uses:'N/A',value:'200 gp'}};let r=sell({'warded ring':1});check('first stack unit pays offer4000',()=>assert(r.ok&&worldState.character.coin===6500));r=sell({'warded ring':1});capture('second stack unit ordinary canon',{result:r,coin:worldState.character.coin});check('next unit pays ordinary half canon10000',()=>assert(r.ok&&r.plan.sellCp===10000&&worldState.character.coin===16500));
}
for(const reverse of [false,true]){
const ws=reverse?[['Warded ring (silver)','60 gp'],['Warded ring','40 gp']]:[['Warded ring','40 gp'],['Warded ring (silver)','60 gp']];const sold=reverse?'Warded ring':'Warded ring (silver)',other=reverse?'Warded ring (silver)':'Warded ring';const n=fixture(['Warded ring x2','Warded ring (silver) x2'],ws),cat=shopTradeCatalog();check('distinct wants get distinct allowances '+reverse,()=>{const p=shopTradePlan(cat,{sell:{'warded ring':1,'warded ring (silver)':1}});assert(p.ok&&p.sellCp===10000);});const cp=reverse?4000:6000;const r=sell({[sold.toLowerCase()]:1});capture('distinct want single sale '+reverse,{catalog:cat.sell,result:r,wants:wants(n),coin:worldState.character.coin});check('matched offer payment correct '+reverse,()=>assert(r.ok&&worldState.character.coin===2500+cp));check('retire the exact paid offer '+reverse,()=>assert.deepStrictEqual(wants(n),[other]));const second=sell({[sold.toLowerCase()]:1});capture('same paid offer repeated '+reverse,{result:second,wants:wants(n),coin:worldState.character.coin});check('same paid offer cannot pay twice '+reverse,()=>assert(!second.ok));}
{
const n=fixture(['Warded ring','Warded ring (silver)'],[['Warded ring','40 gp'],['Warded ring (silver)','60 gp']]);const r=sell({'warded ring':1,'warded ring (silver)':1});check('two distinct wants sold together pay10000 retire both',()=>assert(r.ok&&worldState.character.coin===12500&&!n.wanted.length&&!worldState.character.inventory.length));
}
{
const n=fixture(['Warded ring x2'],[['Warded ring','40 gp']]),cat=shopTradeCatalog(),p=shopTradePlan(cat,{sell:{'warded ring':1}});worldState.character.inventory=[];const before=state(),r=ledgerApply(p,{key:cat.key});capture('stale missing item ledger refusal',r);check('ledger stale missing item refuses full state unchanged',()=>assert(!r.ok&&state()===before));
}
{
const n=fixture(['Warded ring x2'],[['Warded ring','40 gp']]);let r=applyMuts('Frizwick watches you discard it. [ITEM_LOST:Warded ring]');check('591 control no-coin discard retains want',()=>assert(n.wanted.length===1));const coin=worldState.character.coin;r=applyMuts('Frizwick returns one copper in change from an earlier purchase. You discard the ring. [SAY:Frizwick|plain]Your change.[/SAY] [GOLD:+1 cp][ITEM_LOST:Warded ring]');capture('591 separate boundary',{muts:r.muts,wants:wants(n),coinDelta:worldState.character.coin-coin});check('591 unrelated change must not retire ring offer',()=>assert(n.wanted.length===1));
}
const summary={passed,failed,elapsedMs:Date.now()-started,startedUtc:new Date(started).toISOString()};console.log('SUMMARY '+JSON.stringify(summary));fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify({summary,cases},null,2));process.exitCode=failed?1:0;
