// Generated by dev/build-audio-catalog.js; edit dev/audio-delivery.json.
var AUDIO_CATALOG = {
  "schema": 1,
  "cohort": "starter-1",
  "assets": [
    {
      "id": "smithy",
      "label": "Smithy fire",
      "cohort": "starter-1",
      "role": "feature",
      "bed": {
        "url": "sfx/smithy-fire-v2.mp3",
        "gain": 0.55,
        "loopStart": 0,
        "loopEnd": 9.005,
        "maxSeconds": 20,
        "channels": 1,
        "maxBytes": 500000,
        "maxDecodedBytes": 4000000
      },
      "contains": [
        "fire"
      ],
      "enclosures": [
        "covered",
        "sealed"
      ],
      "settings": [
        "interior"
      ],
      "biomes": [
        "unspecified"
      ],
      "from": 0,
      "to": 1440,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "loop": true,
        "mix": true
      },
      "source": {
        "sha256": "36d5ccc8ffa065a642d46d2b8d15cda7556184f30662fe2bf3bf25c5236611c7",
        "url": "https://nox-sound-design.itch.io/essentials-series-sfx-nox-sound",
        "author": "Nox_Sound",
        "license": "CC0-1.0"
      },
      "recipe": "mono; DC removal; 1 s tail/head crossfade; RMS -32 dBFS; libmp3lame 128 kbps",
      "seedOnly": true,
      "sha256": "d2b017fce86f4ef9eef89b669733c35433dae5517fc85ff0ba3e2852b9df23cd",
      "bytes": 145152
    },
    {
      "id": "village-morning",
      "label": "Morning birds and breeze",
      "cohort": "starter-1",
      "role": "environment",
      "bed": {
        "url": "sfx/village-morning-v2.mp3",
        "gain": 0.55,
        "loopStart": 0,
        "loopEnd": 27.067,
        "maxSeconds": 125,
        "channels": 1,
        "maxBytes": 2200000,
        "maxDecodedBytes": 24000000
      },
      "contains": [
        "birds",
        "wind"
      ],
      "enclosures": [
        "open"
      ],
      "settings": [
        "settlement",
        "wilderness"
      ],
      "biomes": [
        "temperate"
      ],
      "from": 300,
      "to": 600,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "loop": true,
        "mix": true
      },
      "source": {
        "sha256": "98b1d9ea7542b496d97a182fcee828bc5d0df39b857ef3b7323c592912e1d372",
        "url": "https://nox-sound-design.itch.io/essentials-series-sfx-nox-sound",
        "author": "Nox_Sound (Essentials Series)",
        "license": "CC0-1.0"
      },
      "recipe": "mono mean; DC removal; 2.00-second raised-cosine overlap of tail/head; RMS target -26 dBFS with peak ceiling -6 dBFS; libmp3lame 128 kbps mono with Xing/LAME gapless header, no ID3",
      "seedOnly": false,
      "sha256": "892f78d6b0642509b503a1197ef5c4a4db253bfd2cebbf9091ee863d76dcfbbd",
      "bytes": 433920
    },
    {
      "id": "village-day",
      "label": "Daytime birds and insects",
      "cohort": "starter-1",
      "role": "environment",
      "bed": {
        "url": "sfx/village-day-v2.mp3",
        "gain": 0.55,
        "loopStart": 0,
        "loopEnd": 55.838,
        "maxSeconds": 125,
        "channels": 1,
        "maxBytes": 2200000,
        "maxDecodedBytes": 24000000
      },
      "contains": [
        "birds",
        "insects",
        "wind"
      ],
      "enclosures": [
        "open"
      ],
      "settings": [
        "settlement",
        "wilderness"
      ],
      "biomes": [
        "temperate"
      ],
      "from": 600,
      "to": 1080,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "loop": true,
        "mix": true
      },
      "source": {
        "sha256": "fdf564645bb6646d3f6c7bf071301aef78540f2c7260aec7d7c907aeecc32b8c",
        "url": "https://nox-sound-design.itch.io/essentials-series-sfx-nox-sound",
        "author": "Nox_Sound (Essentials Series)",
        "license": "CC0-1.0"
      },
      "recipe": "mono mean; DC removal; 2.00-second raised-cosine overlap of tail/head; RMS target -26 dBFS with peak ceiling -6 dBFS; libmp3lame 128 kbps mono with Xing/LAME gapless header, no ID3",
      "seedOnly": false,
      "sha256": "27b6acb80f2cbbe5a26dd619333c65cce3c03549d61d9a0053ccd4c26edb2fdf",
      "bytes": 894336
    },
    {
      "id": "village-evening",
      "label": "Evening breeze",
      "cohort": "starter-1",
      "role": "environment",
      "bed": {
        "url": "sfx/village-evening-v2.mp3",
        "gain": 0.55,
        "loopStart": 0,
        "loopEnd": 27.919,
        "maxSeconds": 125,
        "channels": 1,
        "maxBytes": 2200000,
        "maxDecodedBytes": 24000000
      },
      "contains": [
        "wind"
      ],
      "enclosures": [
        "open"
      ],
      "settings": [
        "settlement",
        "wilderness"
      ],
      "biomes": [
        "temperate"
      ],
      "from": 1080,
      "to": 1260,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "loop": true,
        "mix": true
      },
      "source": {
        "sha256": "e2ec7e5d2e74db52bc21a5b1830c2b983ec8270e976d6b0ef393912f6d383133",
        "url": "https://nox-sound-design.itch.io/essentials-series-sfx-nox-sound",
        "author": "Nox_Sound (Essentials Series)",
        "license": "CC0-1.0"
      },
      "recipe": "mono mean; DC removal; 2.00-second raised-cosine overlap of tail/head; RMS target -26 dBFS with peak ceiling -6 dBFS; libmp3lame 128 kbps mono with Xing/LAME gapless header, no ID3",
      "seedOnly": false,
      "sha256": "dca88de4c40737349aec2a2bccb4151a610b1aa909e4bfac40384b10967435a2",
      "bytes": 447744
    },
    {
      "id": "village-night",
      "label": "Night crickets",
      "cohort": "starter-1",
      "role": "environment",
      "bed": {
        "url": "sfx/village-night-v3.mp3",
        "gain": 0.55,
        "loopStart": 0,
        "loopEnd": 57.79,
        "maxSeconds": 125,
        "channels": 1,
        "maxBytes": 2200000,
        "maxDecodedBytes": 24000000
      },
      "contains": [
        "insects",
        "wind"
      ],
      "enclosures": [
        "open"
      ],
      "settings": [
        "settlement",
        "wilderness"
      ],
      "biomes": [
        "temperate"
      ],
      "from": 1260,
      "to": 300,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "loop": false,
        "mix": false
      },
      "source": {
        "sha256": "f4b4542a7036744acdeaf6e2c46e4f972f260fcd1624d1c1efa3cedcc9f71752",
        "url": "https://freesound.org/s/637083/",
        "author": "Nox_Sound (Freesound 637083)",
        "license": "CC0-1.0"
      },
      "recipe": "mono mean; DC removal; 2.00-second raised-cosine overlap of tail/head; RMS target -26 dBFS with peak ceiling -6 dBFS; libmp3lame 128 kbps mono with Xing/LAME gapless header, no ID3",
      "seedOnly": false,
      "sha256": "6fa58549815f5207b67911116bba88137081dc9a0ec51b5b7cdf3f75a157c40a",
      "bytes": 925440
    },
    {
      "id": "tavern",
      "label": "Tavern crowd",
      "cohort": "starter-1",
      "role": "environment",
      "bed": {
        "url": "sfx/tavern-v1.mp3",
        "gain": 0.55,
        "loopStart": 0,
        "loopEnd": 35.485,
        "maxSeconds": 40,
        "channels": 1,
        "maxBytes": 700000,
        "maxDecodedBytes": 8000000
      },
      "contains": [
        "crowd",
        "voices"
      ],
      "enclosures": [
        "covered",
        "sealed"
      ],
      "settings": [
        "interior"
      ],
      "biomes": [
        "unspecified"
      ],
      "from": 0,
      "to": 1440,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "loop": false,
        "mix": false
      },
      "source": {
        "sha256": "fd4ba1511f8dec5420dd285175c23da7b39e1b2135c8a8c33b044f37550746a4",
        "url": "https://freesound.org/s/326313/",
        "author": "ivolipa (Freesound 326313)",
        "license": "CC0-1.0"
      },
      "recipe": "mono mean; DC removal; 2.00-second raised-cosine overlap of tail/head; RMS target -32 dBFS with peak ceiling -6 dBFS; libmp3lame 128 kbps mono with Xing/LAME gapless header, no ID3",
      "seedOnly": true,
      "sha256": "2329c059994ca980f35f3a1b648bc5fb222d738d2f089b590a0bba141a0511e4",
      "bytes": 568841
    },
    {
      "id": "footsteps-wood",
      "label": "Footsteps on a wooden floor",
      "cohort": "starter-1",
      "role": "accent",
      "sprite": {
        "url": "sfx/accent-footsteps-wood-v1.mp3",
        "gain": [
          0.35,
          0.7
        ],
        "cuts": [
          [
            0.25,
            0.6722
          ],
          [
            0.9222,
            1.3425
          ],
          [
            1.5925,
            2.0656
          ],
          [
            2.3156,
            2.8182
          ],
          [
            3.0682,
            3.5287
          ]
        ],
        "maxSeconds": 6,
        "channels": 1,
        "maxBytes": 200000,
        "maxDecodedBytes": 1200000
      },
      "pattern": {
        "kind": "burst",
        "count": [
          3,
          7
        ],
        "cadence": [
          0.45,
          0.6
        ]
      },
      "gap": [
        90,
        240
      ],
      "trigger": "ambient",
      "rain": "stop",
      "needsAny": [
        "voices",
        "crowd"
      ],
      "contains": [],
      "enclosures": [
        "covered",
        "sealed"
      ],
      "settings": [
        "interior"
      ],
      "biomes": [
        "temperate",
        "arid",
        "tropical",
        "frozen",
        "unspecified"
      ],
      "from": 0,
      "to": 1440,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "mix": true
      },
      "source": {
        "sha256": "ced3c3e067d9e9e7d46075a5cfdcc8063153c0099c076fdfa27cd171f16f18d6,0fbf01e67ceeefa6489d3b82d070c3b03df67ea4daf12503da7aa46a97c9b03b,7b732ddaf1f3586571a6790ebeeea8400f1acf9e4921c64a987d29bb4764756f,8d8c46c46c9743a436b92f971ffdc893ea8a82bb29d1197d767520d5885a666c,71e464eb4ccea15c264339660b175ab55317024f8ae90aa6cdbd582efc72ab7e",
        "url": "https://nox-sound-design.itch.io/essentials-series-sfx-nox-sound",
        "author": "Nox_Sound (Essentials Series)",
        "license": "CC0-1.0"
      },
      "recipe": "mono mean; DC removal; trim below -50 dB of sample peak with 20 ms pre-roll; RMS -30 dBFS, peak ceiling -6 dBFS; 10 ms raised-cosine fades; 0.25 s silence between samples; libmp3lame 128 kbps mono with Xing/LAME gapless header, no ID3",
      "seedOnly": false,
      "sha256": "fb525bfb3e6a27164bb404100e3c91fdeaa58aecf738a4b0080b28b9a29c46ca",
      "bytes": 61440
    }
  ],
  "version": "f6645e44f5f88220a1cb"
};
