// Generated by dev/build-audio-catalog.js; edit dev/audio-delivery.json.
var AUDIO_CATALOG = {
  "schema": 1,
  "cohort": "starter-1",
  "assets": [
    {
      "id": "smithy",
      "label": "Smithy fire",
      "cohort": "starter-1",
      "role": "feature",
      "bed": {
        "url": "sfx/smithy-fire-v2.mp3",
        "gain": 0.55,
        "loopStart": 0,
        "loopEnd": 9.005,
        "maxSeconds": 20,
        "channels": 1,
        "maxBytes": 500000,
        "maxDecodedBytes": 4000000
      },
      "contains": [
        "fire"
      ],
      "enclosures": [
        "covered",
        "sealed"
      ],
      "settings": [
        "interior"
      ],
      "biomes": [
        "unspecified"
      ],
      "from": 0,
      "to": 1440,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "loop": true,
        "mix": true
      },
      "source": {
        "sha256": "36d5ccc8ffa065a642d46d2b8d15cda7556184f30662fe2bf3bf25c5236611c7",
        "url": "https://nox-sound-design.itch.io/essentials-series-sfx-nox-sound",
        "author": "Nox_Sound",
        "license": "CC0-1.0"
      },
      "recipe": "mono; DC removal; 1 s tail/head crossfade; RMS -32 dBFS; libmp3lame 128 kbps",
      "seedOnly": true,
      "sha256": "d2b017fce86f4ef9eef89b669733c35433dae5517fc85ff0ba3e2852b9df23cd",
      "bytes": 145152
    },
    {
      "id": "village-morning",
      "label": "Morning birds and breeze",
      "cohort": "starter-1",
      "role": "environment",
      "bed": {
        "url": "sfx/village-morning-v2.mp3",
        "gain": 0.55,
        "loopStart": 0,
        "loopEnd": 27.067,
        "maxSeconds": 125,
        "channels": 1,
        "maxBytes": 2200000,
        "maxDecodedBytes": 24000000
      },
      "contains": [
        "birds",
        "wind"
      ],
      "enclosures": [
        "open"
      ],
      "settings": [
        "settlement",
        "wilderness"
      ],
      "biomes": [
        "temperate"
      ],
      "from": 300,
      "to": 600,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "loop": true,
        "mix": true
      },
      "source": {
        "sha256": "98b1d9ea7542b496d97a182fcee828bc5d0df39b857ef3b7323c592912e1d372",
        "url": "https://nox-sound-design.itch.io/essentials-series-sfx-nox-sound",
        "author": "Nox_Sound (Essentials Series)",
        "license": "CC0-1.0"
      },
      "recipe": "mono mean; DC removal; 2.00-second raised-cosine overlap of tail/head; RMS target -26 dBFS with peak ceiling -6 dBFS; libmp3lame 128 kbps mono with Xing/LAME gapless header, no ID3",
      "seedOnly": false,
      "sha256": "892f78d6b0642509b503a1197ef5c4a4db253bfd2cebbf9091ee863d76dcfbbd",
      "bytes": 433920
    },
    {
      "id": "village-day",
      "label": "Daytime birds and insects",
      "cohort": "starter-1",
      "role": "environment",
      "bed": {
        "url": "sfx/village-day-v2.mp3",
        "gain": 0.55,
        "loopStart": 0,
        "loopEnd": 55.838,
        "maxSeconds": 125,
        "channels": 1,
        "maxBytes": 2200000,
        "maxDecodedBytes": 24000000
      },
      "contains": [
        "birds",
        "insects",
        "wind"
      ],
      "enclosures": [
        "open"
      ],
      "settings": [
        "settlement",
        "wilderness"
      ],
      "biomes": [
        "temperate"
      ],
      "from": 600,
      "to": 1080,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "loop": true,
        "mix": true
      },
      "source": {
        "sha256": "fdf564645bb6646d3f6c7bf071301aef78540f2c7260aec7d7c907aeecc32b8c",
        "url": "https://nox-sound-design.itch.io/essentials-series-sfx-nox-sound",
        "author": "Nox_Sound (Essentials Series)",
        "license": "CC0-1.0"
      },
      "recipe": "mono mean; DC removal; 2.00-second raised-cosine overlap of tail/head; RMS target -26 dBFS with peak ceiling -6 dBFS; libmp3lame 128 kbps mono with Xing/LAME gapless header, no ID3",
      "seedOnly": false,
      "sha256": "27b6acb80f2cbbe5a26dd619333c65cce3c03549d61d9a0053ccd4c26edb2fdf",
      "bytes": 894336
    },
    {
      "id": "village-evening",
      "label": "Evening breeze",
      "cohort": "starter-1",
      "role": "environment",
      "bed": {
        "url": "sfx/village-evening-v2.mp3",
        "gain": 0.55,
        "loopStart": 0,
        "loopEnd": 27.919,
        "maxSeconds": 125,
        "channels": 1,
        "maxBytes": 2200000,
        "maxDecodedBytes": 24000000
      },
      "contains": [
        "wind"
      ],
      "enclosures": [
        "open"
      ],
      "settings": [
        "settlement",
        "wilderness"
      ],
      "biomes": [
        "temperate"
      ],
      "from": 1080,
      "to": 1260,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "loop": true,
        "mix": true
      },
      "source": {
        "sha256": "e2ec7e5d2e74db52bc21a5b1830c2b983ec8270e976d6b0ef393912f6d383133",
        "url": "https://nox-sound-design.itch.io/essentials-series-sfx-nox-sound",
        "author": "Nox_Sound (Essentials Series)",
        "license": "CC0-1.0"
      },
      "recipe": "mono mean; DC removal; 2.00-second raised-cosine overlap of tail/head; RMS target -26 dBFS with peak ceiling -6 dBFS; libmp3lame 128 kbps mono with Xing/LAME gapless header, no ID3",
      "seedOnly": false,
      "sha256": "dca88de4c40737349aec2a2bccb4151a610b1aa909e4bfac40384b10967435a2",
      "bytes": 447744
    },
    {
      "id": "village-night",
      "label": "Noctina - village night",
      "cohort": "starter-1",
      "role": "environment",
      "bed": {
        "url": "sfx/village-night-noctina-v1.mp3",
        "gain": 0.55,
        "loopStart": 0,
        "loopEnd": 84.15,
        "maxSeconds": 125,
        "channels": 1,
        "maxBytes": 2200000,
        "maxDecodedBytes": 24000000
      },
      "contains": [
        "music",
        "insects",
        "wind",
        "birds",
        "animals"
      ],
      "enclosures": [
        "open"
      ],
      "settings": [
        "settlement",
        "wilderness"
      ],
      "biomes": [
        "temperate"
      ],
      "from": 1260,
      "to": 300,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "loop": true,
        "mix": true
      },
      "source": {
        "sha256": "42e638e79236f986aaa9d9842b922295af66c10cf847192cc3fd2f65d0d2936d",
        "url": "https://suno.com/song/ff0a52f1-8590-4ba6-9c19-11ee87414f54",
        "author": "highdefinitionbuttons823 (owner Suno account); effects: Breviceps, SamsterBirdies, Joseph SARDIN, Nox_Sound",
        "license": "Owner-supplied Suno Pro music + CC0-1.0 effects; see sfx/noctina-night-CREDITS.md"
      },
      "recipe": "Noctina 1.05-89.20 s; 4 s tail/head overlap; music RMS -23 dBFS; quiet CC0 crickets and owl/wing/coyote events at 13/35/49/75 s; mono mean; 128 kbps MP3 with gapless header. Owner authorized in-game adjustment 2026-09-27.",
      "seedOnly": true,
      "sha256": "ac187ddca2a54093452cea8ee9a66c7c0f7cdaabf62c15fd38367defcdab90c6",
      "bytes": 1347499
    },
    {
      "id": "tavern",
      "label": "Tavern chatter and hearth",
      "cohort": "starter-1",
      "role": "environment",
      "bed": {
        "url": "sfx/tavern-hearth-v1.mp3",
        "gain": 0.55,
        "loopStart": 0,
        "loopEnd": 35.485,
        "maxSeconds": 40,
        "channels": 1,
        "maxBytes": 700000,
        "maxDecodedBytes": 8000000
      },
      "contains": [
        "crowd",
        "voices",
        "fire"
      ],
      "enclosures": [
        "covered",
        "sealed"
      ],
      "settings": [
        "interior"
      ],
      "biomes": [
        "temperate",
        "arid",
        "tropical",
        "frozen",
        "unspecified"
      ],
      "from": 0,
      "to": 1440,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "loop": true,
        "mix": true
      },
      "source": {
        "sha256": "fd4ba1511f8dec5420dd285175c23da7b39e1b2135c8a8c33b044f37550746a4,36d5ccc8ffa065a642d46d2b8d15cda7556184f30662fe2bf3bf25c5236611c7",
        "url": "https://freesound.org/s/326313/ https://nox-sound-design.itch.io/essentials-series-sfx-nox-sound",
        "author": "ivolipa (tavern), Nox_Sound (fire)",
        "license": "CC0-1.0"
      },
      "recipe": "Resample source WAVs to mono 44.1kHz. Existing CC0 tavern loop plus 0.6-gain CC0 fire; four periodic fire cycles fitted to tavern duration; mono PCM16, MP3 128kbps with gapless header.",
      "seedOnly": true,
      "sha256": "091d4177ecb1e9114ac6c1f0d62a8484dbd8a5d949ac7760abf022b10d4f5ecc",
      "bytes": 568841
    },
    {
      "id": "footsteps-wood",
      "label": "Footsteps on a wooden floor",
      "cohort": "starter-1",
      "role": "accent",
      "sprite": {
        "url": "sfx/accent-footsteps-wood-v1.mp3",
        "gain": [
          0.35,
          0.7
        ],
        "cuts": [
          [
            0.25,
            0.6722
          ],
          [
            0.9222,
            1.3425
          ],
          [
            1.5925,
            2.0656
          ],
          [
            2.3156,
            2.8182
          ],
          [
            3.0682,
            3.5287
          ]
        ],
        "maxSeconds": 6,
        "channels": 1,
        "maxBytes": 200000,
        "maxDecodedBytes": 1200000
      },
      "pattern": {
        "kind": "burst",
        "count": [
          3,
          7
        ],
        "cadence": [
          0.45,
          0.6
        ]
      },
      "gap": [
        90,
        240
      ],
      "trigger": "ambient",
      "rain": "stop",
      "needsAny": [
        "voices",
        "crowd"
      ],
      "contains": [],
      "enclosures": [
        "covered",
        "sealed"
      ],
      "settings": [
        "interior"
      ],
      "biomes": [
        "temperate",
        "arid",
        "tropical",
        "frozen",
        "unspecified"
      ],
      "from": 0,
      "to": 1440,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "mix": true
      },
      "source": {
        "sha256": "ced3c3e067d9e9e7d46075a5cfdcc8063153c0099c076fdfa27cd171f16f18d6,0fbf01e67ceeefa6489d3b82d070c3b03df67ea4daf12503da7aa46a97c9b03b,7b732ddaf1f3586571a6790ebeeea8400f1acf9e4921c64a987d29bb4764756f,8d8c46c46c9743a436b92f971ffdc893ea8a82bb29d1197d767520d5885a666c,71e464eb4ccea15c264339660b175ab55317024f8ae90aa6cdbd582efc72ab7e",
        "url": "https://nox-sound-design.itch.io/essentials-series-sfx-nox-sound",
        "author": "Nox_Sound (Essentials Series)",
        "license": "CC0-1.0"
      },
      "recipe": "mono mean; DC removal; trim below -50 dB of sample peak with 20 ms pre-roll; RMS -30 dBFS, peak ceiling -6 dBFS; 10 ms raised-cosine fades; 0.25 s silence between samples; libmp3lame 128 kbps mono with Xing/LAME gapless header, no ID3",
      "seedOnly": false,
      "sha256": "fb525bfb3e6a27164bb404100e3c91fdeaa58aecf738a4b0080b28b9a29c46ca",
      "bytes": 61440
    },
    {
      "id": "chimes-koshi",
      "label": "Koshi wind chimes",
      "cohort": "starter-1",
      "role": "accent",
      "sprite": {
        "url": "sfx/accent-chimes-koshi-v1.mp3",
        "gain": [
          0.3,
          0.55
        ],
        "cuts": [
          [
            0.25,
            5.25
          ],
          [
            5.5,
            10.5
          ],
          [
            10.75,
            15.75
          ],
          [
            16,
            21
          ],
          [
            21.25,
            26.25
          ],
          [
            26.5,
            31.5
          ]
        ],
        "maxSeconds": 33,
        "channels": 1,
        "maxBytes": 600000,
        "maxDecodedBytes": 6288000
      },
      "pattern": {
        "kind": "single"
      },
      "gap": [
        45,
        150
      ],
      "trigger": "ambient",
      "rain": "play",
      "needsAny": [],
      "contains": [
        "chimes"
      ],
      "enclosures": [
        "open",
        "covered",
        "sealed"
      ],
      "settings": [
        "settlement",
        "interior",
        "wilderness",
        "coast",
        "unspecified"
      ],
      "biomes": [
        "temperate",
        "arid",
        "tropical",
        "frozen",
        "unspecified"
      ],
      "from": 0,
      "to": 1440,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "mix": false
      },
      "source": {
        "sha256": "bcd9fb192471623bcfc28654ca8c43702eaadd9f1facd945ae41fb86e010513e,f281eaf154d6bec420a83b5f5fbd20c0d1d8145bc1da2bc1f294b75115adedba",
        "url": "https://freesound.org/s/376001/ https://freesound.org/s/378431/",
        "author": "Kinoton",
        "license": "CC0-1.0"
      },
      "recipe": "mono mean; DC removal; trim below -90 dB of sample peak with 20 ms pre-roll; RMS -30 dBFS, peak ceiling -6 dBFS; raised-cosine fades 300 ms in / 1500 ms out; 0.25 s silence between samples; libmp3lame 128 kbps mono with Xing/LAME gapless header, no ID3; six 5 s phrases cut from two continuous takes at their quietest edges",
      "seedOnly": false,
      "sha256": "f24e1eddf7d252f90921a2e5142e0e96be1d05b3fcd85b3baf54dda697587844",
      "bytes": 508800
    },
    {
      "id": "chimes-metal",
      "label": "Metal wind chimes",
      "cohort": "starter-1",
      "role": "accent",
      "sprite": {
        "url": "sfx/accent-chimes-metal-v1.mp3",
        "gain": [
          0.3,
          0.55
        ],
        "cuts": [
          [
            0.25,
            5.25
          ],
          [
            5.5,
            10.5
          ],
          [
            10.75,
            15.75
          ],
          [
            16,
            21
          ],
          [
            21.25,
            26.25
          ]
        ],
        "maxSeconds": 28,
        "channels": 1,
        "maxBytes": 600000,
        "maxDecodedBytes": 5280000
      },
      "pattern": {
        "kind": "single"
      },
      "gap": [
        45,
        150
      ],
      "trigger": "ambient",
      "rain": "play",
      "needsAny": [],
      "contains": [
        "chimes"
      ],
      "enclosures": [
        "open",
        "covered",
        "sealed"
      ],
      "settings": [
        "settlement",
        "interior",
        "wilderness",
        "coast",
        "unspecified"
      ],
      "biomes": [
        "temperate",
        "arid",
        "tropical",
        "frozen",
        "unspecified"
      ],
      "from": 0,
      "to": 1440,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "mix": false
      },
      "source": {
        "sha256": "d6fd7c4b6b65f3b24d2543f552b3e027c74adfab6579024d4e7e194ec9f547ac",
        "url": "https://freesound.org/s/266951/",
        "author": "janbezouska",
        "license": "CC0-1.0"
      },
      "recipe": "mono mean; DC removal; trim below -90 dB of sample peak with 20 ms pre-roll; RMS -30 dBFS, peak ceiling -6 dBFS; raised-cosine fades 300 ms in / 1500 ms out; 0.25 s silence between samples; libmp3lame 128 kbps mono with Xing/LAME gapless header, no ID3; five 5 s phrases cut from a continuous take at its quietest edges",
      "seedOnly": false,
      "sha256": "13b2313af15e1131b2e45f46b3461fe5ea0467342cfe3785e5362246ff4ad5a3",
      "bytes": 425088
    },
    {
      "id": "bowl-small",
      "label": "Small singing bowl",
      "cohort": "starter-1",
      "role": "accent",
      "sprite": {
        "url": "sfx/accent-bowl-small-v1.mp3",
        "gain": [
          0.3,
          0.5
        ],
        "cuts": [
          [
            0.25,
            6.5193
          ]
        ],
        "maxSeconds": 8,
        "channels": 1,
        "maxBytes": 600000,
        "maxDecodedBytes": 1491705
      },
      "pattern": {
        "kind": "single"
      },
      "gap": [
        90,
        300
      ],
      "trigger": "ambient",
      "rain": "play",
      "needsAny": [],
      "contains": [
        "chimes"
      ],
      "enclosures": [
        "covered",
        "sealed"
      ],
      "settings": [
        "interior",
        "settlement"
      ],
      "biomes": [
        "temperate",
        "arid",
        "tropical",
        "frozen",
        "unspecified"
      ],
      "from": 0,
      "to": 1440,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "mix": false
      },
      "source": {
        "sha256": "fc7872085065eb0ff64cf5d4c30730f396eb12652b8f1daa10408d7a5be12125",
        "url": "https://freesound.org/s/271370/",
        "author": "inoshirodesign",
        "license": "CC0-1.0"
      },
      "recipe": "mono mean; DC removal; trim below -60 dB of sample peak with 20 ms pre-roll; RMS -30 dBFS, peak ceiling -6 dBFS; raised-cosine fades 10 ms in / 300 ms out; 0.25 s silence between samples; libmp3lame 128 kbps mono with Xing/LAME gapless header, no ID3; one strike; the owner heard it as a small chime",
      "seedOnly": false,
      "sha256": "d937c01e946178153deb1e012c353711f339d230ed3b8555100e3e39aa27f04e",
      "bytes": 109440
    },
    {
      "id": "bell-church",
      "label": "Church bell, far off",
      "cohort": "starter-1",
      "role": "accent",
      "sprite": {
        "url": "sfx/accent-bell-church-v1.mp3",
        "gain": [
          0.2,
          0.4
        ],
        "cuts": [
          [
            0.25,
            14.25
          ]
        ],
        "maxSeconds": 16,
        "channels": 1,
        "maxBytes": 600000,
        "maxDecodedBytes": 2976000
      },
      "pattern": {
        "kind": "single"
      },
      "gap": [
        240,
        600
      ],
      "trigger": "ambient",
      "rain": "play",
      "needsAny": [],
      "contains": [
        "bells"
      ],
      "enclosures": [
        "open"
      ],
      "settings": [
        "settlement"
      ],
      "biomes": [
        "temperate",
        "arid",
        "tropical",
        "frozen",
        "unspecified"
      ],
      "from": 0,
      "to": 1440,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "mix": false
      },
      "source": {
        "sha256": "8ef3ec01529564007a6484f8dffca50e06f41af2f637b39cdadebf48f5d834b6",
        "url": "https://freesound.org/s/857912/",
        "author": "bassimat",
        "license": "CC0-1.0"
      },
      "recipe": "mono mean; DC removal; trim below -90 dB of sample peak with 20 ms pre-roll; RMS -30 dBFS, peak ceiling -6 dBFS; raised-cosine fades 10 ms in / 2500 ms out; 0.25 s silence between samples; libmp3lame 128 kbps mono with Xing/LAME gapless header, no ID3; first 14 s of the peal with a 2.5 s fade; outdoors only (owner ruling 2026-09-22)",
      "seedOnly": false,
      "sha256": "f1c7bc60d4daa125efc043a3cede71856c0d97d6ac2e34d8bf30beed845ddb59",
      "bytes": 233088
    },
    {
      "id": "village-dusk-noctina",
      "label": "Noctina - dusk with crickets",
      "cohort": "starter-1",
      "role": "environment",
      "bed": {
        "url": "sfx/village-dusk-noctina-v1.mp3",
        "gain": 0.55,
        "loopStart": 0,
        "loopEnd": 84.15,
        "maxSeconds": 125,
        "channels": 1,
        "maxBytes": 2200000,
        "maxDecodedBytes": 24000000
      },
      "contains": [
        "music",
        "insects",
        "wind"
      ],
      "enclosures": [
        "open"
      ],
      "settings": [
        "settlement",
        "wilderness"
      ],
      "biomes": [
        "temperate"
      ],
      "from": 1080,
      "to": 1260,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "loop": true,
        "mix": true
      },
      "source": {
        "sha256": "42e638e79236f986aaa9d9842b922295af66c10cf847192cc3fd2f65d0d2936d",
        "url": "https://suno.com/song/ff0a52f1-8590-4ba6-9c19-11ee87414f54",
        "author": "highdefinitionbuttons823 (owner Suno account); crickets: Nox_Sound",
        "license": "Owner-supplied Suno Pro music + CC0-1.0 effects; see sfx/noctina-night-CREDITS.md"
      },
      "recipe": "Add the preserved music and cricket layers with unity gains, mono mean, PCM16, MP3 128kbps with gapless header. Owner-selected dusk version, no owl, wing or coyote layer; 2026-09-28.",
      "seedOnly": true,
      "sha256": "b912f6c602c9638738a65a604b5826e5ec6b2516e9e01bcc31ba5b085f138475",
      "bytes": 1347499
    },
    {
      "id": "interior-hearth",
      "label": "Quiet hearth fire",
      "cohort": "starter-1",
      "role": "environment",
      "bed": {
        "url": "sfx/smithy-fire-v2.mp3",
        "gain": 0.55,
        "loopStart": 0,
        "loopEnd": 9.005,
        "maxSeconds": 20,
        "channels": 1,
        "maxBytes": 500000,
        "maxDecodedBytes": 4000000
      },
      "contains": [
        "fire"
      ],
      "enclosures": [
        "covered",
        "sealed"
      ],
      "settings": [
        "interior"
      ],
      "biomes": [
        "temperate",
        "arid",
        "tropical",
        "frozen",
        "unspecified"
      ],
      "from": 0,
      "to": 1440,
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "loop": true,
        "mix": true
      },
      "source": {
        "sha256": "36d5ccc8ffa065a642d46d2b8d15cda7556184f30662fe2bf3bf25c5236611c7",
        "url": "https://nox-sound-design.itch.io/essentials-series-sfx-nox-sound",
        "author": "Nox_Sound",
        "license": "CC0-1.0"
      },
      "recipe": "mono; DC removal; 1 s tail/head crossfade; RMS -32 dBFS; libmp3lame 128 kbps",
      "seedOnly": true,
      "defaultFor": "habitable-interior",
      "sha256": "d2b017fce86f4ef9eef89b669733c35433dae5517fc85ff0ba3e2852b9df23cd",
      "bytes": 145152
    },
    {
      "cohort": "starter-1",
      "enclosures": [
        "sealed",
        "covered"
      ],
      "settings": [
        "interior"
      ],
      "biomes": [
        "temperate",
        "arid",
        "tropical",
        "frozen",
        "unspecified"
      ],
      "from": 0,
      "to": 1440,
      "seedOnly": true,
      "id": "alchemist",
      "label": "Alchemistâ€™s quiet simmer",
      "role": "feature",
      "contains": [
        "water"
      ],
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "mix": true,
        "loop": true
      },
      "source": {
        "sha256": "65d72c6fe9be3ce94aed509fd36efbffdf894d17e7babf84ecb105e2d205fb68",
        "url": "https://bigsoundbank.com/boiling-water-s0149.html",
        "author": "Joseph SARDIN",
        "license": "CC0-1.0"
      },
      "recipe": "Only source 0149, high-pass 100 Hz and low-pass 2400 Hz; no straw-bubble layer. Existing preparation: 1.5 s crossfade, RMS -35, peak ceiling -10 dBFS.",
      "bed": {
        "url": "sfx/alchemist-bubbles-v2.mp3",
        "gain": 0.55,
        "loopStart": 0,
        "loopEnd": 11.841,
        "maxSeconds": 15,
        "channels": 1,
        "maxBytes": 250000,
        "maxDecodedBytes": 6000000
      },
      "sha256": "f25b24d399700bb9a7654b6e70a050c124270be04ebe9547be1e39bf2e6d8245",
      "bytes": 190588
    },
    {
      "cohort": "starter-1",
      "enclosures": [
        "sealed",
        "covered"
      ],
      "settings": [
        "interior"
      ],
      "biomes": [
        "temperate",
        "arid",
        "tropical",
        "frozen",
        "unspecified"
      ],
      "from": 0,
      "to": 1440,
      "seedOnly": true,
      "id": "alchemist-glass",
      "label": "Alchemistâ€™s gentle glass clinks",
      "role": "accent",
      "contains": [],
      "needsAny": [],
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "mix": true
      },
      "source": {
        "sha256": "9482ce19c5ba9c264c516c166ec6d5668aec6fc94f23e27307e1fb2a1c355e1d",
        "url": "https://bigsoundbank.com/bottle-clink-s0487.html",
        "author": "Joseph SARDIN",
        "license": "CC0-1.0"
      },
      "recipe": "mono mean; DC removal; trim below -50 dB of sample peak with 20 ms pre-roll; RMS -32 dBFS, peak ceiling -12 dBFS; raised-cosine fades 3 ms in / 40 ms out; 0.25 s silence between samples; libmp3lame 128 kbps mono with Xing/LAME gapless header, no ID3",
      "trigger": "ambient",
      "rain": "play",
      "pattern": {
        "kind": "single"
      },
      "gap": [
        45,
        90
      ],
      "sprite": {
        "url": "sfx/accent-alchemist-glass-v1.mp3",
        "gain": [
          0.35,
          0.55
        ],
        "cuts": [
          [
            0.25,
            0.703
          ],
          [
            0.953,
            1.4125
          ],
          [
            1.6625,
            2.3369
          ],
          [
            2.5869,
            3.3186
          ]
        ],
        "maxSeconds": 5,
        "channels": 1,
        "maxBytes": 100000,
        "maxDecodedBytes": 2000000
      },
      "sha256": "48a9d058d0d32cb591218a5cf023805543c65825a44ca24d6b2e9e5aef4c1ed1",
      "bytes": 57984
    },
    {
      "cohort": "starter-1",
      "enclosures": [
        "sealed",
        "covered"
      ],
      "settings": [
        "interior"
      ],
      "biomes": [
        "temperate",
        "arid",
        "tropical",
        "frozen",
        "unspecified"
      ],
      "from": 0,
      "to": 1440,
      "seedOnly": true,
      "id": "alchemist-entry-bell",
      "label": "Alchemist door bell",
      "role": "accent",
      "contains": [
        "bells"
      ],
      "needsAny": [],
      "approval": {
        "recording": true,
        "rights": true,
        "contents": true,
        "mix": true
      },
      "source": {
        "sha256": "4f69082ff4c06c728efa39bbe7cc1b5b9513bf2ea5619767e860872fd3e3f43f",
        "url": "https://bigsoundbank.com/carillon-commercant-s3588.html",
        "author": "Joseph SARDIN",
        "license": "CC0-1.0"
      },
      "recipe": "mono mean; DC removal; trim below -50 dB of sample peak with 20 ms pre-roll; RMS -30 dBFS, peak ceiling -12 dBFS; raised-cosine fades 8 ms in / 8 ms out; 0.25 s silence between samples; libmp3lame 128 kbps mono with Xing/LAME gapless header, no ID3; owner-selected editor curve: original prepared lossless v1 region [0.25, 1.5343958333333334]; cosine points (0,1), (0.001,1), (1.2843958333333334,0), rendered with dev/audio-envelope.js; preserve 0.25 s padding each side and original source level; encode once from PCM",
      "trigger": "cued",
      "rain": "play",
      "pattern": {
        "kind": "single"
      },
      "gap": [
        45,
        90
      ],
      "sprite": {
        "url": "sfx/alchemist-entry-bell-v5.mp3",
        "gain": [
          0.65,
          0.65
        ],
        "cuts": [
          [
            0.25,
            1.5344
          ]
        ],
        "maxSeconds": 2,
        "channels": 1,
        "maxBytes": 40000,
        "maxDecodedBytes": 400000
      },
      "sha256": "25672994894ba24531164c8ac0731548373b9cd7b65ca61733e55cdb5534caa7",
      "bytes": 29568
    }
  ],
  "version": "d019d9c713c84510b38c"
};
