// capability_bible.js — the unified capability reference (TODO #10). Spells AND abilities share it:
// they have NO intrinsic difference (kind is a cosmetic display tag; cost + isMagical are the real
// axes), so one registry holds both. Merged from spell_bible.js + ability_bible.js (v1.222). Keyed by
// BASE name (parenthetical stripped, lowercased) so it overlays the SPELLS strings and the
// [SPELL_USED:] matcher with no refactor. Genuinely-different domains (items, creatures, professions)
// get their OWN *_bible files — capability = spells+abilities; entities are separate.
//
// Two consumers, one source: GM-authoritative prompt injection on cast/use (anti-drift) + the player
// card / bible_study viewer (bibleCardHTML). GM-invented capabilities canonize write-once into the
// per-campaign overlay worldState.capabilityBible ([SPELL_DEF:]), which capabilityLookup prefers.
//
// ENTRY SCHEMA: kind ("spell"|"ability") | tier (0=cantrip/at-will, 1..4) | cost (at-will|slot|
// passive|per-rest|per-day|pool...) | isMagical (bool; AUTHORING RULE: true if it lights up under
// Detect Magic / is Dispel-targetable) | category (LIST of traditions: arcane|divine|primal|
// necromantic|martial|racial — the gate for limiting an enemy caster's menu; e.g. Turn Undead is
// ["divine","necromantic"], mundane abilities are ["martial"], innate heritage traits are ["racial"]
// (drawn by no caster tradition, so they never surface in an enemy caster's menu)) | range | targets | duration |
// effect | dice? | save?

var CAPABILITY_BIBLE={
  // ── Spells (by tier) ──
  "bone whisper":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["necromantic"],range:"touch",targets:"a skull or bone fragment",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Touch a skull or bone fragment to sense an echo of its owner's final moments — a fleeting impression, not a conversation."},
  "booming blade":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"self (5ft melee)",targets:"1 creature you hit",duration:"until the end of your next turn",save:"N/A",dice:"weapon + 1d8 thunder if it moves",effect:"A melee weapon attack sheathed in thunder; if the target willingly moves before the end of your next turn, it takes 1d8 thunder."},
  "chill touch":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["necromantic"],range:"120ft",targets:"1 creature",duration:"1 round",save:"N/A",dice:"1d8 necrotic",effect:"A ghostly hand (ranged spell attack); 1d8 necrotic and the target cannot regain HP until the start of your next turn. Undead also have disadvantage on attacks against you until then."},
  "druidcraft":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["primal"],range:"30ft",targets:"nature / a point",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Minor nature magic: predict the next 24h weather, make a flower bloom, create a harmless sensory effect, or light/snuff a small flame."},
  "fire bolt":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"120ft",targets:"1 creature or object",duration:"instantaneous",save:"N/A",dice:"1d10 fire",effect:"A ranged spell attack hurling a mote of fire; 1d10 fire on a hit. Ignites unattended flammable objects. Damage scales with caster level, not slots."},
  "grave touch":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["necromantic"],range:"30ft",targets:"1 creature",duration:"1 round",save:"CON or disadvantage",dice:"N/A",effect:"A chill of the grave; the target makes a CON save or has disadvantage on its next attack roll."},
  "guidance":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["divine"],range:"touch",targets:"1 willing creature",duration:"concentration, up to 1 min",save:"N/A",dice:"+1d4 to one check",effect:"Once before the spell ends, the target adds 1d4 to one ability check of its choice."},
  "mage hand":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"30ft",targets:"a spectral hand",duration:"1 minute",save:"N/A",dice:"N/A",effect:"Conjure a floating spectral hand that can manipulate objects, open unlocked doors/containers, and carry up to 10 lb. It cannot attack, activate magic items, or wield weapons."},
  "message":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"120ft",targets:"1 creature",duration:"1 round",save:"N/A",dice:"N/A",effect:"Whisper a short message to one creature within range that only it hears; it may whisper a one-line reply only you hear. Requires a clear path to the target (blocked by total cover). Does NOT reach beyond 120ft — it is not telepathy or long-distance sending."},
  "minor illusion":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"30ft",targets:"a sound or a 5ft image",duration:"1 minute",save:"N/A",dice:"N/A",effect:"Create either a sound or a static visual image no larger than a 5ft cube; an investigation check discerns it is false."},
  "prestidigitation":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"10ft",targets:"an object or point",duration:"up to 1 hour",save:"N/A",dice:"N/A",effect:"Minor magical tricks: light or snuff a small flame, clean or soil an object, chill/warm/flavor food, make a harmless sensory effect, or a trivial mark."},
  "produce flame":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["primal"],range:"30ft",targets:"1 creature",duration:"10 minutes (as light)",save:"N/A",dice:"1d8 fire",effect:"A flame in your hand sheds light; you may hurl it as a ranged spell attack for 1d8 fire (ending the spell)."},
  "ray of frost":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"60ft",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"1d8 cold",effect:"A ranged spell attack; 1d8 cold on a hit and the target's speed drops by 10ft until the start of your next turn."},
  "sacred flame":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["divine"],range:"60ft",targets:"1 creature",duration:"instantaneous",save:"DEX for none",dice:"1d8 radiant",effect:"Radiant light falls on a creature you can see; it makes a DEX save or takes 1d8 radiant. The target gains no benefit from cover."},
  "shillelagh":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["primal"],range:"touch",targets:"your club or quarterstaff",duration:"1 minute",save:"N/A",dice:"1d8",effect:"Your wooden club or quarterstaff becomes magical: use your spellcasting mod for its attacks and it deals 1d8 for the duration."},
  "spare the dying":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["divine"],range:"touch",targets:"1 creature at 0 HP",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Stabilize a creature at 0 HP (it no longer needs death saves). No effect on undead or constructs."},
  "thaumaturgy":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["divine"],range:"30ft",targets:"self / nearby",duration:"up to 1 minute",save:"N/A",dice:"N/A",effect:"A minor divine display: boom your voice, flicker flames, cause tremors, sound a phantom noise, or fling open unlocked doors/windows."},
  "thorn whip":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["primal"],range:"30ft",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"1d6 piercing",effect:"A vine lashes out (melee spell attack at range); 1d6 piercing and, if the target is Large or smaller, you pull it up to 10ft toward you."},
  "toll the dead":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["necromantic"],range:"60ft",targets:"1 creature",duration:"instantaneous",save:"WIS for none",dice:"1d8 necrotic (1d12 if wounded)",effect:"A mournful bell tolls; the target makes a WIS save or takes 1d8 necrotic — 1d12 if it is already below its hit point maximum."},
  "absorb elements":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"1 round",save:"N/A",dice:"+1d6 (absorbed type)",effect:"A reaction when you take acid, cold, fire, lightning, or thunder damage: gain resistance to that type until your next turn, and your next melee hit deals +1d6 of it."},
  "bleed":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["necromantic"],range:"30ft",targets:"1 creature",duration:"1d10 turns or until cancelled",save:"N/A",dice:"1d4 necrotic per turn",effect:"The target bleeds from every orifice, taking 1d4 necrotic at the start of each of its turns for 1d10 turns or until you cancel it."},
  "bless":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["divine"],range:"30ft",targets:"up to 3 creatures",duration:"concentration, up to 1 min",save:"N/A",dice:"+1d4",effect:"Up to three creatures you choose add 1d4 to their attack rolls and saving throws for the duration."},
  "cause fear":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["necromantic"],range:"60ft",targets:"1 creature",duration:"concentration, up to 1 min",save:"WIS or frightened",dice:"N/A",effect:"A creature (not undead or construct) makes a WIS save or is frightened of you, repeating the save at the end of each of its turns."},
  "charm person":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"30ft",targets:"1 humanoid",duration:"1 hour",save:"WIS negates",dice:"N/A",effect:"A humanoid makes a WIS save (advantage if you or your allies are fighting it) or is charmed, regarding you as a friendly acquaintance, until the spell ends or you harm it."},
  "chromatic orb":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"90ft",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"3d8 (chosen element)",effect:"A ranged spell attack hurling a 4-inch orb of acid, cold, fire, lightning, poison, or thunder (you choose) for 3d8."},
  "cure wounds":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["divine","primal"],range:"touch",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"1d8 + spell mod healing",effect:"Touch a creature to restore 1d8 + your spellcasting modifier HP. No effect on undead or constructs."},
  "disguise self":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"1 hour",save:"N/A",dice:"N/A",effect:"Illusorily change your appearance — body and clothing/gear — until the spell ends. Physical inspection or an investigation check reveals the disguise."},
  "divine smite":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["divine"],range:"self (on a melee hit)",targets:"1 creature you hit",duration:"instantaneous",save:"N/A",dice:"2d8 radiant (+1d8 vs undead/fiends)",effect:"When you hit with a melee weapon attack, expend a slot to deal +2d8 radiant (more with a higher slot; +1d8 extra against undead or fiends)."},
  "ensnaring strike":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["primal"],range:"self (next weapon hit)",targets:"1 creature you hit",duration:"concentration, up to 1 min",save:"STR or restrained",dice:"1d6 piercing/turn",effect:"The next time you hit with a weapon this turn, thorny vines sprout; the target makes a STR save or is restrained, taking 1d6 piercing each turn until it breaks free."},
  "entangle":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["primal"],range:"90ft",targets:"20ft square",duration:"concentration, up to 1 min",save:"STR or restrained",dice:"N/A",effect:"Grasping weeds fill a 20ft square (difficult terrain); a creature there makes a STR save or is restrained until it breaks free with a STR check."},
  "faerie fire":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["primal"],range:"60ft",targets:"20ft cube",duration:"concentration, up to 1 minute",save:"DEX for none",dice:"N/A",effect:"Each creature in the cube that fails a DEX save is outlined in light: attacks against it have advantage and it cannot benefit from invisibility."},
  "false life":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["necromantic"],range:"self",targets:"self",duration:"1 hour",save:"N/A",dice:"1d4+4 temp HP",effect:"Gain 1d4+4 temporary hit points for the duration."},
  "feather fall":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"60ft",targets:"up to 5 falling creatures",duration:"1 minute",save:"N/A",dice:"N/A",effect:"A reaction when you or nearby creatures fall: up to five falling creatures descend 60ft per round and take no damage on landing."},
  "guiding bolt":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["divine"],range:"120ft",targets:"1 creature",duration:"1 round (the advantage)",save:"N/A",dice:"4d6 radiant",effect:"A ranged spell attack; 4d6 radiant on a hit, and the next attack roll against that target before the end of your next turn has advantage."},
  "hail of thorns":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["primal"],range:"self (next ranged hit)",targets:"5ft radius around the target",duration:"instantaneous",save:"DEX for half",dice:"1d10 piercing",effect:"Your next ranged weapon hit bursts into thorns: creatures within 5ft of the target take 1d10 piercing (DEX save half)."},
  "healing word":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["divine"],range:"60ft",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"1d4 + spell mod healing",effect:"A bonus action: one creature you can see regains 1d4 + your spellcasting modifier HP. No effect on undead or constructs."},
  "hunter's mark":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["primal"],range:"90ft",targets:"1 creature",duration:"concentration, up to 1 hour",save:"N/A",dice:"+1d6 weapon damage",effect:"Mark one creature you can see. Your weapon attacks against THAT target deal +1d6 damage, and you have advantage to track it. EXCLUSIVE: only one Hunter's Mark can exist at a time — casting it again moves the mark and ends the previous one. If the target drops, you may move the mark to a new creature as a bonus action."},
  "inflict wounds":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["necromantic"],range:"touch",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"3d10 necrotic",effect:"A melee spell attack; on a hit, the target takes 3d10 necrotic."},
  "magic missile":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"120ft",targets:"up to 3 creatures",duration:"instantaneous",save:"N/A",dice:"1d4+1 force per dart",effect:"Three darts of force strike targets you can see, one dart each or combined; each auto-hits for 1d4+1 force. No attack roll, no save."},
  "ray of sickness":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["necromantic"],range:"60ft",targets:"1 creature",duration:"instantaneous",save:"CON or poisoned",dice:"1d8 necrotic",effect:"A ray of sickly energy (ranged spell attack); 1d8 necrotic and, on a failed CON save, the target is poisoned until the end of your next turn."},
  "shield":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"1 round",save:"N/A",dice:"N/A",effect:"A reaction (cast when hit or targeted by magic missile): +5 AC until the start of your next turn, INCLUDING against the triggering attack, and negates magic missile."},
  "shield of faith":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["divine"],range:"60ft",targets:"1 creature",duration:"concentration, up to 10 min",save:"N/A",dice:"N/A",effect:"A shimmering field grants a creature you can see +2 AC for the duration."},
  "silent image":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"60ft",targets:"a 15ft-cube image",duration:"concentration, up to 10 min",save:"N/A",dice:"N/A",effect:"Create a purely visual illusion no larger than a 15ft cube; you can move it. Physical interaction or an investigation check reveals it is false."},
  "thunderwave":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"self (15ft cube)",targets:"creatures in a 15ft cube",duration:"instantaneous",save:"CON for half",dice:"2d8 thunder",effect:"A wave of force: 2d8 thunder (CON save half); creatures that fail are also pushed 10ft away. Audible out to 300ft."},
  "aid":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["divine"],range:"30ft",targets:"up to 3 creatures",duration:"8 hours",save:"N/A",dice:"N/A",effect:"Bolster up to three creatures: their hit point maximum AND current HP each increase by 5 for 8 hours."},
  "barkskin":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["primal"],range:"touch",targets:"1 creature",duration:"concentration, up to 1 hour",save:"N/A",dice:"N/A",effect:"The target's AC cannot be lower than 16 for the duration, regardless of armor worn."},
  "blindness":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["necromantic"],range:"30ft",targets:"1 creature",duration:"1 minute",save:"CON or blinded",dice:"N/A",effect:"The target makes a CON save or is blinded for 1 minute, repeating the save at the end of each of its turns."},
  "darkness":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"60ft",targets:"15ft-radius sphere",duration:"concentration, up to 10 min",save:"N/A",dice:"N/A",effect:"Magical darkness fills a 15ft-radius sphere; it blocks darkvision and ordinary light cannot illuminate it."},
  "find steed":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["divine"],range:"30ft",targets:"a summoned steed",duration:"until dismissed or 0 HP",save:"N/A",dice:"N/A",effect:"Summon a loyal spirit steed (warhorse, pony, etc.) bonded to you telepathically; it serves as a mount and ally until it drops to 0 HP or you dismiss it."},
  "hold person":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane","divine"],range:"60ft",targets:"1 humanoid",duration:"concentration, up to 1 minute",save:"WIS or paralyzed",dice:"N/A",effect:"A humanoid you can see must make a WIS save or be paralyzed. It repeats the save at the end of each of its turns, ending the effect on a success. Humanoids only — not beasts, undead, or monstrosities."},
  "invisibility":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"touch",targets:"1 creature",duration:"concentration, up to 1 hour",save:"N/A",dice:"N/A",effect:"A creature you touch becomes invisible until it attacks, casts a spell, or the spell ends. Anything it is wearing or carrying is invisible too."},
  "knock":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"60ft",targets:"1 lock, door, chest, or manacle",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"A sharp clang unlocks or unbars one locked/stuck object within range. The knock is audible out to 300ft."},
  "lesser restoration":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["divine"],range:"touch",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"End one disease OR one condition on a creature: blinded, deafened, paralyzed, or poisoned."},
  "magic weapon":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["divine"],range:"touch",targets:"1 nonmagical weapon",duration:"concentration, up to 1 hour",save:"N/A",dice:"N/A",effect:"A nonmagical weapon becomes a magic weapon with +1 to attack and damage rolls for the duration."},
  "mirror image":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"1 minute",save:"N/A",dice:"N/A",effect:"Three illusory duplicates flit around you; when something targets you, an attack may strike a duplicate instead (destroying it) rather than you."},
  "misty step":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"A bonus action: teleport up to 30ft to an unoccupied space you can see. Line of sight required — you cannot step through a wall you can't see past."},
  "moonbeam":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["primal"],range:"120ft",targets:"5ft-radius cylinder",duration:"concentration, up to 1 min",save:"CON for half",dice:"2d10 radiant",effect:"A 5ft beam of moonlight; a creature that enters it or starts its turn there takes 2d10 radiant (CON save half). You may move the beam 60ft each turn."},
  "pass without trace":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["primal"],range:"self",targets:"self and allies within 30ft",duration:"concentration, up to 1 hour",save:"N/A",dice:"N/A",effect:"You and allies within 30ft gain +10 to Stealth and cannot be tracked by nonmagical means, leaving no tracks or scent."},
  "ray of enfeeblement":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["necromantic"],range:"60ft",targets:"1 creature",duration:"concentration, up to 1 min",save:"CON to end",dice:"N/A",effect:"A ray of enervation (ranged spell attack); the target deals only half damage with STR-based weapon attacks until the spell ends (CON save each turn to end it early)."},
  "rot":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["necromantic"],range:"30ft",targets:"1 creature",duration:"1d10 turns or until cancelled",save:"N/A",dice:"1d6 necrotic per turn",effect:"The greater Bleed: the target festers with necrotic sores, taking 1d6 necrotic at the start of each of its turns for 1d10 turns or until cancelled."},
  "scorching ray":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"120ft",targets:"up to 3 creatures",duration:"instantaneous",save:"N/A",dice:"2d6 fire per ray",effect:"Three rays of fire; make a separate ranged spell attack for each, 2d6 fire per hit. Split among one or more targets."},
  "shackles of bone":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["necromantic"],range:"60ft",targets:"1 creature",duration:"until a STR check breaks free",save:"STR to break free",dice:"N/A",effect:"Skeletal arms erupt from earth or wall to pin the target prone or against a surface; it is restrained until it snaps the bones with a STR check."},
  "shadow blade":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"concentration, up to 1 min",save:"N/A",dice:"2d8 psychic",effect:"Weave shadows into a sword of solidified gloom (2d8 psychic, finesse, thrown 20/60); you have advantage on attacks with it in dim light or darkness."},
  "shadow step":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["necromantic","arcane"],range:"30ft",targets:"self",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"From an area of dim light or darkness, teleport up to 30ft to another area of dim light or darkness you can see."},
  "silence":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["primal"],range:"120ft",targets:"20ft-radius sphere",duration:"concentration, up to 10 min",save:"N/A",dice:"N/A",effect:"No sound can be created within or pass into a 20ft sphere. Creatures inside are deafened and cannot cast spells with verbal components; thunder damage is negated there."},
  "spike growth":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["primal"],range:"150ft",targets:"20ft radius",duration:"concentration, up to 10 min",save:"N/A",dice:"2d4 piercing per 5ft",effect:"The ground in a 20ft radius sprouts spikes (difficult terrain); a creature takes 2d4 piercing for every 5ft it travels through the area."},
  "spiritual weapon":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["divine"],range:"60ft",targets:"a spectral weapon",duration:"1 minute",save:"N/A",dice:"1d8 + spell mod force",effect:"Create a floating spectral weapon; a bonus action moves it 20ft and makes a melee spell attack for 1d8 + your spellcasting modifier force."},
  "aura of vitality":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["divine"],range:"self (30ft aura)",targets:"you or an ally in 30ft",duration:"concentration, up to 1 min",save:"N/A",dice:"2d6 healing",effect:"For the duration, use a bonus action to heal one creature within 30ft for 2d6."},
  "bestow curse":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["necromantic"],range:"touch",targets:"1 creature",duration:"concentration, up to 1 min",save:"WIS negates",dice:"N/A",effect:"WIS save or cursed — choose: disadvantage on one ability's checks and saves, OR vulnerability to one damage type, OR the target wastes its action on a roll of 1-4."},
  "call lightning":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["primal"],range:"120ft",targets:"5ft-radius strike point",duration:"concentration, up to 10 min",save:"DEX for half",dice:"3d10 lightning",effect:"Summon a storm cloud; each turn as an action, call down a bolt — creatures within 5ft of the chosen point take 3d10 lightning (DEX save half)."},
  "conjure animals":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["primal"],range:"60ft",targets:"summoned beasts",duration:"concentration, up to 1 hour",save:"N/A",dice:"N/A",effect:"Summon fey spirits in beast form (their total power scaling with the slot) that obey your commands and fight for you until the spell ends."},
  "conjure barrage":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["primal"],range:"self (60ft cone)",targets:"creatures in a 60ft cone",duration:"instantaneous",save:"DEX for half",dice:"3d8 (weapon type)",effect:"Hurl a weapon or ammunition to conjure a barrage; each creature in a 60ft cone takes 3d8 of the weapon's damage type (DEX save half)."},
  "counterspell":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["arcane"],range:"60ft",targets:"1 creature casting a spell",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"A reaction when you see a creature within 60ft casting: automatically negate a spell of 3rd tier or lower. For a higher-tier spell, make a spellcasting ability check (DC 10 + that spell's tier) to interrupt it."},
  "death walk":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["necromantic"],range:"self",targets:"self",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Step between the worlds of the living and dead: move up to INT x 5 ft unimpeded through creatures, objects, and difficult terrain, ignoring opportunity attacks."},
  "dispel magic":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["arcane","divine"],range:"120ft",targets:"1 creature, object, or magical effect",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"End one ongoing spell of 3rd tier or lower on the target automatically. For a higher-tier effect, make a spellcasting ability check (DC 10 + that spell's tier). Only affects ongoing magical effects, not instantaneous ones already resolved."},
  "fireball":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["arcane"],range:"150ft",targets:"20ft-radius sphere",duration:"instantaneous",save:"DEX for half",dice:"8d6 fire",effect:"A bright streak blossoms into flame at a point you choose; each creature in a 20ft-radius sphere makes a DEX save, taking 8d6 fire (half on a success). Ignites unattended flammable objects."},
  "fly":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["arcane"],range:"touch",targets:"1 creature",duration:"concentration, up to 10 min",save:"N/A",dice:"N/A",effect:"The target gains a flying speed of 60ft for the duration."},
  "lethe's kiss":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["arcane"],range:"touch or 30ft",targets:"1 creature",duration:"instantaneous",save:"WIS negates",dice:"N/A",effect:"WIS save or the target loses up to 15 minutes of memory per point of your INT modifier — recent events simply vanish. The narrative-only sibling of Oubliate."},
  "lightning arrow":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["primal"],range:"self (next ranged attack)",targets:"target + creatures within 10ft",duration:"instantaneous",save:"DEX for half (splash)",dice:"4d8 lightning",effect:"Your next ranged attack becomes lightning: 4d8 lightning on a hit (2d8 on a miss), and creatures within 10ft of the target take 2d8 (DEX save half)."},
  "miasma":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["necromantic"],range:"60ft",targets:"10x10ft cloud (+1ft per INT mod)",duration:"concentration, up to 1 min",save:"WIS or disadvantage",dice:"N/A",effect:"A cloud of despair; creatures inside are wracked with grief and hopelessness — WIS save or act at disadvantage while within it."},
  "plant growth":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["primal"],range:"150ft",targets:"100ft radius",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Overgrow a 100ft radius into difficult terrain (movement quartered) — or, over 8 hours, enrich the land for a year of bountiful harvest."},
  "revivify":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["divine"],range:"touch",targets:"1 creature dead <=1 min",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Return a creature that died within the last minute to life with 1 HP. Cannot restore missing body parts, revive undead/constructs, or one dead of old age."},
  "speak with dead":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["necromantic"],range:"10ft",targets:"1 corpse",duration:"10 minutes",save:"N/A",dice:"N/A",effect:"Ask a corpse (with a mouth, dead no more than 10 days, not undead) up to five questions; it answers briefly and cryptically from what it knew in life."},
  "spirit guardians":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["divine"],range:"self (15ft radius)",targets:"creatures in a 15ft aura",duration:"concentration, up to 10 min",save:"WIS for half",dice:"3d8 radiant/necrotic",effect:"Spectral guardians swirl in a 15ft aura; hostile creatures there move at half speed and take 3d8 (WIS save half) when they enter or start their turn there."},
  "vampiric touch":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["necromantic"],range:"touch",targets:"1 creature",duration:"concentration, up to 1 min",save:"N/A",dice:"3d6 necrotic (heal half)",effect:"A melee spell attack; 3d6 necrotic and you regain HP equal to half the damage dealt. You can attack again each turn while you concentrate."},
  "wave of scarabs":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["necromantic"],range:"self (30ft cone)",targets:"creatures in a 30ft cone",duration:"instantaneous",save:"DEX for half",dice:"3d6 necrotic",effect:"A swarm of spectral scarabs erupts in a 30ft cone; each creature takes 3d6 necrotic (DEX save half)."},
  "oubliate":{kind:"spell",tier:4,cost:"slot",isMagical:true,category:["arcane"],range:"touch or 30ft",targets:"1 creature",duration:"instantaneous",save:"WIS negates",dice:"N/A",effect:"WIS save or surgically erase ONE specific person or event from the target's memory entirely (the engine scrubs it via [NPC_FORGET:]); they cannot recall it even when reminded."},
  "possess thrall":{kind:"spell",tier:4,cost:"slot",isMagical:true,category:["necromantic"],range:"one of your thralls",targets:"self (mind projected)",duration:"1 turn per INT point or until you withdraw",save:"N/A",dice:"N/A",effect:"Project your mind into one of your undead thralls, seeing and speaking through it; your own body lies in suspended animation until you withdraw."},
  "rigor mortis":{kind:"spell",tier:4,cost:"slot",isMagical:true,category:["necromantic"],range:"60ft",targets:"1 creature",duration:"1d4 + caster level turns",save:"CON or incapacitated",dice:"N/A",effect:"CON save or the target seizes rigid and incapacitated for 1d4 + your level turns."},
  "sleep of the dead":{kind:"spell",tier:4,cost:"slot",isMagical:true,category:["necromantic"],range:"touch",targets:"self or 1 creature",duration:"caster level + INT + INT mod turns",save:"N/A",dice:"N/A",effect:"Feign death on yourself or a creature you touch — indistinguishable from a true corpse (no breath, no pulse). A self-cast always lasts the full duration."},
  // ── Abilities ──
  "arcane bolt":{kind:"ability",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"120ft",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"1d8 force",effect:"A ranged spell attack (INT vs AC); 1d8 force on a hit. The sorcerer's reliable at-will strike."},
  "arcane shield":{kind:"ability",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"until hit",save:"N/A",dice:"N/A",effect:"A shimmer of force absorbs the next 5 damage you take, then dissipates. Raised as a reaction."},
  "blink":{kind:"ability",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"30ft",targets:"self",duration:"instantaneous",save:"DC 15 DEX or arrive off-target",dice:"N/A",effect:"Teleport up to 30ft to a space you can see. On a failed DC 15 DEX check you arrive at a nearby unintended spot."},
  "death sight":{kind:"ability",tier:0,cost:"passive",isMagical:true,category:["necromantic"],range:"60ft",targets:"area",duration:"N/A",save:"N/A",dice:"N/A",effect:"Sense undead, corpses, and death-taint within 60ft without seeing them, and gain advantage on Arcana/Lore checks about undead, curses, or death magic."},
  "divine sense":{kind:"ability",tier:0,cost:"per-rest",isMagical:true,category:["divine"],range:"60ft",targets:"area",duration:"until your next turn",save:"N/A",dice:"N/A",effect:"Sense the location of any undead, fiend, or celestial within 60ft, and any consecrated or desecrated place, until the end of your next turn."},
  "drain life":{kind:"ability",tier:0,cost:"at-will",isMagical:true,category:["necromantic"],range:"30ft",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"1d6 necrotic",effect:"A melee or 30ft necrotic touch; deal 1d6 necrotic and regain HP equal to half the damage dealt."},
  "druidic":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["primal"],range:"N/A",targets:"N/A",duration:"N/A",save:"N/A",dice:"N/A",effect:"You know Druidic, the secret language of druids, and can leave hidden messages (via marks and signs in nature) that only those who know it can read."},
  "evasion":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["martial"],range:"N/A",targets:"N/A",duration:"N/A",save:"N/A",dice:"N/A",effect:"On a FAILED DEX save against an area effect, take half damage instead of full. (Class-feature Evasion later upgrades this to zero on a success.)"},
  "fire lance":{kind:"ability",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"60ft",targets:"1 creature or object",duration:"instantaneous",save:"N/A",dice:"1d10 fire",effect:"A lance of flame; 1d10 fire on a hit and ignites unattended flammable targets."},
  "intimidating presence":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"30ft",targets:"1 creature",duration:"N/A",save:"CHA contest",dice:"N/A",effect:"A CHA check to terrify one creature. On a success it is shaken (-2 to all rolls) until it can no longer see you or the scene ends."},
  "lay on hands":{kind:"ability",tier:0,cost:"pool, refreshes on a long rest",isMagical:true,category:["divine"],range:"touch",targets:"1 creature",duration:"N/A",save:"N/A",dice:"N/A",effect:"Draw from a healing pool of 5 × your level HP: touch to restore HP, or spend 5 points to cure one disease or neutralize one poison. Cannot harm undead with it here."},
  "lockpick":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"N/A",targets:"N/A",duration:"N/A",save:"N/A",dice:"N/A",effect:"Open locks and disarm mechanical traps with a DEX check against the device's DC. Requires thieves' tools."},
  "power strike":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"N/A",targets:"1 attack",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"On a declared attack, add +1d6 damage on a hit. Declared before the roll."},
  "rage":{kind:"ability",tier:0,cost:"per-rest",isMagical:false,category:["martial"],range:"N/A",targets:"N/A",duration:"3 rounds",save:"N/A",dice:"N/A",effect:"Enter a battle fury: +2 STR, +2 melee damage, and you push through pain (resist physical damage, ignore first wounds). Lasts 3 rounds. Ends early if you take no hostile action."},
  "raise thrall":{kind:"ability",tier:0,cost:"at-will",isMagical:true,category:["necromantic"],range:"10ft",targets:"1 fresh corpse",duration:"N/A",save:"N/A",dice:"N/A",effect:"Animate a fresh corpse within 10ft as a zombie thrall that follows basic commands. Requires a body present. ONE thrall at a time (until the archetype expands it); the thrall collapses if you fall unconscious."},
  "reckless attack":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"N/A",targets:"your attacks this turn",duration:"until your next turn",save:"N/A",dice:"N/A",effect:"Attack with advantage this turn; in exchange, attacks against you have advantage until your next turn."},
  "shield wall":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"N/A",targets:"N/A",duration:"until your next turn",save:"N/A",dice:"N/A",effect:"Reduce all incoming damage by 3 until the start of your next turn. Requires a shield or braced stance."},
  "sneak attack":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"N/A",targets:"1 attack",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Double the attack's damage dice when you have advantage, are unseen, or the target is flanked by an ally. Once per turn."},
  "speak with animals":{kind:"ability",tier:0,cost:"at-will",isMagical:true,category:["primal"],range:"nearby beasts",targets:"N/A",duration:"conversational",save:"N/A",dice:"N/A",effect:"Comprehend and verbally communicate with beasts. They can share what they have sensed recently, but are limited by animal intelligence and perspective."},
  "trackless step":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["martial"],range:"N/A",targets:"N/A",duration:"N/A",save:"N/A",dice:"N/A",effect:"Leave no trail in natural terrain; cannot be tracked by nonmagical means while moving through wilderness at a careful pace."},
  "turn undead":{kind:"ability",tier:0,cost:"per-rest",isMagical:true,category:["divine","necromantic"],range:"30ft",targets:"undead in range",duration:"1 minute",save:"WIS (DC 8 + WIS + proficiency)",dice:"N/A",effect:"Channel Divinity: each undead within 30ft that fails a WIS save must spend its turns fleeing you and cannot willingly move closer, for 1 minute or until it takes damage."},
  "volley":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"N/A",targets:"up to 2 creatures in range",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"With one action, make a ranged attack against up to 2 targets within your weapon's range."},
  "weapon mastery":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["martial"],range:"N/A",targets:"N/A",duration:"N/A",save:"N/A",dice:"N/A",effect:"No penalty for using improvised or unfamiliar weapons — proficient with anything wieldable."},
  "wild shape":{kind:"ability",tier:0,cost:"per-rest",isMagical:true,category:["primal"],range:"self",targets:"self",duration:"hours by level",save:"N/A",dice:"N/A",effect:"Transform into a beast you have seen, up to a CR limit that scales with level. You take on its stats; you revert at 0 HP or when you choose. Gear melds. Cannot cast spells while shaped until high level."},
  // ── Racial capabilities (ANCS references these by base name via racial_caps; single source of truth) ──
  // category "racial" = an innate heritage trait, drawn by no caster tradition (so it never appears in an
  // enemy caster's tradition menu). Clearly-arcane innate castings (Dancing Lights, Hellish Rebuke) keep
  // their real tradition. Recharge (passive / 1-day / at-will) is a per-GRANT property carried on the
  // character entry's display name — the bible pins the MECHANICS (range/targets/effect), not the economy.
  "darkvision":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"60ft",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"See in darkness within 60ft as though it were dim light, in shades of grey. Does not pierce magical darkness."},
  "superior darkvision":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"120ft",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"See in darkness within 120ft as though it were dim light, in shades of grey — the extended sight of the deep-dwelling races."},
  "see in magical darkness":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"60ft",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Your darkvision pierces even magically created darkness."},
  "fey ancestry":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Advantage on saving throws against being charmed, and magic cannot put you to sleep."},
  "keen senses":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Advantage on Perception checks that rely on sight, hearing, or smell."},
  "trance":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"4-hour rest",save:"N/A",dice:"N/A",effect:"Meditate 4 hours (semi-aware) to gain the full benefit of an 8-hour long rest; you do not sleep."},
  "gnomish cunning":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Advantage on Intelligence, Wisdom, and Charisma saving throws against magic."},
  "poison resistance":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Advantage on saving throws against poison, and resistance (half damage) to poison."},
  "stonecunning":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"While underground or touching stone you always know your approximate depth and direction; advantage on checks about the origin or construction of stonework."},
  "dwarven toughness":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"+1 maximum HP per character level."},
  "necrotic resistance":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Resistance (half damage) to necrotic damage."},
  "fire resistance":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Resistance (half damage) to fire damage."},
  "elemental resistance":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Resistance (half damage) to one elemental damage type — fire, cold, lightning, or acid — fixed by your heritage."},
  "small size":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"You are Small: advantage on Stealth to hide behind larger creatures and you can move through a larger creature's space, but you have disadvantage attacking with Heavy weapons."},
  "sunlight sensitivity":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"in direct sunlight",save:"N/A",dice:"N/A",effect:"Disadvantage on attack rolls and on sight-based Perception checks while you, or the thing you are looking at, is in direct sunlight."},
  "mask of the wild":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"You can attempt to hide even when only lightly obscured by natural phenomena — foliage, heavy rain, falling snow, or mist."},
  "unsettling presence":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Your uncanny aspect unnerves others: advantage on Intimidation checks."},
  "undead sense":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"30ft",targets:"area",duration:"always on",save:"N/A",dice:"N/A",effect:"You sense the presence of undead and fiends within 30ft before you see them — roughly where and that they are there, not precisely what."},
  "see invisible":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"sight",targets:"area",duration:"always on",save:"N/A",dice:"N/A",effect:"You perceive invisible creatures and objects as faint, wavering outlines."},
  "abyssal fury":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"while bloodied",save:"N/A",dice:"+1d4",effect:"While below half your maximum HP, your melee attacks deal an extra 1d4 damage."},
  "relentless endurance":{kind:"ability",tier:0,cost:"per-day",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Once per day, when you would be reduced to 0 HP but not killed outright, you drop to 1 HP instead."},
  "camouflage":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"while you hold still",save:"N/A",dice:"N/A",effect:"While you remain motionless you blend into your native surroundings (stump/foliage, stone/rockwork, or shadow by heritage) and count as hidden. Any movement ends it."},
  "draconic breath":{kind:"ability",tier:0,cost:"per-rest",isMagical:false,category:["racial"],range:"15ft cone or 30ft line",targets:"creatures in the area",duration:"instantaneous",save:"DEX for half",dice:"2d6 (element by heritage)",effect:"Exhale destructive energy of your draconic bloodline — a 15ft cone or a 30ft line by heritage; each creature in the area takes 2d6 of your element (fire, cold, lightning, or acid), halved on a successful DEX save. Recharges on a rest."},
  "commune with dead":{kind:"ability",tier:1,cost:"per-day",isMagical:true,category:["racial"],range:"10ft",targets:"one corpse dead less than a day",duration:"up to 1 minute",save:"N/A",dice:"N/A",effect:"Once per day, briefly commune with a recently dead creature; for up to a minute it answers a few questions tersely and truthfully, limited to what it knew in life."},
  "dancing lights":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"120ft",targets:"up to four lights or one glowing form",duration:"1 minute (concentration)",save:"N/A",dice:"N/A",effect:"Create up to four torch-sized lights (or combine them into one vaguely humanoid glow) within range and move them as a bonus action; each sheds dim light in a 10ft radius."},
  "hellish rebuke":{kind:"ability",tier:1,cost:"per-day",isMagical:true,category:["arcane"],range:"60ft",targets:"a creature that damaged you",duration:"instantaneous",save:"DEX for half",dice:"2d10 fire",effect:"As a reaction to taking damage from a creature you can see, wreathe it in hellish flame; it takes 2d10 fire, halved on a successful DEX save."}
};

// Base-name key: strip the display parenthetical, lowercase, trim. Mirrors the [SPELL_USED:] matcher.
function capBaseName(nm){return String(nm||"").replace(/\s*\(.*\)/,"").toLowerCase().trim();}

// The ONE capability lookup — used by the card, the viewer, and both injection blocks. The emergent
// per-campaign overlay (worldState.capabilityBible, filed write-once by [SPELL_DEF:]) wins over the
// static base, so a GM-defined capability — or a GM correction to a base one — is authoritative.
function capabilityLookup(nm){
  var key=capBaseName(nm);
  if(typeof worldState!=="undefined"&&worldState&&worldState.capabilityBible&&worldState.capabilityBible[key])return worldState.capabilityBible[key];
  return (typeof CAPABILITY_BIBLE!=="undefined"&&CAPABILITY_BIBLE[key])||null;
}

// capabilitiesByCategory(cat) — every capability tagged with a tradition (arcane|divine|primal|
// necromantic|martial), across the emergent overlay + static base. This is the gate for limiting a
// rolled enemy caster's menu (e.g. an enemy cleric → the "divine" list). Returns [{name, entry}]
// sorted by name; overlay entries win on name collision.
function capabilitiesByCategory(cat){
  var out=[],seen={};
  function scan(reg){if(!reg)return;for(var key in reg){if(seen[key])continue;var e=reg[key];if(e&&e.category&&e.category.indexOf(cat)>=0){out.push({name:key,entry:e});seen[key]=1;}}}
  scan((typeof worldState!=="undefined"&&worldState&&worldState.capabilityBible)?worldState.capabilityBible:null);
  scan(typeof CAPABILITY_BIBLE!=="undefined"?CAPABILITY_BIBLE:null);
  out.sort(function(a,b){return a.name<b.name?-1:1;});
  return out;
}
