// capability_bible.js — the unified capability reference (TODO #10). Spells AND abilities share it:
// they have NO intrinsic difference (kind is a cosmetic display tag; cost + isMagical are the real
// axes), so one registry holds both. Merged from spell_bible.js + ability_bible.js (v1.222). Keyed by
// BASE name (parenthetical stripped, lowercased) so it overlays the SPELLS strings and the
// [SPELL_USED:] matcher with no refactor. Genuinely-different domains (items, creatures, professions)
// get their OWN *_bible files — capability = spells+abilities; entities are separate.
//
// Two consumers, one source: GM-authoritative prompt injection on cast/use (anti-drift) + the player
// card / bible_study viewer (bibleCardHTML). GM-invented capabilities canonize write-once into the
// per-campaign overlay worldState.capabilityBible ([SPELL_DEF:]), which capabilityLookup prefers.
//
// ENTRY SCHEMA: kind ("spell"|"ability") | tier (0=cantrip/at-will, 1..4) | cost (at-will|slot|
// passive|per-rest|per-day|pool...) | isMagical (bool; AUTHORING RULE: true if it lights up under
// Detect Magic / is Dispel-targetable) | category (LIST of traditions: arcane|divine|primal|
// necromantic|martial|racial — the gate for limiting an enemy caster's menu; e.g. Turn Undead is
// ["divine","necromantic"], mundane abilities are ["martial"], innate heritage traits are ["racial"]
// (drawn by no caster tradition, so they never surface in an enemy caster's menu)) | range | targets | duration |
// effect | dice? | save?

var CAPABILITY_BIBLE={
  // ── Spells (by tier) ──
  "bone whisper":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["necromantic"],range:"touch",targets:"a skull or bone fragment",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Touch a skull or bone fragment to sense an echo of its owner's final moments — a fleeting impression, not a conversation."},
  "booming blade":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"self (5ft melee)",targets:"1 creature you hit",duration:"until the end of your next turn",save:"N/A",dice:"weapon + 1d8 thunder if it moves",effect:"A melee weapon attack sheathed in thunder; if the target willingly moves before the end of your next turn, it takes 1d8 thunder."},
  "chill touch":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["necromantic"],range:"120ft",targets:"1 creature",duration:"1 round",save:"N/A",dice:"1d8 necrotic",effect:"A ghostly hand (ranged spell attack); 1d8 necrotic and the target cannot regain HP until the start of your next turn. Undead also have disadvantage on attacks against you until then."},
  "druidcraft":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["primal"],range:"30ft",targets:"nature / a point",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Minor nature magic: predict the next 24h weather, make a flower bloom, create a harmless sensory effect, or light/snuff a small flame."},
  "fire bolt":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"120ft",targets:"1 creature or object",duration:"instantaneous",save:"N/A",dice:"1d10 fire",effect:"A ranged spell attack hurling a mote of fire; 1d10 fire on a hit. Ignites unattended flammable objects. Damage scales with caster level, not slots."},
  "grave touch":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["necromantic"],range:"30ft",targets:"1 creature",duration:"1 round",save:"CON or disadvantage",dice:"N/A",effect:"A chill of the grave; the target makes a CON save or has disadvantage on its next attack roll."},
  "guidance":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["divine"],range:"touch",targets:"1 willing creature",duration:"concentration, up to 1 min",save:"N/A",dice:"+1d4 to one check",effect:"Once before the spell ends, the target adds 1d4 to one ability check of its choice."},
  "mage hand":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"30ft",targets:"a spectral hand",duration:"1 minute",save:"N/A",dice:"N/A",effect:"Conjure a floating spectral hand that can manipulate objects, open unlocked doors/containers, and carry up to 10 lb. It cannot attack, activate magic items, or wield weapons."},
  "message":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"120ft",targets:"1 creature",duration:"1 round",save:"N/A",dice:"N/A",effect:"Whisper a short message to one creature within range that only it hears; it may whisper a one-line reply only you hear. Requires a clear path to the target (blocked by total cover). Does NOT reach beyond 120ft — it is not telepathy or long-distance sending."},
  "minor illusion":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"30ft",targets:"a sound or a 5ft image",duration:"1 minute",save:"N/A",dice:"N/A",effect:"Create either a sound or a static visual image no larger than a 5ft cube; an investigation check discerns it is false."},
  "prestidigitation":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"10ft",targets:"an object or point",duration:"up to 1 hour",save:"N/A",dice:"N/A",effect:"Minor magical tricks: light or snuff a small flame, clean or soil an object, chill/warm/flavor food, make a harmless sensory effect, or a trivial mark."},
  "produce flame":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["primal"],range:"30ft",targets:"1 creature",duration:"10 minutes (as light)",save:"N/A",dice:"1d8 fire",effect:"A flame in your hand sheds light; you may hurl it as a ranged spell attack for 1d8 fire (ending the spell)."},
  "ray of frost":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"60ft",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"1d8 cold",effect:"A ranged spell attack; 1d8 cold on a hit and the target's speed drops by 10ft until the start of your next turn."},
  "sacred flame":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["divine"],range:"60ft",targets:"1 creature",duration:"instantaneous",save:"DEX for none",dice:"1d8 radiant",effect:"Radiant light falls on a creature you can see; it makes a DEX save or takes 1d8 radiant. The target gains no benefit from cover."},
  "shillelagh":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["primal"],range:"touch",targets:"your club or quarterstaff",duration:"1 minute",save:"N/A",dice:"1d8",effect:"Your wooden club or quarterstaff becomes magical: use your spellcasting mod for its attacks and it deals 1d8 for the duration."},
  "spare the dying":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["divine"],range:"touch",targets:"1 creature at 0 HP",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Stabilize a creature at 0 HP (it no longer needs death saves). No effect on undead or constructs."},
  "thaumaturgy":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["divine"],range:"30ft",targets:"self / nearby",duration:"up to 1 minute",save:"N/A",dice:"N/A",effect:"A minor divine display: boom your voice, flicker flames, cause tremors, sound a phantom noise, or fling open unlocked doors/windows."},
  "thorn whip":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["primal"],range:"30ft",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"1d6 piercing",effect:"A vine lashes out (melee spell attack at range); 1d6 piercing and, if the target is Large or smaller, you pull it up to 10ft toward you."},
  "toll the dead":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["necromantic"],range:"60ft",targets:"1 creature",duration:"instantaneous",save:"WIS for none",dice:"1d8 necrotic (1d12 if wounded)",effect:"A mournful bell tolls; the target makes a WIS save or takes 1d8 necrotic — 1d12 if it is already below its hit point maximum."},
  "absorb elements":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"1 round",save:"N/A",dice:"+1d6 (absorbed type)",effect:"A reaction when you take acid, cold, fire, lightning, or thunder damage: gain resistance to that type until your next turn, and your next melee hit deals +1d6 of it."},
  "bleed":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["necromantic"],range:"30ft",targets:"1 creature",duration:"1d10 turns or until cancelled",save:"N/A",dice:"1d4 necrotic per turn",effect:"The target bleeds from every orifice, taking 1d4 necrotic at the start of each of its turns for 1d10 turns or until you cancel it."},
  "bless":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["divine"],range:"30ft",targets:"up to 3 creatures",duration:"concentration, up to 1 min",save:"N/A",dice:"+1d4",effect:"Up to three creatures you choose add 1d4 to their attack rolls and saving throws for the duration."},
  "cause fear":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["necromantic"],range:"60ft",targets:"1 creature",duration:"concentration, up to 1 min",save:"WIS or frightened",dice:"N/A",effect:"A creature (not undead or construct) makes a WIS save or is frightened of you, repeating the save at the end of each of its turns."},
  "charm person":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"30ft",targets:"1 humanoid",duration:"1 hour",save:"WIS negates",dice:"N/A",effect:"A humanoid makes a WIS save (advantage if you or your allies are fighting it) or is charmed, regarding you as a friendly acquaintance, until the spell ends or you harm it."},
  "chromatic orb":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"90ft",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"3d8 (chosen element)",effect:"A ranged spell attack hurling a 4-inch orb of acid, cold, fire, lightning, poison, or thunder (you choose) for 3d8."},
  "command":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["divine"],range:"60ft",targets:"1 creature",duration:"1 round",save:"WIS negates",dice:"N/A",effect:"Speak a one-word command (approach, drop, flee, grovel, halt, or similar); the target makes a WIS save or obeys on its next turn. It will not obey a directly harmful command, and the spell fails if it cannot understand you or is undead."},
  "comprehend languages":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"1 hour",save:"N/A",dice:"N/A",effect:"For the duration you understand the literal meaning of any spoken language you hear and, while touching the surface, any written language. It does NOT decode ciphers, secret codes, or non-linguistic symbols, and it does not let you speak or write the language."},
  "cure wounds":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["divine","primal"],range:"touch",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"1d8 + spell mod healing",effect:"Touch a creature to restore 1d8 + your spellcasting modifier HP. No effect on undead or constructs."},
  "detect magic":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane","divine","primal"],range:"self (30ft radius)",targets:"magical auras within 30ft",duration:"concentration, up to 10 min",save:"N/A",dice:"N/A",effect:"Sense the presence of magic within 30ft; as an action, see a faint aura around a visible magical creature or object and learn its tradition. Blocked by 1ft of stone, 1in of metal, or 3ft of wood. It DETECTS only — learning an item's specific properties is Identify."},
  "disguise self":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"1 hour",save:"N/A",dice:"N/A",effect:"Illusorily change your appearance — body and clothing/gear — until the spell ends. Physical inspection or an investigation check reveals the disguise."},
  "divine smite":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["divine"],range:"self (on a melee hit)",targets:"1 creature you hit",duration:"instantaneous",save:"N/A",dice:"2d8 radiant (+1d8 vs undead/fiends)",effect:"When you hit with a melee weapon attack, expend a slot to deal +2d8 radiant (more with a higher slot; +1d8 extra against undead or fiends)."},
  "ensnaring strike":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["primal"],range:"self (next weapon hit)",targets:"1 creature you hit",duration:"concentration, up to 1 min",save:"STR or restrained",dice:"1d6 piercing/turn",effect:"The next time you hit with a weapon this turn, thorny vines sprout; the target makes a STR save or is restrained, taking 1d6 piercing each turn until it breaks free."},
  "entangle":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["primal"],range:"90ft",targets:"20ft square",duration:"concentration, up to 1 min",save:"STR or restrained",dice:"N/A",effect:"Grasping weeds fill a 20ft square (difficult terrain); a creature there makes a STR save or is restrained until it breaks free with a STR check."},
  "faerie fire":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["primal"],range:"60ft",targets:"20ft cube",duration:"concentration, up to 1 minute",save:"DEX for none",dice:"N/A",effect:"Each creature in the cube that fails a DEX save is outlined in light: attacks against it have advantage and it cannot benefit from invisibility."},
  "false life":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["necromantic"],range:"self",targets:"self",duration:"1 hour",save:"N/A",dice:"1d4+4 temp HP",effect:"Gain 1d4+4 temporary hit points for the duration."},
  "feather fall":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"60ft",targets:"up to 5 falling creatures",duration:"1 minute",save:"N/A",dice:"N/A",effect:"A reaction when you or nearby creatures fall: up to five falling creatures descend 60ft per round and take no damage on landing."},
  "guiding bolt":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["divine"],range:"120ft",targets:"1 creature",duration:"1 round (the advantage)",save:"N/A",dice:"4d6 radiant",effect:"A ranged spell attack; 4d6 radiant on a hit, and the next attack roll against that target before the end of your next turn has advantage."},
  "hail of thorns":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["primal"],range:"self (next ranged hit)",targets:"5ft radius around the target",duration:"instantaneous",save:"DEX for half",dice:"1d10 piercing",effect:"Your next ranged weapon hit bursts into thorns: creatures within 5ft of the target take 1d10 piercing (DEX save half)."},
  "healing word":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["divine"],range:"60ft",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"1d4 + spell mod healing",effect:"A bonus action: one creature you can see regains 1d4 + your spellcasting modifier HP. No effect on undead or constructs."},
  "hunter's mark":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["primal"],range:"90ft",targets:"1 creature",duration:"concentration, up to 1 hour",save:"N/A",dice:"+1d6 weapon damage",effect:"Mark one creature you can see. Your weapon attacks against THAT target deal +1d6 damage, and you have advantage to track it. EXCLUSIVE: only one Hunter's Mark can exist at a time — casting it again moves the mark and ends the previous one. If the target drops, you may move the mark to a new creature as a bonus action."},
  "identify":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"touch",targets:"1 magic item or magic-affected creature",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Handle an object through the casting to learn whether it is magical, what its properties are and how to use them, whether it requires attunement, and how many charges remain. Cast on a creature, learn what spells (if any) currently affect it. A deliberately hidden curse may elude it."},
  "inflict wounds":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["necromantic"],range:"touch",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"3d10 necrotic",effect:"A melee spell attack; on a hit, the target takes 3d10 necrotic."},
  "magic missile":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"120ft",targets:"up to 3 creatures",duration:"instantaneous",save:"N/A",dice:"1d4+1 force per dart",effect:"Three darts of force strike targets you can see, one dart each or combined; each auto-hits for 1d4+1 force. No attack roll, no save."},
  "ray of sickness":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["necromantic"],range:"60ft",targets:"1 creature",duration:"instantaneous",save:"CON or poisoned",dice:"1d8 necrotic",effect:"A ray of sickly energy (ranged spell attack); 1d8 necrotic and, on a failed CON save, the target is poisoned until the end of your next turn."},
  "sanctuary":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["divine"],range:"30ft",targets:"1 creature",duration:"1 minute",save:"WIS (the attacker)",dice:"N/A",effect:"Ward one creature: an enemy that tries to attack or target it must first make a WIS save or be forced to pick a new target (or lose the attack). No protection against area effects, and the ward ends immediately if the warded creature attacks, casts a spell on an enemy, or harms another creature."},
  "shield":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"1 round",save:"N/A",dice:"N/A",effect:"A reaction (cast when hit or targeted by magic missile): +5 AC until the start of your next turn, INCLUDING against the triggering attack, and negates magic missile."},
  "shield of faith":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["divine"],range:"60ft",targets:"1 creature",duration:"concentration, up to 10 min",save:"N/A",dice:"N/A",effect:"A shimmering field grants a creature you can see +2 AC for the duration."},
  "silent image":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"60ft",targets:"a 15ft-cube image",duration:"concentration, up to 10 min",save:"N/A",dice:"N/A",effect:"Create a purely visual illusion no larger than a 15ft cube; you can move it. Physical interaction or an investigation check reveals it is false."},
  "thunderwave":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"self (15ft cube)",targets:"creatures in a 15ft cube",duration:"instantaneous",save:"CON for half",dice:"2d8 thunder",effect:"A wave of force: 2d8 thunder (CON save half); creatures that fail are also pushed 10ft away. Audible out to 300ft."},
  "aid":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["divine"],range:"30ft",targets:"up to 3 creatures",duration:"8 hours",save:"N/A",dice:"N/A",effect:"Bolster up to three creatures: their hit point maximum AND current HP each increase by 5 for 8 hours."},
  "arcane lock":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"touch",targets:"1 door, window, gate, chest, or other closable object",duration:"until dispelled",save:"N/A",dice:"N/A",effect:"Magically seal a closable object: it is locked and barred to everyone except you and creatures you designate at casting (you may also set a password that suppresses the seal for 1 minute when spoken within 5ft). Knock suppresses it for 10 minutes; breaking or picking it is 10 harder than normal."},
  "augury":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["divine"],range:"self",targets:"self (an omen)",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Cast tokens or bones to receive an omen about a SPECIFIC course of action you plan to take within the next 30 minutes: Weal (good results), Woe (bad), Weal and Woe (both), or nothing (no strong result either way). An omen, not an explanation — no details. Repeated castings before a rest risk a random false reading."},
  "barkskin":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["primal"],range:"touch",targets:"1 creature",duration:"concentration, up to 1 hour",save:"N/A",dice:"N/A",effect:"The target's AC cannot be lower than 16 for the duration, regardless of armor worn."},
  "blindness":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["necromantic"],range:"30ft",targets:"1 creature",duration:"1 minute",save:"CON or blinded",dice:"N/A",effect:"The target makes a CON save or is blinded for 1 minute, repeating the save at the end of each of its turns."},
  "darkness":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"60ft",targets:"15ft-radius sphere",duration:"concentration, up to 10 min",save:"N/A",dice:"N/A",effect:"Magical darkness fills a 15ft-radius sphere; it blocks darkvision and ordinary light cannot illuminate it."},
  "find steed":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["divine"],range:"30ft",targets:"a summoned steed",duration:"until dismissed or 0 HP",save:"N/A",dice:"N/A",effect:"Summon a loyal spirit steed (warhorse, pony, etc.) bonded to you telepathically; it serves as a mount and ally until it drops to 0 HP or you dismiss it."},
  "hold person":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane","divine"],range:"60ft",targets:"1 humanoid",duration:"concentration, up to 1 minute",save:"WIS or paralyzed",dice:"N/A",effect:"A humanoid you can see must make a WIS save or be paralyzed. It repeats the save at the end of each of its turns, ending the effect on a success. Humanoids only — not beasts, undead, or monstrosities."},
  "invisibility":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"touch",targets:"1 creature",duration:"concentration, up to 1 hour",save:"N/A",dice:"N/A",effect:"A creature you touch becomes invisible until it attacks, casts a spell, or the spell ends. Anything it is wearing or carrying is invisible too."},
  "knock":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"60ft",targets:"1 lock, door, chest, or manacle",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"A sharp clang unlocks or unbars one locked/stuck object within range. The knock is audible out to 300ft."},
  "lesser restoration":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["divine"],range:"touch",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"End one disease OR one condition on a creature: blinded, deafened, paralyzed, or poisoned."},
  "magic weapon":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["divine"],range:"touch",targets:"1 nonmagical weapon",duration:"concentration, up to 1 hour",save:"N/A",dice:"N/A",effect:"A nonmagical weapon becomes a magic weapon with +1 to attack and damage rolls for the duration."},
  "mirror image":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"1 minute",save:"N/A",dice:"N/A",effect:"Three illusory duplicates flit around you; when something targets you, an attack may strike a duplicate instead (destroying it) rather than you."},
  "misty step":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"A bonus action: teleport up to 30ft to an unoccupied space you can see. Line of sight required — you cannot step through a wall you can't see past."},
  "moonbeam":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["primal"],range:"120ft",targets:"5ft-radius cylinder",duration:"concentration, up to 1 min",save:"CON for half",dice:"2d10 radiant",effect:"A 5ft beam of moonlight; a creature that enters it or starts its turn there takes 2d10 radiant (CON save half). You may move the beam 60ft each turn."},
  "pass without trace":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["primal"],range:"self",targets:"self and allies within 30ft",duration:"concentration, up to 1 hour",save:"N/A",dice:"N/A",effect:"You and allies within 30ft gain +10 to Stealth and cannot be tracked by nonmagical means, leaving no tracks or scent."},
  "phantasmal force":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"60ft",targets:"1 creature",duration:"concentration, up to 1 min",save:"INT negates (and INT check to disbelieve)",dice:"1d6 psychic (if harmful)",effect:"Craft an illusion in ONE target's mind that it believes is real — it rationalizes any illogic away. Only the target perceives it. If the phantasm would harm it (fire, a collapsing beam), it takes 1d6 psychic each round it is affected. An action + INT check lets it disbelieve."},
  "ray of enfeeblement":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["necromantic"],range:"60ft",targets:"1 creature",duration:"concentration, up to 1 min",save:"CON to end",dice:"N/A",effect:"A ray of enervation (ranged spell attack); the target deals only half damage with STR-based weapon attacks until the spell ends (CON save each turn to end it early)."},
  "rot":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["necromantic"],range:"30ft",targets:"1 creature",duration:"1d10 turns or until cancelled",save:"N/A",dice:"1d6 necrotic per turn",effect:"The greater Bleed: the target festers with necrotic sores, taking 1d6 necrotic at the start of each of its turns for 1d10 turns or until cancelled."},
  "scorching ray":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"120ft",targets:"up to 3 creatures",duration:"instantaneous",save:"N/A",dice:"2d6 fire per ray",effect:"Three rays of fire; make a separate ranged spell attack for each, 2d6 fire per hit. Split among one or more targets."},
  "shackles of bone":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["necromantic"],range:"60ft",targets:"1 creature",duration:"until a STR check breaks free",save:"STR to break free",dice:"N/A",effect:"Skeletal arms erupt from earth or wall to pin the target prone or against a surface; it is restrained until it snaps the bones with a STR check."},
  "shadow blade":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"concentration, up to 1 min",save:"N/A",dice:"2d8 psychic",effect:"Weave shadows into a sword of solidified gloom (2d8 psychic, finesse, thrown 20/60); you have advantage on attacks with it in dim light or darkness."},
  "shadow step":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["necromantic","arcane"],range:"30ft",targets:"self",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"From an area of dim light or darkness, teleport up to 30ft to another area of dim light or darkness you can see."},
  "silence":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["primal"],range:"120ft",targets:"20ft-radius sphere",duration:"concentration, up to 10 min",save:"N/A",dice:"N/A",effect:"No sound can be created within or pass into a 20ft sphere. Creatures inside are deafened and cannot cast spells with verbal components; thunder damage is negated there."},
  "spike growth":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["primal"],range:"150ft",targets:"20ft radius",duration:"concentration, up to 10 min",save:"N/A",dice:"2d4 piercing per 5ft",effect:"The ground in a 20ft radius sprouts spikes (difficult terrain); a creature takes 2d4 piercing for every 5ft it travels through the area."},
  "spiritual weapon":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["divine"],range:"60ft",targets:"a spectral weapon",duration:"1 minute",save:"N/A",dice:"1d8 + spell mod force",effect:"Create a floating spectral weapon; a bonus action moves it 20ft and makes a melee spell attack for 1d8 + your spellcasting modifier force."},
  "zone of truth":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["divine"],range:"60ft",targets:"15ft-radius sphere",duration:"10 minutes",save:"CHA to resist",dice:"N/A",effect:"Sanctify a 15ft-radius zone: each creature makes a CHA save on entering or starting its turn there; on a failure it cannot speak a deliberate lie while inside. You know whether each creature passed or failed. The compelled can still be evasive, answer selectively, or stay silent."},
  "aura of vitality":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["divine"],range:"self (30ft aura)",targets:"you or an ally in 30ft",duration:"concentration, up to 1 min",save:"N/A",dice:"2d6 healing",effect:"For the duration, use a bonus action to heal one creature within 30ft for 2d6."},
  "bestow curse":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["necromantic"],range:"touch",targets:"1 creature",duration:"concentration, up to 1 min",save:"WIS negates",dice:"N/A",effect:"WIS save or cursed — choose: disadvantage on one ability's checks and saves, OR vulnerability to one damage type, OR the target wastes its action on a roll of 1-4."},
  "call lightning":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["primal"],range:"120ft",targets:"5ft-radius strike point",duration:"concentration, up to 10 min",save:"DEX for half",dice:"3d10 lightning",effect:"Summon a storm cloud; each turn as an action, call down a bolt — creatures within 5ft of the chosen point take 3d10 lightning (DEX save half)."},
  "conjure animals":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["primal"],range:"60ft",targets:"summoned beasts",duration:"concentration, up to 1 hour",save:"N/A",dice:"N/A",effect:"Summon fey spirits in beast form (their total power scaling with the slot) that obey your commands and fight for you until the spell ends."},
  "conjure barrage":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["primal"],range:"self (60ft cone)",targets:"creatures in a 60ft cone",duration:"instantaneous",save:"DEX for half",dice:"3d8 (weapon type)",effect:"Hurl a weapon or ammunition to conjure a barrage; each creature in a 60ft cone takes 3d8 of the weapon's damage type (DEX save half)."},
  "counterspell":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["arcane"],range:"60ft",targets:"1 creature casting a spell",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"A reaction when you see a creature within 60ft casting: automatically negate a spell of 3rd tier or lower. For a higher-tier spell, make a spellcasting ability check (DC 10 + that spell's tier) to interrupt it."},
  "death walk":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["necromantic"],range:"self",targets:"self",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Step between the worlds of the living and dead: move up to INT x 5 ft unimpeded through creatures, objects, and difficult terrain, ignoring opportunity attacks."},
  "dispel magic":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["arcane","divine"],range:"120ft",targets:"1 creature, object, or magical effect",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"End one ongoing spell of 3rd tier or lower on the target automatically. For a higher-tier effect, make a spellcasting ability check (DC 10 + that spell's tier). Only affects ongoing magical effects, not instantaneous ones already resolved."},
  "fireball":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["arcane"],range:"150ft",targets:"20ft-radius sphere",duration:"instantaneous",save:"DEX for half",dice:"8d6 fire",effect:"A bright streak blossoms into flame at a point you choose; each creature in a 20ft-radius sphere makes a DEX save, taking 8d6 fire (half on a success). Ignites unattended flammable objects."},
  "fly":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["arcane"],range:"touch",targets:"1 creature",duration:"concentration, up to 10 min",save:"N/A",dice:"N/A",effect:"The target gains a flying speed of 60ft for the duration."},
  "lethe's kiss":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["arcane"],range:"touch or 30ft",targets:"1 creature",duration:"instantaneous",save:"WIS negates",dice:"N/A",effect:"WIS save or the target loses up to 15 minutes of memory per point of your INT modifier — recent events simply vanish. The narrative-only sibling of Oubliate."},
  "lightning arrow":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["primal"],range:"self (next ranged attack)",targets:"target + creatures within 10ft",duration:"instantaneous",save:"DEX for half (splash)",dice:"4d8 lightning",effect:"Your next ranged attack becomes lightning: 4d8 lightning on a hit (2d8 on a miss), and creatures within 10ft of the target take 2d8 (DEX save half)."},
  "miasma":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["necromantic"],range:"60ft",targets:"10x10ft cloud (+1ft per INT mod)",duration:"concentration, up to 1 min",save:"WIS or disadvantage",dice:"N/A",effect:"A cloud of despair; creatures inside are wracked with grief and hopelessness — WIS save or act at disadvantage while within it."},
  "plant growth":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["primal"],range:"150ft",targets:"100ft radius",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Overgrow a 100ft radius into difficult terrain (movement quartered) — or, over 8 hours, enrich the land for a year of bountiful harvest."},
  "revivify":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["divine"],range:"touch",targets:"1 creature dead <=1 min",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Return a creature that died within the last minute to life with 1 HP. Cannot restore missing body parts, revive undead/constructs, or one dead of old age."},
  "speak with dead":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["necromantic"],range:"10ft",targets:"1 corpse",duration:"10 minutes",save:"N/A",dice:"N/A",effect:"Ask a corpse (with a mouth, dead no more than 10 days, not undead) up to five questions; it answers briefly and cryptically from what it knew in life."},
  "spirit guardians":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["divine"],range:"self (15ft radius)",targets:"creatures in a 15ft aura",duration:"concentration, up to 10 min",save:"WIS for half",dice:"3d8 radiant/necrotic",effect:"Spectral guardians swirl in a 15ft aura; hostile creatures there move at half speed and take 3d8 (WIS save half) when they enter or start their turn there."},
  "vampiric touch":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["necromantic"],range:"touch",targets:"1 creature",duration:"concentration, up to 1 min",save:"N/A",dice:"3d6 necrotic (heal half)",effect:"A melee spell attack; 3d6 necrotic and you regain HP equal to half the damage dealt. You can attack again each turn while you concentrate."},
  "wave of scarabs":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["necromantic"],range:"self (30ft cone)",targets:"creatures in a 30ft cone",duration:"instantaneous",save:"DEX for half",dice:"3d6 necrotic",effect:"A swarm of spectral scarabs erupts in a 30ft cone; each creature takes 3d6 necrotic (DEX save half)."},
  "divination":{kind:"spell",tier:4,cost:"slot",isMagical:true,category:["divine"],range:"self",targets:"self (one question)",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Through offering and ritual, ask your deity ONE question about a specific goal, event, or activity due to occur within 7 days; you receive a truthful reply — a short phrase, cryptic rhyme, or omen. The gods answer what WILL be as things stand, not hypotheticals. Repeated castings before a rest risk a random false reading."},
  "oubliate":{kind:"spell",tier:4,cost:"slot",isMagical:true,category:["arcane"],range:"touch or 30ft",targets:"1 creature",duration:"instantaneous",save:"WIS negates",dice:"N/A",effect:"WIS save or surgically erase ONE specific person or event from the target's memory entirely (the engine scrubs it via [NPC_FORGET:]); they cannot recall it even when reminded."},
  "possess thrall":{kind:"spell",tier:4,cost:"slot",isMagical:true,category:["necromantic"],range:"one of your thralls",targets:"self (mind projected)",duration:"1 turn per INT point or until you withdraw",save:"N/A",dice:"N/A",effect:"Project your mind into one of your undead thralls, seeing and speaking through it; your own body lies in suspended animation until you withdraw."},
  "rigor mortis":{kind:"spell",tier:4,cost:"slot",isMagical:true,category:["necromantic"],range:"60ft",targets:"1 creature",duration:"1d4 + caster level turns",save:"CON or incapacitated",dice:"N/A",effect:"CON save or the target seizes rigid and incapacitated for 1d4 + your level turns."},
  "sleep of the dead":{kind:"spell",tier:4,cost:"slot",isMagical:true,category:["necromantic"],range:"touch",targets:"self or 1 creature",duration:"caster level + INT + INT mod turns",save:"N/A",dice:"N/A",effect:"Feign death on yourself or a creature you touch — indistinguishable from a true corpse (no breath, no pulse). A self-cast always lasts the full duration."},
  // ── Abilities ──
  "arcane bolt":{kind:"ability",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"120ft",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"1d8 force",effect:"A ranged spell attack (INT vs AC); 1d8 force on a hit. The sorcerer's reliable at-will strike."},
  "arcane shield":{kind:"ability",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"until hit",save:"N/A",dice:"N/A",effect:"A shimmer of force absorbs the next 5 damage you take, then dissipates. Raised as a reaction."},
  "binding ward":{kind:"ability",tier:1,cost:"at-will (10 min ritual)",isMagical:true,category:["divine"],range:"touch",targets:"1 object or surface",duration:"24 hours",save:"WIS (DC 16)",dice:"N/A",effect:"Spend 10 minutes inscribing a temporary ward on a surface or object. For 24 hours, a creature attempting to alter, forge, or destroy it must succeed on a WIS save or be compelled to stop and reconsider. It delays and deters — it does not prevent a determined actor permanently."},
  "blink":{kind:"ability",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"30ft",targets:"self",duration:"instantaneous",save:"DC 15 DEX or arrive off-target",dice:"N/A",effect:"Teleport up to 30ft to a space you can see. On a failed DC 15 DEX check you arrive at a nearby unintended spot."},
  "channel divinity: weight of account":{kind:"ability",tier:2,cost:"per-rest",isMagical:true,category:["divine"],range:"30ft (must be heard)",targets:"1 creature",duration:"1 round",save:"WIS (DC 16) or stunned",dice:"N/A",effect:"As an action, speak a target's outstanding obligations aloud — real or symbolic. It makes a WIS save or is stunned for one round as the full weight of its debts, kept promises, and broken ones settles on it simultaneously."},
  "cold reading":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["martial"],range:"conversation",targets:"1 person observed",duration:"N/A",save:"N/A",dice:"N/A",effect:"Read unguarded moments — microexpressions, involuntary word choices, measured silences — with uncomfortable precision. Advantage on Insight checks to notice what someone is deliberately NOT saying, and to gauge the gap between what they say and what they mean."},
  "cunning action":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"self",targets:"self",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Dash, Disengage, or Hide as a bonus action on each of your turns."},
  "death sight":{kind:"ability",tier:0,cost:"passive",isMagical:true,category:["necromantic"],range:"60ft",targets:"area",duration:"N/A",save:"N/A",dice:"N/A",effect:"Sense undead, corpses, and death-taint within 60ft without seeing them, and gain advantage on Arcana/Lore checks about undead, curses, or death magic."},
  "divine sense":{kind:"ability",tier:0,cost:"per-rest",isMagical:true,category:["divine"],range:"60ft",targets:"area",duration:"until your next turn",save:"N/A",dice:"N/A",effect:"Sense the location of any undead, fiend, or celestial within 60ft, and any consecrated or desecrated place, until the end of your next turn."},
  "door that opens":{kind:"ability",tier:1,cost:"per-rest",isMagical:false,category:["divine"],range:"presence",targets:"1 creature",duration:"until its next Insight or Persuasion check",save:"N/A",dice:"N/A",effect:"Once per long rest, offer a creature a moment of genuine, non-magical safety. It gains advantage on its next Insight or Persuasion check made in your presence, and you learn one true thing it believes about itself."},
  "drain life":{kind:"ability",tier:0,cost:"at-will",isMagical:true,category:["necromantic"],range:"30ft",targets:"1 creature",duration:"instantaneous",save:"N/A",dice:"1d6 necrotic",effect:"A melee or 30ft necrotic touch; deal 1d6 necrotic and regain HP equal to half the damage dealt."},
  "druidic":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["primal"],range:"N/A",targets:"N/A",duration:"N/A",save:"N/A",dice:"N/A",effect:"You know Druidic, the secret language of druids, and can leave hidden messages (via marks and signs in nature) that only those who know it can read."},
  "evasion":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["martial"],range:"N/A",targets:"N/A",duration:"N/A",save:"N/A",dice:"N/A",effect:"On a FAILED DEX save against an area effect, take half damage instead of full. (Class-feature Evasion later upgrades this to zero on a success.)"},
  "expertise":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["martial"],range:"N/A",targets:"N/A",duration:"N/A",save:"N/A",dice:"N/A",effect:"Double your proficiency bonus on checks with a chosen skill you are proficient in (fixed when the expertise was gained — e.g. Stealth, Deception, Thieves' Tools)."},
  "expertise — deception":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["martial"],range:"N/A",targets:"N/A",duration:"N/A",save:"N/A",dice:"N/A",effect:"Double your proficiency bonus on Deception checks."},
  "expertise — stealth":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["martial"],range:"N/A",targets:"N/A",duration:"N/A",save:"N/A",dice:"N/A",effect:"Double your proficiency bonus on Stealth checks."},
  "field intelligence":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["martial"],range:"N/A",targets:"N/A",duration:"N/A",save:"N/A",dice:"N/A",effect:"Detailed operational intelligence on organizations you have worked inside: chains of command, acquisition strategies, prior operations, funding sources. Your recall of a former employer's operations is treated as reliable; specifics live on your sheet."},
  "fire lance":{kind:"ability",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"60ft",targets:"1 creature or object",duration:"instantaneous",save:"N/A",dice:"1d10 fire",effect:"A lance of flame; 1d10 fire on a hit and ignites unattended flammable targets."},
  "intimidating presence":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"30ft",targets:"1 creature",duration:"N/A",save:"CHA contest",dice:"N/A",effect:"A CHA check to terrify one creature. On a success it is shaken (-2 to all rolls) until it can no longer see you or the scene ends."},
  "lay on hands":{kind:"ability",tier:0,cost:"pool, refreshes on a long rest",isMagical:true,category:["divine"],range:"touch",targets:"1 creature",duration:"N/A",save:"N/A",dice:"N/A",effect:"Draw from a healing pool of 5 × your level HP: touch to restore HP, or spend 5 points to cure one disease or neutralize one poison. Cannot harm undead with it here."},
  "layout memory":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["martial"],range:"N/A",targets:"N/A",duration:"N/A",save:"N/A",dice:"N/A",effect:"After one pass through a building or location, retain an accurate mental map of it: entry points, weak latches, guard rhythms, storage placement."},
  "ledger memory":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["divine"],range:"N/A",targets:"N/A",duration:"N/A",save:"N/A",dice:"N/A",effect:"Recall with perfect clarity any contract, debt, name, or obligation you have personally witnessed or been bound to. An INT check (DC 12) identifies whether a symbol, cipher, or document belongs to a known contractual tradition."},
  "lockpick":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"N/A",targets:"N/A",duration:"N/A",save:"N/A",dice:"N/A",effect:"Open locks and disarm mechanical traps with a DEX check against the device's DC. Requires thieves' tools."},
  "operative's read":{kind:"ability",tier:1,cost:"per-rest",isMagical:false,category:["martial"],range:"conversation",targets:"1 person",duration:"instantaneous",save:"N/A",dice:"WIS check DC 12",effect:"Once per short rest, assess a person's likely loyalty, fear threshold, or hidden motive with a WIS check (DC 12). On a success, the GM reveals one concealed motivation."},
  "power strike":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"N/A",targets:"1 attack",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"On a declared attack, add +1d6 damage on a hit. Declared before the roll."},
  "rage":{kind:"ability",tier:0,cost:"per-rest",isMagical:false,category:["martial"],range:"N/A",targets:"N/A",duration:"3 rounds",save:"N/A",dice:"N/A",effect:"Enter a battle fury: +2 STR, +2 melee damage, and you push through pain (resist physical damage, ignore first wounds). Lasts 3 rounds. Ends early if you take no hostile action."},
  "raise thrall":{kind:"ability",tier:0,cost:"at-will",isMagical:true,category:["necromantic"],range:"10ft",targets:"1 fresh corpse",duration:"N/A",save:"N/A",dice:"N/A",effect:"Animate a fresh corpse within 10ft as a zombie thrall that follows basic commands. Requires a body present. ONE thrall at a time (until the archetype expands it); the thrall collapses if you fall unconscious."},
  "reckless attack":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"N/A",targets:"your attacks this turn",duration:"until your next turn",save:"N/A",dice:"N/A",effect:"Attack with advantage this turn; in exchange, attacks against you have advantage until your next turn."},
  "ritual working":{kind:"ability",tier:1,cost:"at-will (ritual time)",isMagical:true,category:["arcane"],range:"touch",targets:"a ritual site or attuned object",duration:"by ritual",save:"N/A",dice:"N/A",effect:"Conduct binding and consecration rituals in a commanding pre-common ritual tongue: consecrate altar stones, levitate and activate attuned ritual objects, produce controlled light phenomena. Slow, deliberate workings — not combat magic."},
  "shield wall":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"N/A",targets:"N/A",duration:"until your next turn",save:"N/A",dice:"N/A",effect:"Reduce all incoming damage by 3 until the start of your next turn. Requires a shield or braced stance."},
  "sigil reading":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["arcane"],range:"touch/sight",targets:"inscribed script",duration:"N/A",save:"N/A",dice:"N/A",effect:"Decipher old and otherworldly script with scholarly fluency — ritual markings, ward anchors, contract notation. Passive identification on contact with inscribed stone or bound material; reading tells you what it SAYS, not whether it is safe."},
  "sneak attack":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"N/A",targets:"1 attack",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Double the attack's damage dice when you have advantage, are unseen, or the target is flanked by an ally. Once per turn."},
  "speak with animals":{kind:"ability",tier:0,cost:"at-will",isMagical:true,category:["primal"],range:"nearby beasts",targets:"N/A",duration:"conversational",save:"N/A",dice:"N/A",effect:"Comprehend and verbally communicate with beasts. They can share what they have sensed recently, but are limited by animal intelligence and perspective."},
  "threat taxonomy":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["martial"],range:"sight",targets:"1 person on first contact",duration:"continuous",save:"N/A",dice:"N/A",effect:"On first contact with an unknown individual, compile a rapid threat-and-asset assessment — physical tells, visible capabilities, social patterns — and update it continuously thereafter. Observation and inference, not mind reading."},
  "trackless step":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["martial"],range:"N/A",targets:"N/A",duration:"N/A",save:"N/A",dice:"N/A",effect:"Leave no trail in natural terrain; cannot be tracked by nonmagical means while moving through wilderness at a careful pace."},
  "turn undead":{kind:"ability",tier:0,cost:"per-rest",isMagical:true,category:["divine","necromantic"],range:"30ft",targets:"undead in range",duration:"1 minute",save:"WIS (DC 8 + WIS + proficiency)",dice:"N/A",effect:"Channel Divinity: each undead within 30ft that fails a WIS save must spend its turns fleeing you and cannot willingly move closer, for 1 minute or until it takes damage."},
  "uncanny dodge":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"self",targets:"self",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"When an attacker you can see hits you with an attack, use your reaction to halve that attack's damage against you. One reaction per round."},
  "unmoored sense":{kind:"ability",tier:1,cost:"at-will",isMagical:true,category:["divine"],range:"60ft",targets:"the nearest disrupted obligation",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"As a bonus action, attune briefly to the nearest disrupted or unanchored obligation within 60ft. You do not learn its contents — only its weight (trivial, significant, or catastrophic) and roughly how long it has been loose."},
  "volley":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"N/A",targets:"up to 2 creatures in range",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"With one action, make a ranged attack against up to 2 targets within your weapon's range."},
  "ward architecture":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["arcane"],range:"sight/touch",targets:"1 ward examined",duration:"N/A",save:"N/A",dice:"N/A",effect:"Trained in the structural logic of protective wards: identify trigger conditions, recognition mechanisms, and whether a ward targets by intent versus by bloodline or status. Cannot always disable what it identifies — but always knows enough to warn."},
  "weapon mastery":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["martial"],range:"N/A",targets:"N/A",duration:"N/A",save:"N/A",dice:"N/A",effect:"No penalty for using improvised or unfamiliar weapons — proficient with anything wieldable."},
  "wild shape":{kind:"ability",tier:0,cost:"per-rest",isMagical:true,category:["primal"],range:"self",targets:"self",duration:"hours by level",save:"N/A",dice:"N/A",effect:"Transform into a beast you have seen, up to a CR limit that scales with level. You take on its stats; you revert at 0 HP or when you choose. Gear melds. Cannot cast spells while shaped until high level."},
  // ── Racial capabilities (ANCS references these by base name via racial_caps; single source of truth) ──
  // category "racial" = an innate heritage trait, drawn by no caster tradition (so it never appears in an
  // enemy caster's tradition menu). Clearly-arcane innate castings (Dancing Lights, Hellish Rebuke) keep
  // their real tradition. Recharge (passive / 1-day / at-will) is a per-GRANT property carried on the
  // character entry's display name — the bible pins the MECHANICS (range/targets/effect), not the economy.
  "darkvision":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"60ft",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"See in darkness within 60ft as though it were dim light, in shades of grey. Does not pierce magical darkness."},
  "superior darkvision":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"120ft",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"See in darkness within 120ft as though it were dim light, in shades of grey — the extended sight of the deep-dwelling races."},
  "see in magical darkness":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"60ft",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Your darkvision pierces even magically created darkness."},
  "fey ancestry":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Advantage on saving throws against being charmed, and magic cannot put you to sleep."},
  "half-fey charm":{kind:"ability",tier:1,cost:"per-day",isMagical:true,category:["racial"],range:"30ft",targets:"1 humanoid",duration:"1 hour",save:"WIS negates",dice:"N/A",effect:"Innate fey heritage: cast Charm Person once per day without a spell slot (full canon under Charm Person — WIS save or the target regards you as a friendly acquaintance until the effect ends or you harm it)."},
  "keen senses":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Advantage on Perception checks that rely on sight, hearing, or smell."},
  "trance":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"4-hour rest",save:"N/A",dice:"N/A",effect:"Meditate 4 hours (semi-aware) to gain the full benefit of an 8-hour long rest; you do not sleep."},
  "gnomish cunning":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Advantage on Intelligence, Wisdom, and Charisma saving throws against magic."},
  "poison resistance":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Advantage on saving throws against poison, and resistance (half damage) to poison."},
  "stonecunning":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"While underground or touching stone you always know your approximate depth and direction; advantage on checks about the origin or construction of stonework."},
  "dwarven toughness":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"+1 maximum HP per character level."},
  "necrotic resistance":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Resistance (half damage) to necrotic damage."},
  "fire resistance":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Resistance (half damage) to fire damage."},
  "elemental resistance":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Resistance (half damage) to one elemental damage type — fire, cold, lightning, or acid — fixed by your heritage."},
  "small size":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"You are Small: advantage on Stealth to hide behind larger creatures and you can move through a larger creature's space, but you have disadvantage attacking with Heavy weapons."},
  "sunlight sensitivity":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"in direct sunlight",save:"N/A",dice:"N/A",effect:"Disadvantage on attack rolls and on sight-based Perception checks while you, or the thing you are looking at, is in direct sunlight."},
  "mask of the wild":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"You can attempt to hide even when only lightly obscured by natural phenomena — foliage, heavy rain, falling snow, or mist."},
  "unsettling presence":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"Your uncanny aspect unnerves others: advantage on Intimidation checks."},
  "undead sense":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"30ft",targets:"area",duration:"always on",save:"N/A",dice:"N/A",effect:"You sense the presence of undead and fiends within 30ft before you see them — roughly where and that they are there, not precisely what."},
  "see invisible":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"sight",targets:"area",duration:"always on",save:"N/A",dice:"N/A",effect:"You perceive invisible creatures and objects as faint, wavering outlines."},
  "abyssal fury":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"while bloodied",save:"N/A",dice:"+1d4",effect:"While below half your maximum HP, your melee attacks deal an extra 1d4 damage."},
  "relentless endurance":{kind:"ability",tier:0,cost:"per-day",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Once per day, when you would be reduced to 0 HP but not killed outright, you drop to 1 HP instead."},
  "camouflage":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["racial"],range:"self",targets:"self",duration:"while you hold still",save:"N/A",dice:"N/A",effect:"While you remain motionless you blend into your native surroundings (stump/foliage, stone/rockwork, or shadow by heritage) and count as hidden. Any movement ends it."},
  "draconic breath":{kind:"ability",tier:0,cost:"per-rest",isMagical:false,category:["racial"],range:"15ft cone or 30ft line",targets:"creatures in the area",duration:"instantaneous",save:"DEX for half",dice:"2d6 (element by heritage)",effect:"Exhale destructive energy of your draconic bloodline — a 15ft cone or a 30ft line by heritage; each creature in the area takes 2d6 of your element (fire, cold, lightning, or acid), halved on a successful DEX save. Recharges on a rest."},
  "commune with dead":{kind:"ability",tier:1,cost:"per-day",isMagical:true,category:["racial"],range:"10ft",targets:"one corpse dead less than a day",duration:"up to 1 minute",save:"N/A",dice:"N/A",effect:"Once per day, briefly commune with a recently dead creature; for up to a minute it answers a few questions tersely and truthfully, limited to what it knew in life."},
  "dancing lights":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"120ft",targets:"up to four lights or one glowing form",duration:"1 minute (concentration)",save:"N/A",dice:"N/A",effect:"Create up to four torch-sized lights (or combine them into one vaguely humanoid glow) within range and move them as a bonus action; each sheds dim light in a 10ft radius."},
  "hellish rebuke":{kind:"ability",tier:1,cost:"per-day",isMagical:true,category:["arcane"],range:"60ft",targets:"a creature that damaged you",duration:"instantaneous",save:"DEX for half",dice:"2d10 fire",effect:"As a reaction to taking damage from a creature you can see, wreathe it in hellish flame; it takes 2d10 fire, halved on a successful DEX save."},

  // ── ARCHETYPE FEATURES ──────────────────────────────────────────────────────────────────────
  // Class-bible progression features (#72). Named entries here so the GM gets their canon injected
  // every turn like any other capability — which is the whole reason archetype features are written
  // to be NARRATABLE rather than numeric (DOC/DOC_class_bible.html Part II-a: a feature is a
  // sentence the GM permanently knows about the character).
  //
  // ROGUE / ARCANE TRICKSTER — spine verb: THE SWAP. Object -> idea -> face -> blame -> story ->
  // fate. Mythic register is Loki/Anansi/Wukong (user call 2026-07-28: "trickster" means mischief
  // and chaos, not a shadow operative). Every entry is GENERATIVE or present-tense on purpose:
  // subtractive "unwrite the past" features have no engine vocabulary (the transcript is sacred and
  // the retcon de-index marks only two entries), so they would drift silently via RAG.
  "the old switcheroo":{kind:"ability",tier:1,cost:"at-will",isMagical:true,category:["arcane"],range:"30ft",targets:"two objects you can see",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"Your invisible Mage Hand exchanges two objects of a size it can carry, and both holders go on believing they hold what they held. A creature actively watching the objects may contest with Perception against your Sleight of Hand."},
  "it was their idea":{kind:"ability",tier:2,cost:"per-rest",isMagical:true,category:["arcane"],range:"30ft",targets:"1 creature",duration:"until the notion is disproved",save:"WIS negates",dice:"N/A",effect:"You plant a suggestion no more unreasonable than something the target might plausibly have thought; on a failed WIS save they remember it as their OWN idea and will argue for it to others as such. Ordering them into obvious harm breaks it immediately."},
  "seventy-two shapes":{kind:"ability",tier:3,cost:"at-will",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"until you drop it",save:"N/A",dice:"N/A",effect:"Take the form of any person or creature of roughly your size that you have seen — voice, face, bearing. It holds until you choose to end it, and does not drop when you are struck. It grants none of the form's abilities or statistics; someone who knows the original well may contest with Insight on close interaction."},
  "never caught":{kind:"ability",tier:3,cost:"1/scene",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"The first time in a scene you would be seized, cornered, bound, or otherwise physically taken, you simply are not — you were already elsewhere, and those present half-remember deciding to let you go. Does not prevent damage, only capture."},
  "the story runs ahead":{kind:"ability",tier:4,cost:"per-day",isMagical:true,category:["arcane"],range:"anywhere word travels",targets:"a rumour",duration:"permanent",save:"N/A",dice:"N/A",effect:"You set a rumour loose about yourself or another; by the time it reaches its destination it has become true in the small ways a story needs to be — the debt was paid, the guard was bribed, the heir was seen in the city. It creates circumstance, never undoes what has already happened, and never directly harms a creature."},
  "turnabout":{kind:"ability",tier:4,cost:"1/campaign",isMagical:true,category:["arcane"],range:"60ft",targets:"you and 1 creature",duration:"permanent",save:"WIS negates",dice:"N/A",effect:"Once, at a moment of your choosing: you and another creature exchange places entirely — position, bonds and restraints, conditions, and the blame the situation carries. The tyrant stands in the cell wearing your charges; you stand where they stood. From that moment everyone present proceeds as though it had always been so, and acts on it."},

  // Straight-Rogue class features, L11-L17 (user fill 2026-07-28). Mundane tradecraft — category
  // ["martial"] so they never surface in a rolled enemy CASTER's menu. "summon item" is the one
  // judgement call: it reads magical (isMagical true, so Detect Magic sees it) while staying a
  // rogue's trick rather than an arcane tradition.
  "silent stalker":{kind:"ability",tier:0,cost:"passive",isMagical:false,category:["martial"],range:"self",targets:"self",duration:"always on",save:"N/A",dice:"N/A",effect:"You move without sound. Floorboards, gravel, dry leaves and armour make no noise for you; a creature cannot detect you by hearing alone, and Stealth checks ignore penalties for noisy footing."},
  // SHARED KEY — Rogue L13 and Ranger L9 both carry this name, and capBaseName lowercases, so one
  // entry serves both (the Extra Attack precedent: four classes, one canon). The effect therefore
  // covers BOTH readings — the rogue's crowd and the ranger's cover — rather than the rogue's
  // alone, which is what it said when first authored and would have silently rewritten the
  // ranger's +10-Stealth camouflage into a city ability.
  "hide in plain sight":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"self",targets:"self",duration:"until you draw attention",save:"N/A",dice:"N/A",effect:"You disappear into whatever surrounds you. In a crowd or a household you become one of them — posture, pace and business all wrong for the person being hunted. In the wild you take on the cover itself: motionless against rock, bracken or snow, effectively invisible to a passing eye. Someone actively searching may contest with Perception; acting overtly ends it."},
  "escape artist":{kind:"ability",tier:0,cost:"at-will",isMagical:false,category:["martial"],range:"self",targets:"self",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"No non-magical binding holds you: rope, manacles, chains, a locked cell, a press of hands. Given a few unobserved moments you are simply out. Magical restraints still hold."},
  "summon item":{kind:"ability",tier:0,cost:"per-rest",isMagical:true,category:["martial"],range:"100ft",targets:"1 small object you have handled",duration:"instantaneous",save:"N/A",dice:"N/A",effect:"An object small enough to close your hand around, which you have handled before and which is not held or worn by a creature, vanishes from where it lies and arrives in your palm. Through walls, locks and pockets you cannot see."},

  // ── ARCANE TRICKSTER SPELL BENCH (user fill 2026-07-28) ─────────────────────────────────────
  // Third-caster schedule T1@3 · T2@10 · T3@14 · T4@18. Tradition ["arcane"] throughout, so an
  // enemy arcane caster can legitimately draw from this bench (the category gate).
  "flash":{kind:"spell",tier:0,cost:"at-will",isMagical:true,category:["arcane"],range:"30ft",targets:"1 creature",duration:"instantaneous",save:"CON negates",dice:"N/A",effect:"A soundless burst of white light at a creature's eye level; on a failed CON save it is blinded until the end of its next turn. Useless against a creature that cannot see, and it plainly announces that magic was cast."},
  "fog bank":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"60ft",targets:"20ft sphere",duration:"10 minutes (concentration)",save:"N/A",dice:"N/A",effect:"A bank of dense fog rolls out and fills the area, heavily obscuring everything inside it. Creatures within cannot see out, and those outside cannot see in. A strong wind disperses it in a round."},
  "leap":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"touch",targets:"1 creature",duration:"1 minute",save:"N/A",dice:"N/A",effect:"The target's jumping distance triples — rooftop to rooftop, a chasm, a courtyard wall. It does not slow a fall at the far end."},
  "grease":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"60ft",targets:"10ft square",duration:"1 minute",save:"DEX negates",dice:"N/A",effect:"Slick grease coats the ground. A creature in the area when it appears, or entering it, makes a DEX save or falls prone; the area is difficult ground while it lasts. It burns if set alight."},
  "sleep":{kind:"spell",tier:1,cost:"slot",isMagical:true,category:["arcane"],range:"90ft",targets:"creatures in a 20ft sphere, weakest first",duration:"1 minute",save:"N/A",dice:"5d8 HP total",effect:"Roll 5d8: that many hit points of creatures fall unconscious, starting with the least wounded and working up until the pool runs out. Undead and creatures immune to charm are unaffected; damage or a hard shake wakes a sleeper."},
  "ventriloquism":{kind:"spell",tier:1,cost:"at-will",isMagical:true,category:["arcane"],range:"90ft",targets:"a point you can see",duration:"up to 1 minute",save:"INT disbelieves",dice:"N/A",effect:"Your voice issues from somewhere else — a doorway, a rafter, a statue, another person's mouth. Anything you could say, you can say from there. A suspicious listener may make an INT check to place the trick."},
  "blur":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"self",targets:"self",duration:"1 minute (concentration)",save:"N/A",dice:"N/A",effect:"Your outline swims and doubles. Attacks against you have disadvantage unless the attacker can see without eyes or otherwise ignores illusion."},
  "spider climb":{kind:"spell",tier:2,cost:"slot",isMagical:true,category:["arcane"],range:"touch",targets:"1 creature",duration:"1 hour (concentration)",save:"N/A",dice:"N/A",effect:"The target climbs sheer walls and ceilings with hands free, moving at its normal pace across any solid surface."},
  "fear":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["arcane"],range:"30ft cone",targets:"creatures in the cone",duration:"1 minute (concentration)",save:"WIS negates",dice:"N/A",effect:"Each creature in the cone sees its own worst thing; on a failed WIS save it drops what it holds and flees by the fastest route for as long as it can see you. It may repeat the save at the end of each of its turns."},
  "astral steed":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["arcane"],range:"30ft",targets:"1 summoned mount",duration:"1 hour",save:"N/A",dice:"N/A",effect:"A silver-grey horse of solid starlight forms and will carry you tirelessly at speed, over ground a real horse would refuse. It vanishes if it takes any damage, and cannot fight."},
  "telepathy":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["arcane"],range:"sight, then any distance on the same plane",targets:"1 creature",duration:"1 hour",save:"N/A",dice:"N/A",effect:"You open a private two-way channel of thought with one creature you can see. Words and images pass instantly and silently; the other party knows exactly who is speaking and may simply refuse to answer."},
  "shrink":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["arcane"],range:"30ft",targets:"1 willing creature or unattended object",duration:"10 minutes (concentration)",save:"N/A",dice:"N/A",effect:"The target halves in every dimension — through a grate, into a pocket, under a door. A shrunken creature has disadvantage on STR checks and deals a die less damage; an object's weight drops with it."},
  "breathe water":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["arcane"],range:"30ft",targets:"up to 6 creatures",duration:"4 hours",save:"N/A",dice:"N/A",effect:"The targets breathe water as easily as air for the duration. It grants no swimming speed and no protection from cold or pressure."},
  "slow":{kind:"spell",tier:3,cost:"slot",isMagical:true,category:["arcane"],range:"120ft",targets:"up to 6 creatures in a 40ft cube",duration:"1 minute (concentration)",save:"WIS negates",dice:"N/A",effect:"On a failed WIS save a creature's speed halves, it takes a penalty to AC and DEX saves, and it can take only one action or one bonus action on its turn. It may repeat the save at the end of each of its turns."},
  "charm monster":{kind:"spell",tier:4,cost:"slot",isMagical:true,category:["arcane"],range:"30ft",targets:"1 creature",duration:"1 hour",save:"WIS negates",dice:"N/A",effect:"Any creature, not merely a person, regards you as a trusted friend on a failed WIS save. It will not obey obviously suicidal orders, and it knows it was charmed when the spell ends."},
  "wall of misdirection":{kind:"spell",tier:4,cost:"slot",isMagical:true,category:["arcane"],range:"120ft",targets:"a 60ft long wall",duration:"10 minutes (concentration)",save:"INT disbelieves",dice:"N/A",effect:"A wall that shows each viewer something plausible and wrong — open road where there is a cliff, blank stone where there is a door. Creatures may pass through it freely; one who studies it and succeeds on an INT check sees it for what it is, and can then tell others."},
  "confusion":{kind:"spell",tier:4,cost:"slot",isMagical:true,category:["arcane"],range:"90ft",targets:"creatures in a 20ft sphere",duration:"1 minute (concentration)",save:"WIS negates",dice:"N/A",effect:"Affected creatures lose track of friend, foe and intent: each turn one wanders, one attacks whatever is nearest, one stands babbling. A creature may repeat the save at the end of each of its turns."},
  "archmage hand":{kind:"spell",tier:4,cost:"slot",isMagical:true,category:["arcane"],range:"120ft",targets:"1 hand",duration:"1 hour (concentration)",save:"N/A",dice:"N/A",effect:"Your Mage Hand grown to full strength and reach: invisible, it can carry a person's weight, force a stuck door, wield a weapon at your direction, or throttle. It is as strong as you are and can be attacked only by dispelling."},
  "mass charm":{kind:"spell",tier:4,cost:"slot",isMagical:true,category:["arcane"],range:"60ft",targets:"up to 8 creatures in a 30ft cube",duration:"1 hour",save:"WIS negates",dice:"N/A",effect:"A whole room takes you for a friend on a failed WIS save — a guardroom, a council, a crowd. Each knows it was charmed afterwards, which makes this a spell that buys time and costs reputation."},
  "implant memory":{kind:"spell",tier:4,cost:"slot",isMagical:true,category:["arcane"],range:"touch",targets:"1 creature",duration:"permanent until contradicted",save:"WIS negates",dice:"N/A",effect:"You give the target a memory of something that did not happen, no longer than a few minutes and no more unlikely than their own life allows. They recall it as their own and will act and testify on it. Hard evidence to the contrary lets them doubt it. The counterpart to Oubliate: this ADDS to what a mind holds rather than taking away."},
  "group telepathy":{kind:"spell",tier:4,cost:"slot",isMagical:true,category:["arcane"],range:"30ft at casting, then 1 mile",targets:"up to 6 willing creatures",duration:"1 hour",save:"N/A",dice:"N/A",effect:"You link a party in silent speech — everyone hears everyone, at a mile's spread, through walls and noise. Perfect for a heist and ruinous for an argument; a linked creature may close its end at will."}
};

// Base-name key: strip the display parenthetical, lowercase, trim. Mirrors the [SPELL_USED:] matcher.
function capBaseName(nm){return String(nm||"").replace(/\s*\(.*\)/,"").toLowerCase().trim();}

// The ONE capability lookup — used by the card, the viewer, and both injection blocks. The emergent
// per-campaign overlay (worldState.capabilityBible, filed write-once by [SPELL_DEF:]) wins over the
// static base, so a GM-defined capability — or a GM correction to a base one — is authoritative.
function capabilityLookup(nm){
  var key=capBaseName(nm);
  if(typeof worldState!=="undefined"&&worldState&&worldState.capabilityBible&&worldState.capabilityBible[key])return worldState.capabilityBible[key];
  return (typeof CAPABILITY_BIBLE!=="undefined"&&CAPABILITY_BIBLE[key])||null;
}

// capabilitiesByCategory(cat) — every capability tagged with a tradition (arcane|divine|primal|
// necromantic|martial), across the emergent overlay + static base. This is the gate for limiting a
// rolled enemy caster's menu (e.g. an enemy cleric → the "divine" list). Returns [{name, entry}]
// sorted by name; overlay entries win on name collision.
function capabilitiesByCategory(cat){
  var out=[],seen={};
  function scan(reg){if(!reg)return;for(var key in reg){if(seen[key])continue;var e=reg[key];if(e&&e.category&&e.category.indexOf(cat)>=0){out.push({name:key,entry:e});seen[key]=1;}}}
  scan((typeof worldState!=="undefined"&&worldState&&worldState.capabilityBible)?worldState.capabilityBible:null);
  scan(typeof CAPABILITY_BIBLE!=="undefined"?CAPABILITY_BIBLE:null);
  out.sort(function(a,b){return a.name<b.name?-1:1;});
  return out;
}
