// ─── CLASS BIBLE (TODO #72) ─────────────────────────────────────────────────────────────────
// THE single definitive source for character progression: classes, per-level features,
// archetype spines (L3 identity / 6 / 10 / 14 / 18 / L20 capstone), spell tier lists, skill
// seeds, and the 1-20 XP curve. Spec: DOC/DOC_class_bible.html (R2 — all forks ruled
// 2026-07-27: picks at tier-unlock levels; table extended to L20; creation-only skill seeds).
//
// ⚠ NOT WIRED INTO THE ENGINE YET. Until the C6 sequence lands (classDef() lookup → store
// swap → CLSS deleted), the game still reads CLSS/CLASS_FEATURES/ABILS/ARCHETYPES/ARCH_SPELLS/
// STAT_PRIORITY/SPELLS. This file is loaded by the satellites (bible_editor.html) and the
// engine-test harness only. Divergence from the legacy tables during the fill phase is
// EXPECTED (this file runs ahead); the legacy tables remain engine truth until C6-②.
//
// FORMAT RULES (the editor depends on them):
//  · The data between the >>> <<< markers is machine-REGENERATED by bible_editor.html's
//    exporter — no hand comments inside the markers (they would be lost on export).
//  · Serialization is canonical: JSON.stringify(obj, null, 2). The BIBLE EDITOR CONTRACT
//    (dev/run-tests.js) byte-compares a fresh serialize against this region, so a hand edit
//    that breaks canonical form fails the build instead of silently fighting the editor.
//  · Feature shape {nm, ds}: nm is the capability_bible key once the feature is authored
//    there (the racial_caps pattern — mechanics live in ONE place); ds is legacy/summary
//    prose. Empty features arrays are FILL-PHASE blanks, not errors.
//  · spellTiers maps tier → unlock level (C2). Empty spell-tier arrays are fill-phase
//    blanks. Half-caster (Ranger/Paladin) tiers are DRAFT pending the fill phase.
//  · CLASS_XP_LEVELS 1-10 = the shipped XP_LEVELS verbatim; 11-20 = spec R2 draft numbers.
// >>> CLASS BIBLE DATA
var CLASS_XP_LEVELS = [0,300,900,2700,6500,14000,23000,34000,48000,64000,85000,100000,120000,140000,165000,195000,225000,265000,305000,355000];
var CLASS_BIBLE = {
  "Warrior": {
    "id": "Warrior",
    "nm": "Warrior",
    "hd": 12,
    "prime": "STR",
    "desc": "Weapon master, armor bearer",
    "gear": "hand-and-a-half sword, chainmail, belt knife, travel rations (3 days)",
    "statPriority": [
      "STR",
      "CON",
      "DEX",
      "WIS",
      "CHA",
      "INT"
    ],
    "abilities": [
      {
        "nm": "Power Strike",
        "ds": "+d6 bonus damage on a declared attack."
      },
      {
        "nm": "Shield Wall",
        "ds": "Reduce incoming damage by 3 until next turn."
      },
      {
        "nm": "Weapon Mastery",
        "ds": "No penalty for improvised or unfamiliar arms."
      }
    ],
    "skillSeeds": [],
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Action Surge",
            "ds": "one additional action, once per rest."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Extra Attack",
            "ds": "attack twice per action."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Indomitable",
            "ds": "reroll a failed save, once per rest."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Indomitable (x2)",
            "ds": "twice per rest."
          }
        ]
      },
      "11": {
        "features": []
      },
      "13": {
        "features": []
      },
      "15": {
        "features": []
      },
      "17": {
        "features": []
      }
    },
    "archetypes": [
      {
        "id": "champion",
        "nm": "Champion",
        "desc": "Critical hits on 19-20. Superior Athlete. Remarkable endurance in battle.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "The Telling Blow",
                "ds": "Your strikes land where they hurt most — wounds you deal are graver than they have any right to be, and foes remember them."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Peak of the Body",
                "ds": "Any feat of raw athleticism a human could dream of, you can do: leap the chasm, kick down the oak door, carry the ox."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Last One Standing",
                "ds": "Pain, exhaustion, and wounds do not slow you — you fight at full strength until the fight is done, and you don't drop while anyone needs you standing."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "One Against Many",
                "ds": "Surrounded is where you're strongest: every attacker is in your reach, numbers grant them nothing, and a room of soldiers is a queue."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Strength of Legend",
                "ds": "Feats beyond mortal — hold the falling gate, bend the portcullis. Bards argue over which stories are true; all of them are."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Challenge",
                "ds": "Once, call out any creature by name: it must meet you alone in the circle, and nothing outside may touch what happens within."
              }
            ]
          }
        }
      },
      {
        "id": "battlemaster",
        "nm": "Battle Master",
        "desc": "Maneuver dice to trip, disarm, feint, and rally allies in combat.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "The Read",
                "ds": "One look at a fighter and you know their style, their training, and the mistake they will make."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Wordless Command",
                "ds": "Your allies fight as though rehearsed — a glance repositions a companion; the party has a plan even when there was no time to make one."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "The Turning Move",
                "ds": "Once per combat, call the moment that turns the fight — trip, disarm, feint, rally — and it succeeds; named foes contest."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "The Battlefield Is a Board",
                "ds": "You see the whole engagement at once: where reinforcements enter, when morale breaks, what each combatant does next."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "A Call to Arms",
                "ds": "Conscript 5d10 locals into an army under your command — each soldier level 2d6, armed to their station. One army at a time; a new one disbands the old."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Plan Holds",
                "ds": "Once, lay the plan out loud: as long as it's followed, each step succeeds as described — until the objective, an abandoned step, or a betrayal."
              }
            ]
          }
        }
      },
      {
        "id": "eldritchknight",
        "nm": "Eldritch Knight",
        "desc": "Abjuration and evocation spells. Weapon Bond -- blade returns to hand always.",
        "spellTiers": {
          "1": 3,
          "2": 10,
          "3": 14,
          "4": 18
        },
        "spells": {
          "1": [
            "Shield",
            "Absorb Elements",
            "Magic Missile"
          ],
          "2": [
            "Misty Step",
            "Mirror Image"
          ],
          "3": [],
          "4": [],
          "cantrips": [
            "Fire Bolt",
            "Booming Blade"
          ]
        },
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Weapon Bond",
                "ds": "Your bonded blade always returns to your hand — thrown, disarmed, stolen, oceans apart; it comes when called."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Spellblade",
                "ds": "Your spells flow through the steel — casting and striking are one motion, a slash that carries the spell."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Sundering Stroke",
                "ds": "Your blade cuts magic itself: sever an enchantment, cut a summoning from its anchor, part a wall of flame."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Soul Steal",
                "ds": "Your blade drinks the soul of what it cuts, taking one of the victim's abilities for 4 hours — three held at once, nothing new until one expires or is released."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "The Standing Ward",
                "ds": "You can ward a place — castle, bridge, village: no magic enters unbidden while you keep it, and you know every arcane trespass."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Blade Keeps Faith",
                "ds": "Once, when death takes you, it doesn't — the bond pulls you back; you wake, blade in hand, wherever the blade lies."
              }
            ]
          }
        }
      }
    ]
  },
  "Rogue": {
    "id": "Rogue",
    "nm": "Rogue",
    "hd": 8,
    "prime": "DEX",
    "desc": "Shadow, cunning, and coin",
    "gear": "short blades x2, leather armor, lockpicks, smoke powder, travel rations (3 days), first aid pack",
    "statPriority": [
      "DEX",
      "INT",
      "CHA",
      "CON",
      "WIS",
      "STR"
    ],
    "abilities": [
      {
        "nm": "Sneak Attack",
        "ds": "Double damage dice when unseen or flanking."
      },
      {
        "nm": "Evasion",
        "ds": "On a failed DEX save, take half damage instead of full."
      },
      {
        "nm": "Lockpick",
        "ds": "Open locks and bypass traps with a DEX check."
      }
    ],
    "skillSeeds": [
      "Stealth",
      "Lockpicking"
    ],
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Cunning Action",
            "ds": "Dash, Disengage, or Hide as bonus action."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Uncanny Dodge",
            "ds": "halve an attack's damage as reaction."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Evasion",
            "ds": "no damage on successful DEX saves, half on fail."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Blindsense",
            "ds": "know location of hidden creatures within 10ft."
          }
        ]
      },
      "11": {
        "features": [
          {
            "nm": "Silent Stalker",
            "ds": "moves without making a sound"
          }
        ]
      },
      "13": {
        "features": [
          {
            "nm": "Hide in Plain Sight",
            "ds": "can fade into a crowd undetected"
          }
        ]
      },
      "15": {
        "features": [
          {
            "nm": "Escape Artist",
            "ds": "cannot be bound by non magical means"
          }
        ]
      },
      "17": {
        "features": [
          {
            "nm": "Summon Item",
            "ds": "teleports a small item to the hand of the rogue."
          }
        ]
      }
    },
    "archetypes": [
      {
        "id": "thief",
        "nm": "Thief",
        "desc": "Use objects and magic items as a bonus action. Fast Hands. Supreme Sneak.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Legerdemain",
                "ds": "Anything within arm's reach you can already have taken — victims discover the loss later, not now."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "No Lock Holds",
                "ds": "Locks, knots, seals, and traps open for you; a lock is a suggestion, not a barrier."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "The Casing Eye",
                "ds": "One look at a room and you know where the valuables are, who holds the keys, and every way out."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "The Shirt Off Your Back",
                "ds": "You can steal what is worn, held, or watched — a sword from a hand, a ring mid-handshake."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Word of the Score",
                "ds": "Rumor of every treasure, vault, and hidden thing finds its way to you wherever you go."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Impossible Theft",
                "ds": "Once, steal a thing no hand should hold — a god's flame, a house's luck, a word from a language."
              }
            ]
          }
        }
      },
      {
        "id": "assassin",
        "nm": "Assassin",
        "desc": "Automatic crit against surprised targets. Perfect disguise. Infiltration Expertise.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "The First Blow Is the Last",
                "ds": "Your first strike against an unsuspecting target is an automatic critical hit; against ordinary folk the fight is over before it begins."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Master Poisoner",
                "ds": "Any food, drink, or weapon can be lethally poisoned in moments, improvised and creative — onset and symptoms are yours to design."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Sure Shot",
                "ds": "Once per combat, declare an impossible ranged shot — ricochet, bank shot, needle-threading, extreme distance — it hits, critically. If you can see it, you can kill it."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "A Natural Death",
                "ds": "Your kills wear whatever face you choose — a fall, a fever, a stopped heart; no one reads murder in them unless you want them to."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Angel of Death",
                "ds": "Once per day, nothing bars your approach to a target within 150 feet — walls gap, wards seam, guards look away. The kill and the leaving are still yours."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Inevitable End",
                "ds": "Once, name a target: their death becomes when, not if — the story bends toward the ending you chose, supplying opportunity but never the kill itself."
              }
            ]
          }
        }
      },
      {
        "id": "arcanetrickster",
        "nm": "Arcane Trickster",
        "desc": "Illusion and enchantment spells. Mage Hand for theft. Distract and confuse.",
        "spellTiers": {
          "1": 3,
          "2": 10,
          "3": 14,
          "4": 18
        },
        "spells": {
          "1": [
            "Charm Person",
            "Silent Image",
            "Disguise Self",
            "Feather Fall",
            "Fog Bank",
            "Leap",
            "Grease",
            "Sleep",
            "Ventriloquism"
          ],
          "2": [
            "Invisibility",
            "Shadow Blade",
            "Knock",
            "Darkness",
            "Shadow Step",
            "Mirror Image",
            "Blur",
            "Spider Climb",
            "Hold Person",
            "Misty Step"
          ],
          "3": [
            "Blink",
            "Lethe's Kiss",
            "Fear",
            "Astral Steed",
            "Telepathy",
            "Shrink",
            "Breathe Water",
            "Slow"
          ],
          "4": [
            "Oubliate",
            "Charm Monster",
            "Wall of Misdirection",
            "Confusion",
            "Archmage Hand",
            "Mass Charm",
            "Implant Memory",
            "Group Telepathy",
            "Mirror Image"
          ],
          "cantrips": [
            "Mage Hand",
            "Minor Illusion",
            "Message",
            "Flash"
          ]
        },
        "levels": {
          "3": {
            "features": [
              {
                "nm": "The Old Switcheroo",
                "ds": "Your invisible Mage Hand swaps two objects at 30ft; both holders keep believing they hold what they held."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "It Was Their Idea",
                "ds": "A suggestion you plant is remembered by the target as their own notion, and defended to others as such."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Seventy-Two Shapes",
                "ds": "Take the form of any person or creature you have seen; it holds until you choose to drop it."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Never Caught",
                "ds": "The first time each scene you would be seized or cornered, you simply are not — and they half-remember letting you go."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "The Story Runs Ahead",
                "ds": "A rumour you set loose is true by the time it arrives — it creates circumstance, never undoes what happened."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "Turnabout",
                "ds": "CAPSTONE: once, you and another creature exchange place, bonds, condition and blame — and everyone proceeds as though it had always been so."
              }
            ]
          }
        }
      }
    ]
  },
  "Sorcerer": {
    "id": "Sorcerer",
    "nm": "Sorcerer",
    "hd": 6,
    "prime": "INT",
    "desc": "Arcane power, fragile body",
    "gear": "carved staff, spell components, grimoire, travel rations (3 days)",
    "statPriority": [
      "INT",
      "DEX",
      "CON",
      "WIS",
      "CHA",
      "STR"
    ],
    "abilities": [
      {
        "nm": "Arcane Bolt",
        "ds": "Ranged magic attack. INT vs AC, d8 damage."
      },
      {
        "nm": "Fire Lance",
        "ds": "d10 damage, ignites flammable targets."
      },
      {
        "nm": "Arcane Shield",
        "ds": "Absorbs 5 damage. Lasts until hit."
      },
      {
        "nm": "Blink",
        "ds": "Teleport 30ft. DC15 DEX or arrive off target."
      }
    ],
    "skillSeeds": [],
    "spellTiers": {
      "2": 5,
      "3": 7,
      "4": 9,
      "5": 11,
      "6": 15
    },
    "spells": {
      "1": [
        "Magic Missile",
        "Shield",
        "Thunderwave",
        "Chromatic Orb"
      ],
      "2": [
        "Misty Step",
        "Scorching Ray",
        "Hold Person",
        "Invisibility"
      ],
      "3": [
        "Fireball",
        "Counterspell",
        "Fly"
      ],
      "4": [],
      "5": [],
      "6": [],
      "cantrips": [
        "Fire Bolt",
        "Ray of Frost",
        "Mage Hand",
        "Prestidigitation"
      ]
    },
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Font of Magic",
            "ds": "sorcery points for spell slots and metamagic."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Metamagic",
            "ds": "Quickened, Twinned, Extended, Subtle spells."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Sorcerous Restoration",
            "ds": "regain 4 sorcery points on short rest."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Overchannel",
            "ds": "maximize spell damage at HP cost."
          }
        ]
      },
      "11": {
        "features": []
      },
      "13": {
        "features": []
      },
      "15": {
        "features": []
      },
      "17": {
        "features": []
      }
    },
    "archetypes": [
      {
        "id": "draconic",
        "nm": "Draconic Bloodline",
        "desc": "Dragon ancestry. Bonus HP per level. Elemental affinity. Wings at high level.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      },
      {
        "id": "wildmagic",
        "nm": "Wild Magic",
        "desc": "Chaotic unstable power. Random surges. Tides of Chaos for lucky advantage.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      },
      {
        "id": "shadow",
        "nm": "Shadow Magic",
        "desc": "Power from the Shadowfell. Darkvision. Hound of Ill Omen. Shadow Walk.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      }
    ]
  },
  "Ranger": {
    "id": "Ranger",
    "nm": "Ranger",
    "hd": 10,
    "prime": "DEX",
    "desc": "Hunter and tracker",
    "gear": "recurve bow, hunting knife, leather armor, trail kit, travel rations (3 days)",
    "statPriority": [
      "DEX",
      "WIS",
      "CON",
      "STR",
      "INT",
      "CHA"
    ],
    "abilities": [
      {
        "nm": "Hunter's Mark",
        "ds": "Mark a target. +d4 damage and advantage on tracking."
      },
      {
        "nm": "Trackless Step",
        "ds": "Leave no trail in natural terrain."
      },
      {
        "nm": "Volley",
        "ds": "Hit up to 2 targets in range with one action."
      }
    ],
    "skillSeeds": [],
    "spellTiers": {
      "2": 7,
      "3": 9,
      "4": 13
    },
    "spells": {
      "1": [
        "Hunter's Mark",
        "Cure Wounds",
        "Ensnaring Strike",
        "Hail of Thorns"
      ],
      "2": [
        "Pass Without Trace",
        "Spike Growth",
        "Silence"
      ],
      "3": [
        "Conjure Barrage",
        "Lightning Arrow"
      ],
      "4": []
    },
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Fighting Style",
            "ds": "Archery, Defense, Dueling, or Two-Weapon."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Extra Attack",
            "ds": "attack twice per action."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Land's Stride",
            "ds": "no difficult terrain penalty."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Hide in Plain Sight",
            "ds": "+10 Stealth camouflage."
          }
        ]
      },
      "11": {
        "features": []
      },
      "13": {
        "features": []
      },
      "15": {
        "features": []
      },
      "17": {
        "features": []
      }
    },
    "archetypes": [
      {
        "id": "hunter",
        "nm": "Hunter",
        "desc": "Colossus Slayer on wounded targets. Giant Killer reaction. Defensive multiattack.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      },
      {
        "id": "beastmaster",
        "nm": "Beast Master",
        "desc": "Bond with a beast companion that fights alongside you. Primal bond.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      },
      {
        "id": "gloomstalker",
        "nm": "Gloom Stalker",
        "desc": "Invisible in magical darkness. Extra attack on first round. Dread Ambusher.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      }
    ]
  },
  "Primal": {
    "id": "Primal",
    "nm": "Primal",
    "hd": 12,
    "prime": "STR",
    "desc": "Rage, beast, and storm",
    "gear": "great axe, hide armor, war paint, iron flask, travel rations (3 days)",
    "statPriority": [
      "STR",
      "CON",
      "DEX",
      "WIS",
      "CHA",
      "INT"
    ],
    "abilities": [
      {
        "nm": "Rage",
        "ds": "+2 STR, +2 damage, ignore pain. Lasts 3 rounds."
      },
      {
        "nm": "Reckless Attack",
        "ds": "Advantage on attack, enemy has advantage back."
      },
      {
        "nm": "Intimidating Presence",
        "ds": "CHA check to terrify. Success: enemy shaken (-2 all rolls)."
      }
    ],
    "skillSeeds": [],
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Danger Sense",
            "ds": "advantage on DEX saves vs visible effects."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Extra Attack",
            "ds": "attack twice per action."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Feral Instinct",
            "ds": "advantage on initiative. Act normally if surprised while raging."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Brutal Critical",
            "ds": "extra damage die on critical hits."
          }
        ]
      },
      "11": {
        "features": []
      },
      "13": {
        "features": []
      },
      "15": {
        "features": []
      },
      "17": {
        "features": []
      }
    },
    "archetypes": [
      {
        "id": "totem",
        "nm": "Totemborn",
        "desc": "Spirit animal bond. Bear for resistance, Eagle for mobility, Wolf for pack tactics.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      },
      {
        "id": "frenzy",
        "nm": "Berserker",
        "desc": "Frenzied rage -- bonus attack every turn. Immune to charm and fear while raging.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      },
      {
        "id": "stormherald",
        "nm": "Stormcaller",
        "desc": "Aura of lightning, thunder, or arctic cold. Living storm of destruction.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      }
    ]
  },
  "Paladin": {
    "id": "Paladin",
    "nm": "Paladin",
    "hd": 10,
    "prime": "CHA",
    "desc": "Holy warrior, oath-bound",
    "gear": "longsword, shield, chainmail, holy symbol, travel rations (3 days)",
    "statPriority": [
      "CHA",
      "STR",
      "CON",
      "WIS",
      "DEX",
      "INT"
    ],
    "abilities": [
      {
        "nm": "Divine Smite",
        "ds": "Expend a spell slot to deal +2d8 radiant damage on a hit."
      },
      {
        "nm": "Lay on Hands",
        "ds": "Pool of 5xLevel HP. Touch to heal or cure disease/poison."
      },
      {
        "nm": "Divine Sense",
        "ds": "Detect undead, fiends, and celestials within 60ft."
      }
    ],
    "skillSeeds": [],
    "spellTiers": {
      "2": 7,
      "3": 9,
      "4": 13
    },
    "spells": {
      "1": [
        "Divine Smite",
        "Cure Wounds",
        "Bless",
        "Shield of Faith"
      ],
      "2": [
        "Aid",
        "Magic Weapon",
        "Find Steed"
      ],
      "3": [
        "Revivify",
        "Dispel Magic",
        "Aura of Vitality"
      ],
      "4": []
    },
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Fighting Style",
            "ds": "Defense, Dueling, Great Weapon, or Protection."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Extra Attack",
            "ds": "attack twice per action."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Aura of Protection",
            "ds": "add CHA modifier to saves within 10ft."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Aura of Courage",
            "ds": "allies within 10ft cannot be frightened."
          }
        ]
      },
      "11": {
        "features": []
      },
      "13": {
        "features": []
      },
      "15": {
        "features": []
      },
      "17": {
        "features": []
      }
    },
    "archetypes": [
      {
        "id": "vengeance",
        "nm": "Oath of Vengeance",
        "desc": "Hunter of the wicked. Vow of Enmity for advantage. Relentless pursuit. Banishment.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      },
      {
        "id": "devotion",
        "nm": "Oath of Devotion",
        "desc": "Sacred Weapon -- add CHA to attacks. Holy Nimbus aura. Purity of spirit.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      },
      {
        "id": "ancients",
        "nm": "Oath of Ancients",
        "desc": "Nature's warrior. Aura of Warding vs spells. Undying Sentinel at 0 HP.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      }
    ]
  },
  "Cleric": {
    "id": "Cleric",
    "nm": "Cleric",
    "hd": 8,
    "prime": "WIS",
    "desc": "Divine power, battle priest",
    "gear": "mace, scale armor, shield, holy symbol, prayer beads, travel rations (3 days)",
    "statPriority": [
      "WIS",
      "CON",
      "STR",
      "CHA",
      "DEX",
      "INT"
    ],
    "abilities": [
      {
        "nm": "Sacred Flame",
        "ds": "Radiant damage cantrip. DEX save or take d8 radiant."
      },
      {
        "nm": "Turn Undead",
        "ds": "Undead within 30ft must flee. DC = 8+WIS+proficiency."
      },
      {
        "nm": "Healing Word",
        "ds": "Bonus action. Heal target for d4+WIS modifier HP."
      }
    ],
    "skillSeeds": [],
    "spellTiers": {
      "2": 5,
      "3": 7,
      "4": 9,
      "5": 11,
      "6": 15
    },
    "spells": {
      "1": [
        "Healing Word",
        "Bless",
        "Guiding Bolt",
        "Shield of Faith"
      ],
      "2": [
        "Spiritual Weapon",
        "Hold Person",
        "Lesser Restoration"
      ],
      "3": [
        "Spirit Guardians",
        "Revivify",
        "Dispel Magic"
      ],
      "4": [],
      "5": [],
      "6": [],
      "cantrips": [
        "Sacred Flame",
        "Guidance",
        "Spare the Dying",
        "Thaumaturgy"
      ]
    },
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Channel Divinity",
            "ds": "powerful divine ability, once per rest."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Destroy Undead",
            "ds": "Turn Undead destroys weaker undead outright."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Divine Strike",
            "ds": "bonus damage of domain type, once per turn."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Divine Intervention",
            "ds": "10% chance of deity response."
          }
        ]
      },
      "11": {
        "features": []
      },
      "13": {
        "features": []
      },
      "15": {
        "features": []
      },
      "17": {
        "features": []
      }
    },
    "archetypes": [
      {
        "id": "life",
        "nm": "Life Domain",
        "desc": "Master healer. Disciple of Life -- healing spells restore bonus HP. Preserve Life.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      },
      {
        "id": "war",
        "nm": "War Domain",
        "desc": "God of battle. War Priest bonus attack. Guided Strike -- +10 to a missed attack.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      },
      {
        "id": "trickery",
        "nm": "Trickery Domain",
        "desc": "Deception and illusion. Invoke Duplicity -- create a perfect duplicate of yourself.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      }
    ]
  },
  "Druid": {
    "id": "Druid",
    "nm": "Druid",
    "hd": 8,
    "prime": "WIS",
    "desc": "Nature magic, wild shape",
    "gear": "wooden staff, leather armor, herbalism kit, totem fetish, travel rations (3 days)",
    "statPriority": [
      "WIS",
      "CON",
      "DEX",
      "INT",
      "CHA",
      "STR"
    ],
    "abilities": [
      {
        "nm": "Wild Shape",
        "ds": "Transform into a beast. CR limit scales with level."
      },
      {
        "nm": "Druidic",
        "ds": "Secret language of druids. Leave hidden messages in nature."
      },
      {
        "nm": "Speak with Animals",
        "ds": "Communicate with beasts. They share what they have sensed."
      }
    ],
    "skillSeeds": [],
    "spellTiers": {
      "2": 5,
      "3": 7,
      "4": 9,
      "5": 11,
      "6": 15
    },
    "spells": {
      "1": [
        "Entangle",
        "Healing Word",
        "Thunderwave",
        "Faerie Fire"
      ],
      "2": [
        "Moonbeam",
        "Barkskin",
        "Pass Without Trace"
      ],
      "3": [
        "Call Lightning",
        "Conjure Animals",
        "Plant Growth"
      ],
      "4": [],
      "5": [],
      "6": [],
      "cantrips": [
        "Produce Flame",
        "Shillelagh",
        "Druidcraft",
        "Thorn Whip"
      ]
    },
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Wild Shape (CR 1/4)",
            "ds": "transform into a beast you have seen."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Wild Shape (CR 1)",
            "ds": "more powerful beast forms available."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Timeless Body",
            "ds": "age at 1/10 normal rate."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Beast Spells",
            "ds": "cast druid spells while in Wild Shape."
          }
        ]
      },
      "11": {
        "features": []
      },
      "13": {
        "features": []
      },
      "15": {
        "features": []
      },
      "17": {
        "features": []
      }
    },
    "archetypes": [
      {
        "id": "land",
        "nm": "Circle of the Land",
        "desc": "Ancient magic of terrain. Bonus spells by terrain type. Natural Recovery of spell slots.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      },
      {
        "id": "moon",
        "nm": "Circle of the Moon",
        "desc": "Powerful Wild Shape. Combat beast forms. Elemental forms at high level.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      },
      {
        "id": "spores",
        "nm": "Circle of Spores",
        "desc": "Halo of Spores necrotic damage. Symbiotic Entity -- enhanced Wild Shape for combat.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      }
    ]
  },
  "Necromancer": {
    "id": "Necromancer",
    "nm": "Necromancer",
    "hd": 6,
    "prime": "INT",
    "desc": "Death magic, bone and shadow",
    "gear": "skull focus, dark robes, grimoire of the dead, grave dust pouch, travel rations (3 days)",
    "statPriority": [
      "INT",
      "CON",
      "DEX",
      "WIS",
      "CHA",
      "STR"
    ],
    "abilities": [
      {
        "nm": "Raise Thrall",
        "ds": "Animate a fresh corpse within 10ft as a zombie thrall. Requires a body present. The thrall follows basic commands and collapses if you fall unconscious. One thrall at a time until your archetype expands this."
      },
      {
        "nm": "Drain Life",
        "ds": "Melee or 30ft necrotic attack. Deal d6 necrotic damage; regain HP equal to half the damage dealt."
      },
      {
        "nm": "Death Sight",
        "ds": "Sense undead, corpses, and death-taint within 60ft without seeing them. Advantage on Arcana and Lore checks involving undead, curses, or death magic."
      }
    ],
    "skillSeeds": [],
    "spellTiers": {
      "2": 5,
      "3": 7,
      "4": 9,
      "5": 11,
      "6": 15
    },
    "spells": {
      "1": [
        "Inflict Wounds",
        "Ray of Sickness",
        "False Life",
        "Cause Fear",
        "Bleed"
      ],
      "2": [
        "Ray of Enfeeblement",
        "Blindness",
        "Shadow Step",
        "Shackles of Bone",
        "Rot"
      ],
      "3": [
        "Vampiric Touch",
        "Speak with Dead",
        "Wave of Scarabs",
        "Bestow Curse",
        "Miasma",
        "Death Walk"
      ],
      "4": [
        "Rigor Mortis",
        "Possess Thrall",
        "Sleep of the Dead"
      ],
      "5": [],
      "6": [],
      "cantrips": [
        "Chill Touch",
        "Toll the Dead",
        "Bone Whisper",
        "Grave Touch"
      ]
    },
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Undead Thrall",
            "ds": "your Raise Thrall servant persists permanently until destroyed. Gains bonus HP equal to your INT modifier. Can follow complex multi-step orders."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Grim Harvest",
            "ds": "when you kill a creature with a spell, regain HP equal to twice the spell's level (minimum 2). Once per turn."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Necrotic Resilience",
            "ds": "resistance to necrotic damage, advantage on death saving throws. Undead you control cannot be Turned by Clerics or Paladins."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Command Undead",
            "ds": "attempt to seize control of any undead creature you can see. INT save (DC 8 + INT modifier + proficiency). Success: under your control for 24 hours."
          }
        ]
      },
      "11": {
        "features": []
      },
      "13": {
        "features": []
      },
      "15": {
        "features": []
      },
      "17": {
        "features": []
      }
    },
    "archetypes": [
      {
        "id": "bonesculptor",
        "nm": "Bone Sculptor",
        "desc": "Raise up to 3 thralls simultaneously from available corpses with one casting. Thralls gain +2 AC from bone reinforcement. Can animate dead from a distance of 30ft. The path to undeath begins here.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      },
      {
        "id": "shadowweaver",
        "nm": "Shadow Weaver",
        "desc": "Teleport between areas of dim light or darkness within 60ft as a bonus action. Once per rest -- Wraith Form: become incorporeal for 1 round, immune to physical damage and able to pass through walls.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      },
      {
        "id": "soulbinder",
        "nm": "Soul Binder",
        "desc": "Trap a dying creature's soul in a prepared vessel (bone, gem, or bottle). One soul per casting, unlimited vessels. Bound souls answer questions truthfully or can be shattered for a 15ft burst of 3d8 necrotic damage.",
        "levels": {
          "3": {
            "features": []
          },
          "6": {
            "features": []
          },
          "10": {
            "features": []
          },
          "14": {
            "features": []
          },
          "18": {
            "features": []
          },
          "20": {
            "features": []
          }
        }
      }
    ]
  }
};
// <<< CLASS BIBLE DATA
