// ─── CLASS BIBLE (TODO #72) ─────────────────────────────────────────────────────────────────
// THE single definitive source for character progression: classes, per-level features,
// archetype spines (L3 identity / 6 / 10 / 14 / 18 / L20 capstone), spell tier lists, skill
// seeds, and the 1-20 XP curve. Spec: DOC/Research/DOC_class_bible.html (R2 — all forks ruled
// 2026-07-27: picks at tier-unlock levels; table extended to L20; creation-only skill seeds).
//
// ⚠ ENGINE-WIRED SINCE C6 (all three steps landed 2026-08-03, v1.533/v1.534): the engine reads
// THIS file through classDef()/classDefs()/classFeaturesAt()/archFeaturesAt()/classXpLevels()
// (helpers.js); the legacy class tables (CLSS/ABILS/CLASS_FEATURES/ARCHETYPES/STAT_PRIORITY/
// XP_LEVELS) are DELETED. Creation spell-pick pools (SPELLS/ARCH_SPELLS, data.js) stay separate
// until #72 C2 lands spell growth. Loaded by the app shell, the satellites, and the test harness.
//
// FORMAT RULES (the editor depends on them):
//  · The data between the >>> <<< markers is machine-REGENERATED by bible_editor.html's
//    exporter — no hand comments inside the markers (they would be lost on export).
//  · Serialization is canonical: JSON.stringify(obj, null, 2). The BIBLE EDITOR CONTRACT
//    (dev/run-tests.js) byte-compares a fresh serialize against this region, so a hand edit
//    that breaks canonical form fails the build instead of silently fighting the editor.
//  · Feature shape {nm, ds}: nm is the capability_bible key once the feature is authored
//    there (the racial_caps pattern — mechanics live in ONE place); ds is legacy/summary
//    prose. Empty features arrays are FILL-PHASE blanks, not errors.
//  · spellTiers maps tier → unlock level (C2). Empty spell-tier arrays are fill-phase
//    blanks. Half-caster (Ranger/Paladin) tiers are DRAFT pending the fill phase.
//  · CLASS_XP_LEVELS 1-10 = the shipped XP_LEVELS verbatim; 11-20 = spec R2 draft numbers.
// >>> CLASS BIBLE DATA
var CLASS_XP_LEVELS = [0,300,900,2700,6500,14000,23000,34000,48000,64000,85000,100000,120000,140000,165000,195000,225000,265000,305000,355000];
var CLASS_BIBLE = {
  "Warrior": {
    "id": "Warrior",
    "nm": "Warrior",
    "hd": 12,
    "prime": "STR",
    "castStat": "INT",
    "desc": "Weapon master, armor bearer",
    "gear": "hand-and-a-half sword, chainmail, belt knife, travel rations (3 days), first aide kit.",
    "statPriority": [
      "STR",
      "CON",
      "DEX",
      "WIS",
      "CHA",
      "INT"
    ],
    "abilities": [
      {
        "nm": "Power Strike",
        "ds": "+d6 bonus damage on a declared attack."
      },
      {
        "nm": "Shield Wall",
        "ds": "Reduce incoming damage by 3 until next turn."
      },
      {
        "nm": "Weapon Mastery",
        "ds": "No penalty for improvised or unfamiliar arms."
      }
    ],
    "skillSeeds": [
      "Intimidation",
      "Endure Pain"
    ],
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Action Surge",
            "ds": "one additional action, once per rest."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Stunning Blow",
            "ds": "Forgo a hit's damage to stun instead — CON save negates. Any foe can be caught by it only once; they never fall for the same blow twice."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Resilience",
            "ds": "You recover 1 hit point per level every hour — a Warrior who walks off a battlefield is whole by nightfall, with no healer."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Taunt",
            "ds": "Make yourself the only thing worth killing: for 3 rounds every foe who heard you attacks you instead of your companions."
          }
        ]
      },
      "11": {
        "features": [
          {
            "nm": "Double Attack",
            "ds": "You attack twice on your turn, and may split the two attacks between different targets."
          }
        ]
      },
      "13": {
        "features": [
          {
            "nm": "Counter Attack",
            "ds": "Roll d20 against each melee attack on you; under your level you counter — half damage taken, and you answer with a strike of your own."
          }
        ]
      },
      "15": {
        "features": [
          {
            "nm": "Iron Constitution",
            "ds": "Every Constitution save succeeds automatically except on a natural 1. Your body has stopped negotiating."
          }
        ]
      },
      "17": {
        "features": [
          {
            "nm": "Unstoppable",
            "ds": "While you have hit points nothing takes you out of the fight — no stun, paralysis, restraint, prone, disarm, or forced movement. You can be killed; you cannot be handled."
          }
        ]
      }
    },
    "archetypes": [
      {
        "id": "champion",
        "nm": "Champion",
        "desc": "Critical hits on 19-20. Superior Athlete. Remarkable endurance in battle.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "The Telling Blow",
                "ds": "Your strikes land where they hurt most — wounds you deal are graver than they have any right to be, and foes remember them."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Peak of the Body",
                "ds": "Any feat of raw athleticism a human could dream of, you can do: leap the chasm, kick down the oak door, carry the ox."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Last One Standing",
                "ds": "Pain, exhaustion, and wounds do not slow you — you fight at full strength until the fight is done, and you don't drop while anyone needs you standing."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "One Against Many",
                "ds": "Surrounded is where you're strongest: every attacker is in your reach, numbers grant them nothing, and a room of soldiers is a queue."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Strength of Legend",
                "ds": "Feats beyond mortal — hold the falling gate, bend the portcullis. Bards argue over which stories are true; all of them are."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Challenge",
                "ds": "Once, call out any creature by name: it must meet you alone in the circle, and nothing outside may touch what happens within."
              }
            ]
          }
        }
      },
      {
        "id": "battlemaster",
        "nm": "Battle Master",
        "desc": "Maneuver dice to trip, disarm, feint, and rally allies in combat.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "The Read",
                "ds": "One look at a fighter and you know their style, their training, and the mistake they will make."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Wordless Command",
                "ds": "Your allies fight as though rehearsed — a glance repositions a companion; the party has a plan even when there was no time to make one."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "The Turning Move",
                "ds": "Once per combat, call the moment that turns the fight — trip, disarm, feint, rally — and it succeeds; named foes contest."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "The Battlefield Is a Board",
                "ds": "You see the whole engagement at once: where reinforcements enter, when morale breaks, what each combatant does next."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "A Call to Arms",
                "ds": "Conscript 5d10 locals into an army under your command — each soldier level 2d6, armed to their station. One army at a time; a new one disbands the old."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Plan Holds",
                "ds": "Once, lay the plan out loud: as long as it's followed, each step succeeds as described — until the objective, an abandoned step, or a betrayal."
              }
            ]
          }
        }
      },
      {
        "id": "eldritchknight",
        "nm": "Eldritch Knight",
        "desc": "Abjuration and evocation spells. Weapon Bond -- blade returns to hand always.",
        "spellTiers": {
          "1": 3,
          "2": 10,
          "3": 14,
          "4": 18
        },
        "spells": {
          "1": [
            "Shield",
            "Absorb Elements",
            "Magic Missile"
          ],
          "2": [
            "Misty Step",
            "Mirror Image"
          ],
          "3": [],
          "4": [],
          "cantrips": [
            "Fire Bolt",
            "Booming Blade"
          ]
        },
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Weapon Bond",
                "ds": "Your bonded blade always returns to your hand — thrown, disarmed, stolen, oceans apart; it comes when called."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Spellblade",
                "ds": "Your spells flow through the steel — casting and striking are one motion, a slash that carries the spell."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Sundering Stroke",
                "ds": "Your blade cuts magic itself: sever an enchantment, cut a summoning from its anchor, part a wall of flame."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Soul Steal",
                "ds": "Your blade drinks the soul of what it cuts, taking one of the victim's abilities for 4 hours — three held at once, nothing new until one expires or is released."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "The Standing Ward",
                "ds": "You can ward a place — castle, bridge, village: no magic enters unbidden while you keep it, and you know every arcane trespass."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Blade Keeps Faith",
                "ds": "Once, when death takes you, it doesn't — the bond pulls you back; you wake, blade in hand, wherever the blade lies."
              }
            ]
          }
        }
      }
    ]
  },
  "Rogue": {
    "id": "Rogue",
    "nm": "Rogue",
    "hd": 8,
    "prime": "DEX",
    "castStat": "INT",
    "desc": "Shadow, cunning, and coin",
    "gear": "short blades x2, leather armor, lockpicks, smoke powder, travel rations (3 days), first aid pack",
    "statPriority": [
      "DEX",
      "INT",
      "CHA",
      "CON",
      "WIS",
      "STR"
    ],
    "abilities": [
      {
        "nm": "Sneak Attack",
        "ds": "Double damage dice when unseen or flanking."
      },
      {
        "nm": "Evasion",
        "ds": "On a failed DEX save, take half damage instead of full."
      },
      {
        "nm": "Lockpick",
        "ds": "Open locks and bypass traps with a DEX check."
      }
    ],
    "skillSeeds": [
      "Stealth",
      "Lockpicking"
    ],
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Cunning Action",
            "ds": "Dash, Disengage, or Hide as bonus action."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Uncanny Dodge",
            "ds": "halve an attack's damage as reaction."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Evasion",
            "ds": "no damage on successful DEX saves, half on fail."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Blindsense",
            "ds": "know location of hidden creatures within 10ft."
          }
        ]
      },
      "11": {
        "features": [
          {
            "nm": "Silent Stalker",
            "ds": "moves without making a sound."
          }
        ]
      },
      "13": {
        "features": [
          {
            "nm": "Hide in Plain Sight",
            "ds": "can fade into a crowd undetected."
          }
        ]
      },
      "15": {
        "features": [
          {
            "nm": "Escape Artist",
            "ds": "cannot be bound by non magical means."
          }
        ]
      },
      "17": {
        "features": [
          {
            "nm": "Summon Item",
            "ds": "Teleports a small item to the hand of the rogue.  Works on any item within 30 feet if the rogue knows it's location.  Does NOT require line of sight."
          }
        ]
      }
    },
    "archetypes": [
      {
        "id": "thief",
        "nm": "Thief",
        "desc": "Use objects and magic items as a bonus action. Fast Hands. Supreme Sneak.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Legerdemain",
                "ds": "Anything within arm's reach you can already have taken — victims discover the loss later, not now."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "No Lock Holds",
                "ds": "Locks, knots, seals, and traps open for you; a lock is a suggestion, not a barrier."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "The Casing Eye",
                "ds": "One look at a room and you know where the valuables are, who holds the keys, and every way out."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "The Shirt Off Your Back",
                "ds": "You can steal what is worn, held, or watched — a sword from a hand, a ring mid-handshake."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Word of the Score",
                "ds": "Rumor of every treasure, vault, and hidden thing finds its way to you wherever you go."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Impossible Theft",
                "ds": "Once, steal a thing no hand should hold — a god's flame, a house's luck, a word from a language."
              }
            ]
          }
        }
      },
      {
        "id": "assassin",
        "nm": "Assassin",
        "desc": "Automatic crit against surprised targets. Perfect disguise. Infiltration Expertise.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "The First Blow Is the Last",
                "ds": "Your first strike against an unsuspecting target is an automatic critical hit; against ordinary folk the fight is over before it begins."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Master Poisoner",
                "ds": "Any food, drink, or weapon can be lethally poisoned in moments, improvised and creative — onset and symptoms are yours to design."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Sure Shot",
                "ds": "Once per combat, declare an impossible ranged shot — ricochet, bank shot, needle-threading, extreme distance — it hits, critically. If you can see it, you can kill it."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "A Natural Death",
                "ds": "Your kills wear whatever face you choose — a fall, a fever, a stopped heart; no one reads murder in them unless you want them to."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Angel of Death",
                "ds": "Once per day, nothing bars your approach to a target within 150 feet — walls gap, wards seam, guards look away. The kill and the leaving are still yours."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Inevitable End",
                "ds": "Once, name a target: their death becomes when, not if — the story bends toward the ending you chose, supplying opportunity but never the kill itself."
              }
            ]
          }
        }
      },
      {
        "id": "arcanetrickster",
        "nm": "Arcane Trickster",
        "desc": "Illusion and enchantment spells. Mage Hand for theft. Distract and confuse.",
        "spellTiers": {
          "1": 3,
          "2": 10,
          "3": 14,
          "4": 18
        },
        "spells": {
          "1": [
            "Charm Person",
            "Silent Image",
            "Disguise Self",
            "Feather Fall",
            "Fog Bank",
            "Leap",
            "Grease",
            "Sleep",
            "Ventriloquism"
          ],
          "2": [
            "Invisibility",
            "Shadow Blade",
            "Knock",
            "Darkness",
            "Shadow Step",
            "Mirror Image",
            "Blur",
            "Spider Climb",
            "Hold Person",
            "Misty Step"
          ],
          "3": [
            "Blink",
            "Lethe's Kiss",
            "Fear",
            "Astral Steed",
            "Telepathy",
            "Shrink",
            "Breathe Water",
            "Slow"
          ],
          "4": [
            "Oubliate",
            "Charm Monster",
            "Wall of Misdirection",
            "Confusion",
            "Archmage Hand",
            "Mass Charm",
            "Implant Memory",
            "Group Telepathy"
          ],
          "cantrips": [
            "Mage Hand",
            "Minor Illusion",
            "Message",
            "Flash"
          ]
        },
        "levels": {
          "3": {
            "features": [
              {
                "nm": "The Old Switcheroo",
                "ds": "Your invisible Mage Hand swaps two objects at 30ft; both holders keep believing they hold what they held."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "It Was Their Idea",
                "ds": "A suggestion you plant is remembered by the target as their own notion, and defended to others as such."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Seventy-Two Shapes",
                "ds": "Take the form of any person or creature you have seen; it holds until you choose to drop it."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Never Caught",
                "ds": "The first time each scene you would be seized or cornered, you simply are not — and they half-remember letting you go."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "The Story Runs Ahead",
                "ds": "A rumour you set loose is true by the time it arrives — it creates circumstance, never undoes what happened."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "Turnabout",
                "ds": "CAPSTONE: once, you and another creature exchange place, bonds, condition and blame — and everyone proceeds as though it had always been so."
              }
            ]
          }
        }
      }
    ]
  },
  "Sorcerer": {
    "id": "Sorcerer",
    "nm": "Sorcerer",
    "hd": 4,
    "prime": "INT",
    "castStat": "INT",
    "desc": "Arcane power, fragile body",
    "gear": "carved staff, spell components, grimoire, travel rations (3 days), first aid kit",
    "statPriority": [
      "INT",
      "DEX",
      "CON",
      "WIS",
      "CHA",
      "STR"
    ],
    "abilities": [
      {
        "nm": "Arcane Bolt",
        "ds": "Ranged magic attack. INT vs AC, d8 damage."
      },
      {
        "nm": "Fire Lance",
        "ds": "d10 damage, ignites flammable targets."
      },
      {
        "nm": "Arcane Shield",
        "ds": "Absorbs 5 damage. Lasts until hit."
      },
      {
        "nm": "Blink",
        "ds": "Teleport 30ft. DC15 DEX or arrive off target."
      }
    ],
    "skillSeeds": [
      "Arcana",
      "Lore"
    ],
    "spellTiers": {
      "2": 5,
      "3": 7,
      "4": 9,
      "5": 11,
      "6": 15
    },
    "spells": {
      "1": [
        "Magic Missile",
        "Shield",
        "Thunderwave",
        "Chromatic Orb",
        "Silent Image",
        "Sleep",
        "Ventriloquism",
        "Hole",
        "Absorb Elements",
        "Grease"
      ],
      "2": [
        "Misty Step",
        "Scorching Ray",
        "Hold Person",
        "Invisibility",
        "Arcane Lock",
        "Darkness",
        "Mirror Image",
        "Phantasmal Force",
        "Silence",
        "Spider Climb"
      ],
      "3": [
        "Fireball",
        "Counterspell",
        "Fly",
        "Diamond Skin",
        "Dispel Magic",
        "Fear",
        "Telepathy",
        "Astral Steed",
        "Breathe Water",
        "Lethe's Kiss",
        "Shrink"
      ],
      "4": [
        "Ice Storm",
        "Wall of Fire",
        "Greater Invisibility",
        "Banishment",
        "Polymorph",
        "Archmage Hand"
      ],
      "5": [
        "Cone of Cold",
        "Telekinesis",
        "Wall of Force",
        "Hold Monster",
        "Shape Shift"
      ],
      "6": [
        "Chain Lightning",
        "Disintegrate",
        "Globe of Invulnerability",
        "Gemstone Warriors"
      ],
      "cantrips": [
        "Fire Bolt",
        "Ray of Frost",
        "Mage Hand",
        "Prestidigitation",
        "Dancing Lights",
        "Flash",
        "Message",
        "Thaumaturgy",
        "Light"
      ]
    },
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Font of Magic",
            "ds": "Your magic is not studied, it is LIVED — a reservoir in the blood that refills as you do. You feel your remaining power the way others feel fatigue, and you can always tell when another caster is nearly spent."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Metamagic",
            "ds": "A spell's shape is yours to bend as you cast it: quicken it into an instant, twin it onto a second target, stretch its reach or duration, or work it with no word or gesture at all — magic indistinguishable from intent."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Sorcerous Restoration",
            "ds": "Power returns to you the way breath does. Minutes of stillness restore what hours of rest give other casters — a sorcerer who catches their wind is a sorcerer rearmed."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Overchannel",
            "ds": "Push a spell past its ceiling: maximum possible effect, no roll. The price is paid in your own body — d6 damage per tier of the spell, and those wounds cannot be healed by any means until you next sleep. The power was never free; it was borrowed."
          }
        ]
      },
      "11": {
        "features": [
          {
            "nm": "Arcane Sight",
            "ds": "You see magic as plainly as light. Every enchantment, ward, curse, and active spell declares itself to your eyes; every illusion is a painting you can see the brushstrokes in; every disguise self announces the face beneath."
          }
        ]
      },
      "13": {
        "features": [
          {
            "nm": "Split Weave",
            "ds": "Your mind holds two workings at once. Concentration is no longer a single thread — you can sustain two spells simultaneously, and losing one does not shake the other."
          }
        ]
      },
      "15": {
        "features": [
          {
            "nm": "Body of Magic",
            "ds": "The flesh is half power now. Magic sustains you where the body fails — you barely need food, sleep, or air; poison and disease find nothing to grip; and you age at a crawl. The frailty remains: what cuts you still cuts."
          }
        ]
      },
      "17": {
        "features": [
          {
            "nm": "Witnessed Once, Worked Once",
            "ds": "Once per day you may work a spell you do not know but have SEEN worked — friend's blessing or enemy's curse, anything cast in your sight is yours to cast back, once, exactly as it was done."
          }
        ]
      }
    },
    "archetypes": [
      {
        "id": "draconic",
        "nm": "Draconic Bloodline",
        "desc": "Dragon ancestry. Bonus HP per level. Elemental affinity. Wings at high level.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Old Blood",
                "ds": "The dragon in your line wakes. Fine scales harden your skin where armor would sit, one element runs in your veins — flame, frost, storm, or venom, chosen once — and dragons and their kin know you on sight for what you carry."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Elemental Vein",
                "ds": "Your element cannot harm you, and it answers small requests without a spell: candle-flames bow, frost blooms across a window, sparks leap to your hand. Your spells of that element hit harder than they have any right to."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Presence of the Wyrm",
                "ds": "The old blood fills a room when you let it. Lesser creatures' nerve breaks under your attention; hardened ones bargain more carefully. It is not charm and it is not fear — it is the older thing both descend from."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Wings",
                "ds": "They were always there, waiting. Wings tear free when called and fold away to nothing — true flight, your own, in any armor, at any hour."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Wyrmform",
                "ds": "Once per day, take the shape of the dragon whose blood you carry — the full creature, for a scene: wings, breath, bulk, and the fear that comes with it. What you do wearing it is remembered."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Progenitor's Due",
                "ds": "CAPSTONE, once per campaign. Speak the true name in your blood and your ancestor ANSWERS — the progenitor dragon itself comes, in the flesh, disposed to treat you as kin. What it does when it arrives is its own will; dragons are not tame. But it came for you, and the world saw it come."
              }
            ]
          }
        }
      },
      {
        "id": "wildmagic",
        "nm": "Wild Magic",
        "desc": "Chaotic unstable power. Random surges. Tides of Chaos for lucky advantage.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Tides of Chaos",
                "ds": "Chaos likes you. When you gamble — a reckless casting, a mad plan, a coin-flip moment — fortune leans your way. In exchange, your magic sometimes answers with an idea of its own: a surge the GM narrates, wondrous or inconvenient, never nothing."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Bend Luck",
                "ds": "Another's fortune is yours to nudge: steal a stumble from an ally's slip, gift one to an enemy's sure step. A visible flicker of wrongness accompanies it — dice land on edge, bowstrings snap, the horseshoe falls."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Controlled Chaos",
                "ds": "The surge is no longer blind. When your magic answers with its own idea, it offers TWO — and you choose which one happens. Chaos has stopped happening to you and started negotiating."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Chaos Feeds You",
                "ds": "Every surge, yours or the world's — wild magic, a miscast, an artifact's tantrum — pours power back into you instead of taking it. Standing in another caster's catastrophe, you are the only one getting stronger."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Unraveling Presence",
                "ds": "Probability frays around you. Locks slip, arrows curve, the one loose stone finds an enemy's foot; around you the improbable becomes merely uncommon, and it is never on the other side. A GM who plans around you plans in ranges."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "Rewrite the Odds",
                "ds": "CAPSTONE, once per campaign. Name one moment of pure chance — a fall, a storm, a draw, a die — and declare its outcome, however impossible. It happens exactly as spoken. Chance owed you one, and everyone watching learns it paid."
              }
            ]
          }
        }
      },
      {
        "id": "shadow",
        "nm": "Shadow Magic",
        "desc": "Power from the Shadowfell. Darkvision. Hound of Ill Omen. Shadow Walk.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Eyes of the Dark",
                "ds": "No darkness is dark to you, mundane or magical — and the dark answers small requests: torches gutter, shadows pool and stretch, a corner is always unlit when you need one. Something on the other side of the dark knows your name now."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Hound of Ill Omen",
                "ds": "Whisper a name into a shadow and a hound of it steps out to harry that creature. It does not tire, it does not lose the trail, and its quarry sleeps badly until the hound is called off or destroyed. One hound at a time."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Shadow Walk",
                "ds": "Every shadow is a door. Step into one and out of any other you have stood in before, however far — the cold between them is crossed in a single held breath. What lives in that cold has learned to let you pass."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "The Shadow Half",
                "ds": "Your shadow can leave you: a second self of dark that walks, watches, and whispers back what it sees. While it is out you cast a shadow that isn't yours, and the observant will notice. If it is destroyed, you feel it — and it comes back only at nightfall."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "The Dark Between",
                "ds": "You can pull others through with you — carry companions along a Shadow Walk, or drag an enemy INTO the cold between and finish the conversation there, in a realm where every advantage is yours. Its native things treat you as one of their lords."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "Sovereign of the Night",
                "ds": "CAPSTONE, once per campaign. From one dusk to the next dawn, the night is YOURS: every shadow a door, every darkness your eyes and ears, every dark thing yours to command. One night to move an army unseen, empty a fortress, or visit every enemy you have at once. Then the sun rises, and the debt is even."
              }
            ]
          }
        }
      }
    ]
  },
  "Ranger": {
    "id": "Ranger",
    "nm": "Ranger",
    "hd": 10,
    "prime": "DEX",
    "castStat": "WIS",
    "desc": "Hunter and tracker",
    "gear": "recurve bow, hunting knife, leather armor, trail kit, travel rations (3 days)",
    "statPriority": [
      "DEX",
      "WIS",
      "CON",
      "STR",
      "INT",
      "CHA"
    ],
    "abilities": [
      {
        "nm": "Hunter's Mark",
        "ds": "Mark a target. +d4 damage and advantage on tracking."
      },
      {
        "nm": "Trackless Step",
        "ds": "Leave no trail in natural terrain."
      },
      {
        "nm": "Volley",
        "ds": "Hit up to 2 targets in range with one action."
      }
    ],
    "skillSeeds": [
      "Tracking",
      "Survival",
      "Stealth"
    ],
    "spellTiers": {
      "2": 7,
      "3": 9,
      "4": 13
    },
    "spells": {
      "1": [
        "Hunter's Mark",
        "Cure Wounds",
        "Ensnaring Strike",
        "Hail of Thorns"
      ],
      "2": [
        "Pass Without Trace",
        "Spike Growth",
        "Silence",
        "Fletch"
      ],
      "3": [
        "Conjure Barrage",
        "Lightning Arrow",
        "Breathe Water",
        "Conjure Animals"
      ],
      "4": [
        "Swift Quiver",
        "Guardian of Nature",
        "Locate Creature",
        "Freedom of Movement"
      ]
    },
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Fighting Style",
            "ds": "Archery, Defense, Dueling, or Two-Weapon."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Extra Attack",
            "ds": "attack twice per action."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Land's Stride",
            "ds": "no difficult terrain penalty."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Hide in Plain Sight",
            "ds": "+10 Stealth camouflage."
          }
        ]
      },
      "11": {
        "features": [
          {
            "nm": "The Long Hunt",
            "ds": "Your Hunter's Mark never fades until you release it: you know the direction and freshness of your quarry's trail anywhere in the region, and it cannot lose you by mundane means."
          }
        ]
      },
      "13": {
        "features": [
          {
            "nm": "The Impossible Shot",
            "ds": "Once per scene, make the shot no one else would attempt — through the arrow slit, the rope at fifty paces, the apple off the moving cart. Declare it; it lands."
          }
        ]
      },
      "15": {
        "features": [
          {
            "nm": "One with the Wild",
            "ds": "In natural terrain you cannot be tracked, ambushed, or outpaced, and beasts will not raise a claw against you unprovoked."
          }
        ]
      },
      "17": {
        "features": [
          {
            "nm": "Apex Predator",
            "ds": "Your marked quarry is already dead and its body just hasn't heard: your attacks against it crit on 18-20, it cannot hide from you, and your allies strike it harder for knowing you're on it (+2 to their attacks)."
          }
        ]
      }
    },
    "archetypes": [
      {
        "id": "hunter",
        "nm": "Hunter",
        "desc": "Colossus Slayer on wounded targets. Giant Killer reaction. Defensive multiattack.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Bigger They Are",
                "ds": "Your first strike each round against a wounded or oversized foe deals +2d6 — the larger the target, the surer your point finds the seam."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Read the Beast",
                "ds": "One look at any creature tells you its strengths, its weaknesses, and how much fight it has left — exact wounds, what it resists, and the move it will make next."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Cull the Herd",
                "ds": "When a foe drops to your attack, your momentum carries into the next: immediately strike another target in reach or range. The chain breaks only when you miss."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Nowhere Soft to Land",
                "ds": "Numbers stop meaning anything: foes gain no advantage from surrounding or flanking you, their opportunity strikes miss, and when three or more engage you, it's you who has the advantage."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Slayer of Legends",
                "ds": "The creatures out of old stories are just bigger quarry: your weapons wound anything however warded, and no aura of terror, majesty, or size makes your hands hesitate."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Last Great Hunt",
                "ds": "Once, name a single creature the object of your Last Great Hunt: no distance, disguise, or plane hides it from your pursuit, and when you finally close, your killing shot cannot be prevented — only survived."
              }
            ]
          }
        }
      },
      {
        "id": "beastmaster",
        "nm": "Beast Master",
        "desc": "Bond with a beast companion that fights alongside you. Primal bond.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Bonded Companion",
                "ds": "A beast of the wild has chosen you: it fights beside you, shares your instincts, and obeys without words. If it dies, no other will choose you for a year and a day — the wild takes bonds seriously."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Shared Senses",
                "ds": "Close your eyes and use your companion's: see, hear, and scent through it at any distance you could walk in a day."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Pack of Two",
                "ds": "You fight as one animal in two bodies: when either of you lands a hit, the other may immediately strike the same target."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Kinship of the Wild",
                "ds": "Any beast will hear you out: once per scene, ask the wild a favor — a hawk to carry word, wolves to harry a column, rats to empty a granary by dawn."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Companion of Legend",
                "ds": "Your companion has grown into something from the old stories — dire-sized, cunning as a person, and known by name in three kingdoms. Enemies plan around it now, not you."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "Two Hearts, One Life",
                "ds": "Death cannot part you: when either of you falls, the other may share its own life to pull them back (split your remaining HP). And once — only once — one of you may take the other's death entirely, no matter its cause."
              }
            ]
          }
        }
      },
      {
        "id": "gloomstalker",
        "nm": "Gloom Stalker",
        "desc": "Invisible in magical darkness. Extra attack on first round. Dread Ambusher.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Terror in the Dark",
                "ds": "Foes you strike from darkness or ambush must check their nerve or panic — a camp you hit at night starts breaking before it forms ranks."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "No Light Needed",
                "ds": "You see perfectly in any darkness, mundane or magical — and darkness likes you back: within 30ft of you torches gutter and lanterns shrink."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "The Unseen Path",
                "ds": "Once per round, step from one shadow into another you can see. The dark is a hallway only you have the key to."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Leave No Witness",
                "ds": "A foe you drop from stealth goes down silently — no cry, no clatter, no alarm — and nothing you do in darkness reveals where you are."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Where Lights Die",
                "ds": "Night itself takes your side: once per day, drown a battlefield (60ft) in a darkness only you and your allies see through, for a whole scene."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Long Night",
                "ds": "You are the thing veterans warn recruits about. Once, declare a night yours: until dawn, within a mile, the darkness answers to you — who sleeps, who wakes, who is found, and who never is."
              }
            ]
          }
        }
      }
    ]
  },
  "Primal": {
    "id": "Primal",
    "nm": "Primal",
    "hd": 12,
    "prime": "STR",
    "desc": "Rage, beast, and storm",
    "gear": "great axe, hide armor, war paint, iron flask, travel rations (3 days)",
    "statPriority": [
      "STR",
      "CON",
      "DEX",
      "WIS",
      "CHA",
      "INT"
    ],
    "abilities": [
      {
        "nm": "Rage",
        "ds": "+2 STR, +2 damage, ignore pain. Lasts 3 rounds."
      },
      {
        "nm": "Reckless Attack",
        "ds": "Advantage on attack, enemy has advantage back."
      },
      {
        "nm": "Intimidating Presence",
        "ds": "CHA check to terrify. Success: enemy shaken (-2 all rolls)."
      }
    ],
    "skillSeeds": [
      "Endure Pain",
      "Intimidation",
      "Survival"
    ],
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Danger Sense",
            "ds": "advantage on DEX saves vs visible effects."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Extra Attack",
            "ds": "attack twice per action."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Feral Instinct",
            "ds": "advantage on initiative. Act normally if surprised while raging."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Brutal Critical",
            "ds": "extra damage die on critical hits."
          }
        ]
      },
      "11": {
        "features": [
          {
            "nm": "Rage Without End",
            "ds": "Your rage lasts as long as the fight does, and dropping to 0 HP doesn't end it — you get one more round of fury on your feet before your body files its complaint."
          }
        ]
      },
      "13": {
        "features": [
          {
            "nm": "Shrug It Off",
            "ds": "While raging, halve all damage that isn't an attack on your mind. Pain is information, and you've stopped reading your mail."
          }
        ]
      },
      "15": {
        "features": [
          {
            "nm": "The Beast Beneath",
            "ds": "Your body answers the wild directly: your unarmed strikes and grapples land like a great beast's, and on all fours you outrun horses."
          }
        ]
      },
      "17": {
        "features": [
          {
            "nm": "More Than Mortal",
            "ds": "Strength and Constitution push past the mortal ceiling (+4 each, caps raised). Doors, chains, and 'impossible' are all suggestions now."
          }
        ]
      }
    },
    "archetypes": [
      {
        "id": "totemborn",
        "nm": "Totemborn",
        "desc": "Spirit animal bond. Bear for resistance, Eagle for mobility, Wolf for pack tactics.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Totem Spirit",
                "ds": "A spirit walks in your skin — choose it: Bear (halve all damage while raging), Eagle (no one you charge escapes, no one you flee catches), or Wolf (every ally fighting beside you strikes harder). The totem can be renegotiated only at a sacred site."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Totem Aspect",
                "ds": "The spirit stays after the rage: Bear hauls like an ox team, Eagle reads a hillside a mile off, Wolf tracks by scent alone at a dead run."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Spirit Walk",
                "ds": "Sleep, and send your spirit out in the totem's shape for an hour — scout the pass, circle the camp, whisper to your kin in their dreams."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Two Totems",
                "ds": "A second spirit accepts you: carry both totems' gifts at once. Shamans argue about whether that's allowed. The spirits don't."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "The Great Spirit's Voice",
                "ds": "Every beast of your totems' kind within the valley answers your call, and the spirits of the wild deal with you as an equal, not a guest."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "Avatar of the Totem",
                "ds": "Once per day, the totem wears YOU: become the spirit made flesh for a scene — a bear the size of a wagon, an eagle that blots the torchlight, a wolf out of the first winter. Your legend and the spirit's are the same story now."
              }
            ]
          }
        }
      },
      {
        "id": "berserker",
        "nm": "Berserker",
        "desc": "Frenzied rage -- bonus attack every turn. Immune to charm and fear while raging.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Blood Price",
                "ds": "Wounds feed the fury: every time you're hurt while raging, your next attack hits +2 harder. They can stop you or they can hurt you — not both."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Terrifying Frenzy",
                "ds": "Your frenzy is a weapon everyone else feels: foes who watch you drop one of their own must check their nerve or give ground."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Furious Leap",
                "ds": "The gap between you and your prey is never safe: leap your full movement onto any foe, arriving as an attack that puts them on the ground."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Rage Undying",
                "ds": "Frenzy no longer ends while enemies stand and costs no exhaustion after — and the first time each day you'd drop mid-frenzy, you stand back up at 1 HP, angrier."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Avalanche of One",
                "ds": "Your charge breaks formations: shield walls scatter, gates crack, cavalry balks. Enemy commanders write their orders around where you might be."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Last Red Day",
                "ds": "Once, declare the Last Red Day: until the battle ends you cannot die, cannot tire, and cannot be stopped by anything smaller than the battle itself. When it ends you sleep for a week — win or lose."
              }
            ]
          }
        }
      },
      {
        "id": "stormcaller",
        "nm": "Stormcaller",
        "desc": "Aura of lightning, thunder, or arctic cold. Living storm of destruction.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Storm Shroud",
                "ds": "Your rage wears weather — choose it: lightning (attackers take 1d8 back), thunder (your blows throw foes off their feet), or frost (everything near you slows). The sky above you agrees with your mood."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Ride the Wind",
                "ds": "The storm carries its own: leap gaps no mortal could, and fall from any height into a thunderclap landing that costs you nothing."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Call the Bolt",
                "ds": "Point at what the sky should hate: once per round, a bolt falls on a foe within 60ft — 3d10 lightning, DEX for half."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Eye of the Storm",
                "ds": "Allies inside your aura stand in the eye: your weather never touches them, and arrows shot into it are slapped aside by the wind."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Season of Wrath",
                "ds": "Your rage bends the weather for miles — fog to hide a retreat, a squall to ground the enemy's archers, a killing frost at midsummer. The land keeps your grudges."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Walking Tempest",
                "ds": "Once per day, stop pretending to be a person: become the storm outright for a scene — a moving column of wind, frost, and lightning that armies cannot hold and arrows cannot find."
              }
            ]
          }
        }
      }
    ]
  },
  "Paladin": {
    "id": "Paladin",
    "nm": "Paladin",
    "hd": 10,
    "prime": "CHA",
    "castStat": "CHA",
    "desc": "Holy warrior, oath-bound",
    "gear": "longsword, shield, chainmail, holy symbol, travel rations (3 days)",
    "statPriority": [
      "CHA",
      "STR",
      "CON",
      "WIS",
      "DEX",
      "INT"
    ],
    "abilities": [
      {
        "nm": "Divine Smite",
        "ds": "Expend a spell slot to deal +2d8 radiant damage on a hit."
      },
      {
        "nm": "Lay on Hands",
        "ds": "Pool of 5xLevel HP. Touch to heal or cure disease/poison."
      },
      {
        "nm": "Divine Sense",
        "ds": "Detect undead, fiends, and celestials within 60ft."
      }
    ],
    "skillSeeds": [
      "Persuasion",
      "Insight"
    ],
    "spellTiers": {
      "2": 7,
      "3": 9,
      "4": 13
    },
    "spells": {
      "1": [
        "Divine Smite",
        "Cure Wounds",
        "Bless",
        "Shield of Faith"
      ],
      "2": [
        "Aid",
        "Magic Weapon",
        "Find Steed"
      ],
      "3": [
        "Revivify",
        "Dispel Magic",
        "Aura of Vitality"
      ],
      "4": [
        "Banishment",
        "Death Ward",
        "Staggering Smite",
        "Aura of Life"
      ]
    },
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Fighting Style",
            "ds": "Defense, Dueling, Great Weapon, or Protection."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Extra Attack",
            "ds": "attack twice per action."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Aura of Protection",
            "ds": "add CHA modifier to saves within 10ft."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Aura of Courage",
            "ds": "allies within 10ft cannot be frightened."
          }
        ]
      },
      "11": {
        "features": [
          {
            "nm": "Oathlight",
            "ds": "Your weapon carries your oath without being asked: every hit deals +1d8 radiant, and creatures of darkness find the light sticky — it clings, and marks them for everyone to see."
          }
        ]
      },
      "13": {
        "features": [
          {
            "nm": "The Unbroken Line",
            "ds": "While you stand, allies within your aura cannot be moved, felled, or made to flee against their will. Lines break where you aren't."
          }
        ]
      },
      "15": {
        "features": [
          {
            "nm": "Judgment's Eye",
            "ds": "Lies rot in your gaze: you always know when you're told a falsehood, and once per scene you may compel one creature to answer a single question truly (CHA negates)."
          }
        ]
      },
      "17": {
        "features": [
          {
            "nm": "Saint's Vessel",
            "ds": "Your body is consecrated ground: hostile magic must overcome your conviction (CHA) to touch you at all, and wherever you sleep counts as hallowed."
          }
        ]
      }
    },
    "archetypes": [
      {
        "id": "vengeance",
        "nm": "Oath of Vengeance",
        "desc": "Hunter of the wicked. Vow of Enmity for advantage. Relentless pursuit. Banishment.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "The Named Enemy",
                "ds": "Speak a wrongdoer's name before witnesses: against them you have advantage on everything — striking, tracking, resisting their arts — until justice is done. One name at a time. Choose carefully; the oath remembers."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "No Rest for the Wicked",
                "ds": "Your named enemy cannot lose you: you sense their direction within a day's ride, and while the hunt is on you need half the sleep and none of the comfort."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Drag Them Back",
                "ds": "The guilty do not get to leave: once per scene, halt a fleeing foe where it stands — teleport, wings, or terror avail it nothing for one full round."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Sentence Passed",
                "ds": "Your smites against the named enemy cannot be resisted, reduced, or forgiven — and each one breaks a hold their power has over someone else."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Wrath That Walks",
                "ds": "Your reputation does half the work now: the corrupt across a region know you are coming, and their servants must check their nerve or abandon them first."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Final Accounting",
                "ds": "Once, declare the Accounting against your named enemy: neither of you can die, flee, or be aided until one yields or falls. Every debt settles inside that circle."
              }
            ]
          }
        }
      },
      {
        "id": "devotion",
        "nm": "Oath of Devotion",
        "desc": "Sacred Weapon -- add CHA to attacks. Holy Nimbus aura. Purity of spirit.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Beacon of Honesty",
                "ds": "Your presence is an oath others lean on: allies who can see you cannot be charmed or made afraid — and your word, once given, is impossible for you to break, and everyone can feel that it is."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Shield the Weak",
                "ds": "Once per round, take a blow meant for anyone within reach — and take it better than they would have: half damage to you."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Consecrated Ground",
                "ds": "Where you plant your feet becomes holy for the scene: undead and fiends must fight their own nature to come within 10ft, and the dying inside it do not slip away."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "The Gentle Hand",
                "ds": "Your healing pool doubles, and Lay on Hands now mends minds as well as bodies — madness, despair, and magical corruption end at your touch."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Light Undimmed",
                "ds": "Your radiance becomes a fact of the region: within your aura all healing is doubled, all darkness is merely shade, and lies stumble on their way out of the mouth."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "Call the Dawn",
                "ds": "Once, when all is lost, call the dawn early: every ally standing with you is healed whole, freed of fear and curse, and cannot fall below 1 HP until the fight ends. The bards will get it wrong. It was better than they say."
              }
            ]
          }
        }
      },
      {
        "id": "ancients",
        "nm": "Oath of Ancients",
        "desc": "Nature's warrior. Aura of Warding vs spells. Undying Sentinel at 0 HP.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "The Green Vow",
                "ds": "You swore to the life older than the gods: wild places accept you as kin, your smites bloom with thorned light, and once per scene the vines answer you — grasping, tripping, holding fast."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Sap and Stone",
                "ds": "Poison, rot, and wither slide off you and those at your side, and your body keeps the forest's calendar — you age a year for its ten."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Roots of the World",
                "ds": "Tree, stone, and stream confide in you — what passed, when, and bleeding or not. Once per day the land opens a path: brush parts, fords surface, cliffs offer stairs."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Undying Green",
                "ds": "The first time each day you would fall, you don't: life floods back at half strength, and green shoots rise in your footprints. The old life does not let go of its sworn."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Season's Champion",
                "ds": "The wild rises where you fight: for a scene the terrain takes your side — thorn hedges, sudden bogs, groves that hide your friends and swallow your enemies."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Old Light",
                "ds": "Once, kindle the Old Light — the sun the first forests grew under: within a mile, corruption burns out of land and folk alike, the wild's dead rise as allies for one battle, and what you plant that day cannot be killed by anything younger than the world."
              }
            ]
          }
        }
      }
    ]
  },
  "Cleric": {
    "id": "Cleric",
    "nm": "Cleric",
    "hd": 8,
    "prime": "WIS",
    "castStat": "WIS",
    "desc": "Divine power, battle priest",
    "gear": "mace, scale armor, shield, holy symbol, prayer beads, travel rations (3 days)",
    "statPriority": [
      "WIS",
      "CON",
      "STR",
      "CHA",
      "DEX",
      "INT"
    ],
    "abilities": [
      {
        "nm": "Sacred Flame",
        "ds": "Radiant damage cantrip. DEX save or take d8 radiant."
      },
      {
        "nm": "Turn Undead",
        "ds": "Undead within 30ft must flee. DC = 8+WIS+proficiency."
      },
      {
        "nm": "Healing Word",
        "ds": "Bonus action. Heal target for d4+WIS modifier HP."
      }
    ],
    "skillSeeds": [
      "Lore",
      "First Aid"
    ],
    "spellTiers": {
      "2": 5,
      "3": 7,
      "4": 9,
      "5": 11,
      "6": 15
    },
    "spells": {
      "1": [
        "Healing Word",
        "Bless",
        "Guiding Bolt",
        "Shield of Faith",
        "Command",
        "Sanctuary",
        "Detect Magic"
      ],
      "2": [
        "Spiritual Weapon",
        "Hold Person",
        "Lesser Restoration",
        "Augury",
        "Zone of Truth"
      ],
      "3": [
        "Spirit Guardians",
        "Revivify",
        "Dispel Magic"
      ],
      "4": [
        "Divination",
        "Death Ward",
        "Guardian of Faith",
        "Freedom of Movement"
      ],
      "5": [
        "Flame Strike",
        "Mass Cure Wounds",
        "Greater Restoration",
        "Resurrection"
      ],
      "6": [
        "Heal",
        "Blade Barrier",
        "Heroes' Feast"
      ],
      "cantrips": [
        "Sacred Flame",
        "Guidance",
        "Spare the Dying",
        "Thaumaturgy",
        "Succor"
      ]
    },
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Minor Miracle",
            "ds": "Once per rest you spend your god's authority out loud, and it answers in its own idiom — light in a dark place, a binding broken, a frightened crowd's courage handed back. The god answers the priest, not the request: what arrives is what your deity would give, not what you asked for."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Destroy Undead",
            "ds": "Undead of lesser standing than you no longer flee when you turn them — they come apart where they stand. Anything older or greater than you still runs, and remembers who made it run."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Divine Strike",
            "ds": "Your god blesses your weapon: once per turn a hit carries an extra d8 of your deity's own kind — light, flame, frost, rot — and the wound is unmistakably divine to anyone who looks at the body."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Divine Intervention",
            "ds": "You may pray aloud for your god to act directly. Roll d100; under your level it does — plainly, publicly, and in its own way. Answered or not, it will not be asked again for seven days."
          }
        ]
      },
      "11": {
        "features": [
          {
            "nm": "Consecrated Ground",
            "ds": "A night's rite makes a place yours: nothing unholy crosses the threshold uninvited, and anyone who sleeps inside wakes as though they had rested a week. You hold one consecrated place at a time — raising a new one lets the old go quiet."
          }
        ]
      },
      "13": {
        "features": [
          {
            "nm": "The Blessing Holds",
            "ds": "Your boons outlast the danger that prompted them. Any blessing you lay on a companion runs until your next rest instead of fading with the fight — a party that travels with you travels blessed."
          }
        ]
      },
      "15": {
        "features": [
          {
            "nm": "Death Waits",
            "ds": "Once per rest, when you or anyone you can see drops, death is told to wait: they stand at 1 hit point instead of falling. The same creature cannot be spared twice in one day — the second time, the god is not listening."
          }
        ]
      },
      "17": {
        "features": [
          {
            "nm": "Smite",
            "ds": "Once per day, name a creature you can see and your god strikes it directly: a single blow equal to 95% of the hit points it has left, delivered in your deity's own idiom — a thunderclap from a storm god, ghostly kraken tentacles from a god of the deep; the GM chooses the manifestation. It is never a killing blow: whatever it hits is left at death's door, and what happens next is up to you."
          }
        ]
      }
    },
    "archetypes": [
      {
        "id": "life",
        "nm": "Life Domain",
        "desc": "Master healer. Disciple of Life -- healing spells restore bonus HP. Preserve Life.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Disciple of Life",
                "ds": "Every healing you work gives back more than it should, and your hands read a body at a touch: what broke it, how long it has, and whether the trouble is wound, poison, sickness, or grief."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Cleanse",
                "ds": "Disease, poison, rot, and afflictions of the body lift where you keep vigil: one night's work cures any single creature, and a plague ends in whatever village you stay in. It mends the body — what corrupts a soul is not your department."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Preserve Life",
                "ds": "Once per rest you can catch someone in the first moments after death — a creature dead less than a minute stands again at 1 hit point, whole enough to walk. What they saw while they were gone is between them and your god."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Restore Limb",
                "ds": "A night of prayer over the wounded regrows what was lost: an arm, a leg, an eye, a hand — anything short of a head. The new flesh is whole, strong, and unmistakably a gift; it carries no scar, and everyone who knew the old wound knows exactly who to thank."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Battlefield Miracle",
                "ds": "Once per day you may declare it, and for one scene no ally within your sight dies. They fall, they bleed, they are dragged from the field — and every one of them wakes up. Your enemies enjoy no such protection."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Return",
                "ds": "CAPSTONE, once per campaign. You can ask for one person back and be answered. Whatever remains of them — a body, a scrap, a name — they return whole and themselves, however they died and however long ago."
              }
            ]
          }
        }
      },
      {
        "id": "war",
        "nm": "War Domain",
        "desc": "God of battle. War Priest bonus attack. Guided Strike -- +10 to a missed attack.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "War Priest",
                "ds": "Prayer and blow are one motion. You never have to choose between casting and fighting on a turn, and armor, shield, and weapon never hinder your magic — a spell of yours has been swung as often as spoken."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Guided Strike",
                "ds": "Once per fight a miss becomes a hit — yours, or any companion's you can see. Your god corrects the swing visibly, and everyone on the field knows whose hand did it."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "The Line Holds",
                "ds": "Nobody breaks where you stand. Allies who can see or hear you cannot be routed, frightened, or panicked, and the wounded among them keep their feet as long as you keep yours."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Consecrated Arms",
                "ds": "Every weapon your party carries counts as blessed while you are in the fight — the ghost, the fiend, the thing that ordinary steel passes straight through takes the blow like anything else. Yours in particular has no bad angles."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "The God of Battle Attends",
                "ds": "Once a day you may call your deity onto the field, and it comes visibly — a wave of standing light, a shadow in armor twelve feet tall — and fights beside you for that encounter, as capable as you are. Everyone present sees it. Word of it travels ahead of you."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "Decide the Battle",
                "ds": "CAPSTONE, once per campaign. In a battle you are fighting in, name the victor and the field goes that way: reinforcements arrive, the flank folds, the champion's horse throws them. The outcome is yours. The cost in the dead is not, and you will be counting it afterwards."
              }
            ]
          }
        }
      },
      {
        "id": "subjugation",
        "nm": "Subjugation Domain",
        "desc": "Divine authority made compulsion. The Knee -- your voice carries your god's weight. Yoke the defeated into open, unwilling service.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "The Oath",
                "ds": "A promise spoken to you binds. The oath-breaker knows the instant they break it, and so do you, wherever you are — and misfortune of your god's choosing dogs them until amends are made. Only words offered willingly can bind; a forced vow is just noise."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "The Yoke",
                "ds": "A defeated or helpless creature can be bound into your service: awake, aware, resentful, and obedient. You give orders and it carries them out hating every step — you see nothing through its eyes and speak nothing through its mouth; it serves, it is not worn. One yoked servant at a time; release it, or die, and it is free."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "The Knee",
                "ds": "The weight of your god hangs on your voice. Small commands spoken directly — kneel, drop it, wait, speak — land unless the target has real cause to resist, and even then defiance is visible effort. You never puppet a body; you press a will, and its owner is awake for every moment of it."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "The Missive",
                "ds": "Your compulsion no longer needs your presence. A command under your seal, or carried by a messenger in your name, binds as though you spoke it eye to eye — distance was the defense, and there is no defense. One such standing command may be abroad at a time."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "The Word",
                "ds": "Once per day you may speak one short command in your god's own voice, and every creature that hears it obeys for one action. Nothing immediately self-destructive can be commanded, and named foes get a WIS save; the rest simply do it, and remember afterwards that they did."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The Law",
                "ds": "CAPSTONE, once per campaign. Speak one decree over a place — a city, a valley, a kingdom's road — and it becomes law in the oldest sense: the land itself enforces it. No blood spilled in this valley. No lie spoken in this city. It holds until a god's own authority overturns it, and your name is on it forever."
              }
            ]
          }
        }
      }
    ]
  },
  "Druid": {
    "id": "Druid",
    "nm": "Druid",
    "hd": 8,
    "prime": "WIS",
    "castStat": "WIS",
    "desc": "Nature magic, wild shape",
    "gear": "wooden staff, leather armor, herbalism kit, totem fetish, travel rations (3 days)",
    "statPriority": [
      "WIS",
      "CON",
      "DEX",
      "INT",
      "CHA",
      "STR"
    ],
    "abilities": [
      {
        "nm": "Wild Shape",
        "ds": "Transform into a beast. CR limit scales with level."
      },
      {
        "nm": "Druidic",
        "ds": "Secret language of druids. Leave hidden messages in nature."
      },
      {
        "nm": "Speak with Animals",
        "ds": "Communicate with beasts. They share what they have sensed."
      }
    ],
    "skillSeeds": [
      "Nature",
      "Animal Handling",
      "Foraging"
    ],
    "spellTiers": {
      "2": 5,
      "3": 7,
      "4": 9,
      "5": 11,
      "6": 15
    },
    "spells": {
      "1": [
        "Entangle",
        "Healing Word",
        "Thunderwave",
        "Faerie Fire"
      ],
      "2": [
        "Moonbeam",
        "Barkskin",
        "Pass Without Trace"
      ],
      "3": [
        "Call Lightning",
        "Conjure Animals",
        "Plant Growth"
      ],
      "4": [
        "Blight",
        "Dominate Beast",
        "Control Water",
        "Giant Insect"
      ],
      "5": [
        "Insect Plague",
        "Tree Stride",
        "Wall of Stone",
        "Awaken"
      ],
      "6": [
        "Sunbeam",
        "Wall of Thorns",
        "Wind Walk"
      ],
      "cantrips": [
        "Produce Flame",
        "Shillelagh",
        "Druidcraft",
        "Thorn Whip"
      ]
    },
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Wild Shape (CR 1/4)",
            "ds": "transform into a beast you have seen."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Wild Shape (CR 1)",
            "ds": "more powerful beast forms available."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Timeless Body",
            "ds": "age at 1/10 normal rate."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Beast Spells",
            "ds": "cast druid spells while in Wild Shape."
          }
        ]
      },
      "11": {
        "features": [
          {
            "nm": "Second Skin",
            "ds": "Wild Shape is a breath, not a ritual: shift as part of any action, gear melding or staying as you choose, and your beast ceiling keeps climbing with your level."
          }
        ]
      },
      "13": {
        "features": [
          {
            "nm": "Voice of the Land",
            "ds": "The land within a mile confides in you: ask it what walks, what sickens, what hides. Its answer is always true and always partial — the land has its own sense of humor."
          }
        ]
      },
      "15": {
        "features": [
          {
            "nm": "Root and Branch",
            "ds": "The green fights for you unasked: difficult terrain never slows you, and once per scene the undergrowth itself restrains everything you name within 30ft."
          }
        ]
      },
      "17": {
        "features": [
          {
            "nm": "Shape of the World",
            "ds": "Your Wild Shape reaches past flesh: elemental bodies — living flame, stone, water, wind — once per day each. The beasts were practice."
          }
        ]
      }
    },
    "archetypes": [
      {
        "id": "land",
        "nm": "Circle of the Land",
        "desc": "Ancient magic of terrain. Bonus spells by terrain type. Natural Recovery of spell slots.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Homeground",
                "ds": "Choose your land — forest, desert, mountain, swamp, or coast. On it you are unmistakable: regain one spent cast per scene, and its creatures treat you as an elder of their own."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "The Land Provides",
                "ds": "Your land feeds, hides, and heals your own: foraging always succeeds, camps are never found unless you wish it, and natural rest heals double."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Read the Ley",
                "ds": "You see the lines of power under any terrain — sacred sites, poisoned ground, buried things. Once per day, borrow a ley line: one spell cast at full strength, free."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "All Ground Is Homeground",
                "ds": "Every natural terrain now counts as your land, and hostile magic that would blight soil, water, or growing things simply fails within your sight."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "The Land Remembers",
                "ds": "Wake the memory of a place for a scene: the drowned village rises walkable, the razed forest stands ghost-green, and what happened there plays out for every eye you choose."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "Keeper of the Green",
                "ds": "One region — a forest, a valley, a coastline — takes you as its keeper: it prospers or withers on your word, warns you of every intrusion, and no power younger than the hills can claim it while you live."
              }
            ]
          }
        }
      },
      {
        "id": "moon",
        "nm": "Circle of the Moon",
        "desc": "Powerful Wild Shape. Combat beast forms. Elemental forms at high level.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "War Shape",
                "ds": "Your Wild Shape is built for the front line: combat forms beyond your years, shifting instant, and the beast's hide takes the first wounds meant for you (temporary HP on every shift)."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Fang and Focus",
                "ds": "Your claws and fangs bite through wards meant for steel (they count as magical), and the beast's throat can still carry your casting — roar the spell."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Shapes of the Ice Years",
                "ds": "The moon shows you older beasts: forms long extinct — cave bears the size of carts, wolves from the first winters. Your shapes now frighten as they fight."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "The Half-Form",
                "ds": "Take the middle shape: your hands and voice with the beast's strength and senses — cast, speak, climb, and rend in the same body."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Tide of Shapes",
                "ds": "Shift without count or cost, flowing form to form mid-motion — bird to bear mid-pounce. Your enemies fight a different animal every round and never the one they planned for."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "The First Beast",
                "ds": "Once per day, wear the First Beast — the shape all animals remember in their bones. For a scene, everything wild within a mile answers its cry as kin, and nothing mortal that sees it ever quite settles on what it was."
              }
            ]
          }
        }
      },
      {
        "id": "spores",
        "nm": "Circle of Spores",
        "desc": "Halo of Spores necrotic damage. Symbiotic Entity -- enhanced Wild Shape for combat.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "The Quiet Bloom",
                "ds": "Your spores ride every breath within 10ft: foes you choose take 1d6 necrotic each round they linger, and you feel every living and dead thing your cloud touches."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Rot into Life",
                "ds": "Death feeds the circle: when a creature dies inside your bloom, choose — take its vigor as your own (temporary HP), or let its corpse serve until scene's end as a spore-walker."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Gardener of Corpses",
                "ds": "Your spore-walkers persist and multiply — up to three at once — and each bursts when destroyed (2d8 necrotic cloud). Waste nothing; the circle doesn't."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Flesh Is a Season",
                "ds": "Decay keeps your calendar now: rot stone, wood, and iron with a touch, hold a corpse or harvest fresh indefinitely — and your own green-riddled body no longer bleeds, sickens, or takes poison."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "The Patient Kingdom",
                "ds": "Everything fungal within a mile is your eyes and hands: word crosses the forest floor in minutes, and ground you claim becomes a slow trap — spoiled stores, sapped strength, dread with no visible source."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "All Things Return",
                "ds": "Once — only once — when anything dies within your bloom, friend, foe, or you, refuse the death: it is composted, and the creature stands back up whole. The circle takes a year of your life as tithe, and a ring of pale mushrooms marks the spot forever."
              }
            ]
          }
        }
      }
    ]
  },
  "Necromancer": {
    "id": "Necromancer",
    "nm": "Necromancer",
    "hd": 6,
    "prime": "INT",
    "castStat": "INT",
    "desc": "Death magic, bone and shadow",
    "gear": "skull focus, dark robes, grimoire of the dead, grave dust pouch, travel rations (3 days)",
    "statPriority": [
      "INT",
      "CON",
      "DEX",
      "WIS",
      "CHA",
      "STR"
    ],
    "abilities": [
      {
        "nm": "Raise Thrall",
        "ds": "Animate a fresh corpse within 10ft as a zombie thrall. Requires a body present. The thrall follows basic commands and collapses if you fall unconscious. One thrall at a time until your archetype expands this."
      },
      {
        "nm": "Drain Life",
        "ds": "Melee or 30ft necrotic attack. Deal d6 necrotic damage; regain HP equal to half the damage dealt."
      },
      {
        "nm": "Death Sight",
        "ds": "Sense undead, corpses, and death-taint within 60ft without seeing them. Advantage on Arcana and Lore checks involving undead, curses, or death magic."
      }
    ],
    "skillSeeds": [
      "Arcana",
      "First Aid"
    ],
    "spellTiers": {
      "2": 5,
      "3": 7,
      "4": 9,
      "5": 11,
      "6": 15
    },
    "spells": {
      "1": [
        "Inflict Wounds",
        "Ray of Sickness",
        "False Life",
        "Cause Fear",
        "Bleed",
        "Eldritch Tendrils",
        "Hide from Undead",
        "Miasma",
        "Wither"
      ],
      "2": [
        "Ray of Enfeeblement",
        "Blindness",
        "Shadow Step",
        "Shackles of Bone",
        "Rot",
        "Blood Armour",
        "Conscript Undead",
        "Hemorrhage",
        "Hold Undead",
        "Siphon Life",
        "Visitation"
      ],
      "3": [
        "Vampiric Touch",
        "Speak with Dead",
        "Wave of Scarabs",
        "Bestow Curse",
        "Death Walk",
        "Age",
        "Blade of Corruption",
        "Creeping Death",
        "Devil's Trap",
        "Dire Cremation",
        "Grim Totem",
        "Haunting",
        "Rigor Mortis",
        "Whirl of Bones"
      ],
      "4": [
        "Possess Thrall",
        "Sleep of the Dead",
        "Archmage Hand",
        "Aspect of the Undead",
        "Blight",
        "Eject Soul",
        "Exploding Corpse",
        "Flesh Golem",
        "Three Sisters",
        "Travelling Wounds",
        "Vampiric Courtesan",
        "Blood to Blood"
      ],
      "5": [
        "Catastrophic Wound",
        "Charybdis",
        "Resurrection",
        "Soul Cage",
        "Combine Undead"
      ],
      "6": [
        "Aspect of the Reaper",
        "Horrid Wilting",
        "Necrotic Nova",
        "Vampiric Assault"
      ],
      "cantrips": [
        "Chill Touch",
        "Toll the Dead",
        "Bone Whisper",
        "Grave Touch",
        "Mage Hand",
        "Ray of Frost"
      ]
    },
    "levels": {
      "2": {
        "features": [
          {
            "nm": "Undead Thrall",
            "ds": "your Raise Thrall servant persists permanently until destroyed. Gains bonus HP equal to your INT modifier. Can follow simple multi-step orders, Go to X and perform task Y."
          }
        ]
      },
      "5": {
        "features": [
          {
            "nm": "Grim Harvest",
            "ds": "when you kill a creature with a spell, regain HP equal to twice the spell's level (minimum 2). Once per turn."
          }
        ]
      },
      "7": {
        "features": [
          {
            "nm": "Conscript Undead",
            "ds": "Seize control of any undead creature you can see. INT save for success  (DC 8 + INT modifier + proficiency). Success: under your control for 24 hours. A maximum of level/3 undead may be controled at once."
          }
        ]
      },
      "9": {
        "features": [
          {
            "nm": "Necrotic Resilience",
            "ds": "resistance to necrotic damage, advantage on death saving throws. Undead you control cannot be Turned by Clerics or Paladins."
          }
        ]
      },
      "11": {
        "features": [
          {
            "nm": "Dark Immunity",
            "ds": "Immune to all forms of decay, disease, and death or blood magic."
          }
        ]
      },
      "13": {
        "features": [
          {
            "nm": "Dire Phylactery",
            "ds": "Requires a focus object.  While focused on a target, any loss of hitpoints experienced by the target is stored as mana in the focus object at a rate of 5hp to 1mp.  The mana in the focus object can then be drawn into the necromancer as a mana supply. "
          }
        ]
      },
      "15": {
        "features": [
          {
            "nm": "Vampiric Charm",
            "ds": "the promise of death's defeat is intoxicating, the target must make a savings throw or become the necromancer's thrall.  A new savings throw may be rolled every dawn."
          }
        ]
      },
      "17": {
        "features": [
          {
            "nm": "Path of the Lich",
            "ds": "the path to becoming a lich is open to you.  It is one time only and irreversible."
          }
        ]
      }
    },
    "archetypes": [
      {
        "id": "bonesculptor",
        "nm": "Bone Sculptor",
        "desc": "Raise up to 3 thralls simultaneously from available corpses with one casting. Thralls gain +2 AC from bone reinforcement. Can animate dead from a distance of 30ft. The path to undeath begins here.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Bone Shards",
                "ds": "Casts shards of bone at the target doing 1d4 per caster level, range of 80 feet."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Bone Armor",
                "ds": "Caster becomes clad in hardened, articulated bone platemail.  "
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Bone Structure",
                "ds": "Caster can create structures of bone which emerge from the ground.  Fails on concecrated earth."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Bone Golem",
                "ds": "Creates a golem made of bone. "
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Army of Bone",
                "ds": "Summons waves of skeletons to crash against enemy forces, 25 skeletons at a time.  As skeletons fall new ones rise and join the fight.  Continues until the caster breaks concentration. "
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "Bone Dragon",
                "ds": "Summons a bone dragon."
              }
            ]
          }
        }
      },
      {
        "id": "entropist",
        "nm": "Entropist",
        "desc": "Entropy is your weapon: your touch corrodes one nonmagical object per round -- blades pit, ropes fray, doors give way, stone remembers it was sand. Constructs and objects take double damage from your spells.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Accelerated Decay",
                "ds": "By intention: your touch rots living flesh: 2d8 necrotic and the target ages 1d10 years (CON save halves the damage and refuses the years). What you rot stays rotted -- wounds you deal cannot be magically healed until the next dawn."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Rust in the Air",
                "ds": "your decay no longer needs touch -- corrode objects at 30ft. Once per round when a nonmagical weapon or projectile strikes you, it decays mid-blow: damage halved, the weapon ruined."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Field of Entropy",
                "ds": "a 30ft radius where everything ends faster: structures sag and crack, potions spoil, food blackens, healing is halved, and objects age a year every round. Concentration, up to 1 minute."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Unraveling",
                "ds": "decay reaches the immaterial: end one active spell or enchantment you can see, or silence a magic item until dawn -- its virtue rusts like everything else."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Ruin",
                "ds": "a minute of ritual collapses years into moments on one structure: a fortress gate becomes a breach, a bridge becomes a memory, a siege engine becomes mulch. Consecrated ground resists."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "Entropy Incarnate",
                "ds": "for one scene you are the ending of things: nonliving matter you touch turns to dust outright, hostile magic gutters out within 30ft of you, and living creatures who stand against you age a year and take 4d10 necrotic each round (CON for half). Once per day."
              }
            ]
          }
        }
      },
      {
        "id": "soulbinder",
        "nm": "Soul Binder",
        "desc": "Trap a dying creature's soul in a prepared vessel (bone, gem, or bottle). One soul per casting, unlimited vessels. Bound souls answer questions truthfully or can be shattered for a 15ft burst of 3d8 necrotic damage.",
        "levels": {
          "3": {
            "features": [
              {
                "nm": "Soulfire",
                "ds": "a bound soul is fuel: consume one to regain mana equal to the soul's level, or to cast your next spell as if one tier higher. The soul is spent forever -- it does not pass on, it burns."
              }
            ]
          },
          "6": {
            "features": [
              {
                "nm": "Greater Vessels",
                "ds": "Once per day: you bind at 30ft the instant death occurs, and your vessels hold souls indefinitely. An unwilling dying soul may resist (CHA save)."
              }
            ]
          },
          "10": {
            "features": [
              {
                "nm": "Soul Puppet",
                "ds": "pour a bound soul into a fresh corpse: the dead walks again with its own memories and skills intact -- a thinking servant, not a shambler. It knows exactly what it owes you."
              }
            ]
          },
          "14": {
            "features": [
              {
                "nm": "Anchored Soul",
                "ds": "your own soul rides in a prepared vessel: the first time you die, you wake beside it a day later and the vessel shatters. Crafting a new anchor takes a month. This is the apprenticeship for what waits at level 17."
              }
            ]
          },
          "18": {
            "features": [
              {
                "nm": "Reap the Field",
                "ds": "any creature that dies within 60ft offers you its soul -- no action, no vessel prepared, you ARE the vessel. Battles fill your satchel; armies feed you."
              }
            ]
          },
          "20": {
            "features": [
              {
                "nm": "Judge of the Dead",
                "ds": "no soul passes within a mile without your leave: the dying linger until you rule, and the dead cannot be raised against you. Once -- only once -- you may spend every soul you hold to call one person truly back to life."
              }
            ]
          }
        }
      }
    ]
  }
};
// <<< CLASS BIBLE DATA
