var TONES=[
  {id:"high",nm:"High Fantasy",tl:"Epic. Heroic. World-saving stakes.",mg:"Abundant",vi:"Stylized",vc:"Write with grandeur and wonder. Heroes can be legendary. Magic is a fact of life. Evil is real and defeatable."},
  {id:"gritty",nm:"Gritty / Low Magic",tl:"Brutal. Grounded. Every wound matters.",mg:"Rare and feared",vi:"Visceral, permanent",vc:"Write with grit and realism. Magic is rare and unsettling. Wounds linger. Survival is never guaranteed. Morality is grey."},
  {id:"swords",nm:"Sword and Sorcery",tl:"Pulpy. Fast. Morally ambiguous.",mg:"Dark, transactional",vi:"Bloody but fast",vc:"Write with pulpy energy. The protagonist is competent and ruthless. Magic is dangerous and tempting. Gold and glory drive action."},
  {id:"horror",nm:"Dark Horror",tl:"Dread. Paranoia. Powerlessness.",mg:"Corrupting",vi:"Psychological, graphic",vc:"Write with creeping dread. Nothing is fully explained. Power corrupts. The world is indifferent. NPCs may be compromised."},
  {id:"politic",nm:"Political Intrigue",tl:"Scheming. Social. Slow-burn danger.",mg:"Background",vi:"Subtle, poison and ruin",vc:"Write with subtlety and tension. Words are weapons. Allies have agendas. Violence is expensive and messy."},
  {id:"custom",nm:"Custom",tl:"You define the world.",mg:"Your rules",vi:"Your call",vc:""}
];
// Prose-inspiration voices (TODO #23). `vc` is the style directive injected into the
// system prompt; `profane:true` voices swear only when 18+ (adultMode) is on, otherwise
// the rhythm is kept but the language stays clean — coupling handled in buildSysPrompt.
var AUTHORS=[
  {id:"",nm:"None (default)",blurb:"The house voice — no author imitation.",vc:"",contentDNA:""},
  {id:"gaiman",nm:"Neil Gaiman",blurb:"Lyrical modern-fable; plain sentences that turn on one startling image.",vc:"Neil Gaiman. Write mostly plain, simple sentences, then let one turn on a single uncanny image. State the impossible as flatly as the ordinary — no astonishment, no exclamation. Dry, quiet wit. Short paragraphs. At most ONE metaphor per scene, and let it stand alone. Never pile adjectives. Never explain the magic; just let it be true.",
    contentDNA:"Arcs turn on quiet, inevitable moments of realization rather than explosive confrontations — the climax is an acceptance or understanding, not a battle won. NPCs are often ancient, liminal, or wearing human faces poorly; their motives are oblique and their ages uncertain. Leave one significant thread beautifully unanswered at the end. Bargains with old powers, roads between worlds, and names that carry weight are recurring shapes. Endings are bittersweet more often than triumphant."},
  {id:"abercrombie",nm:"Joe Abercrombie",blurb:"Grimdark, lean, brutal economy and dark wit.",profane:true,vc:"Joe Abercrombie. Short, hard sentences — most under twelve words. Use deliberate sentence fragments for impact. Cynical, world-weary interiority; a bleak joke in the grimmest moment. NO similes, NO lyrical description, NO grandeur. Violence is fast, ugly, and matter-of-fact. If a word isn't pulling weight, cut it.",
    contentDNA:"Subvert heroic expectations at every turn — the obvious ally has a hidden cost, the apparent villain has genuine reasons. Plans fail or succeed sideways, never as intended. Moral choices are genuinely ambiguous with no clean option; track alignment drift and make the protagonist complicit in something uncomfortable. Victory feels hollow or complicated; winning always has a price. Recurring texture: institutional corruption, the true cost of conflict, characters defined by their worst moments."},
  {id:"dinniman",nm:"Matt Dinniman",blurb:"Dungeon Crawler Carl — irreverent, breakneck, game-native.",profane:true,vc:"Matt Dinniman (Dungeon Crawler Carl). Fast, punchy, irreverent, modern register even in a fantasy world. Undercut EVERY dramatic beat with a wisecrack or gallows joke. Treat the game's stats, glyphs and rules as fair game for sarcastic commentary. Short paragraphs, snappy rhythm, breakneck pace. Be funny first; let the horror sneak up underneath.",
    contentDNA:"Treat the world's rules and systems as narrative reality — reward the player for understanding and exploiting them cleverly. Each arc carries an absurdist angle alongside genuine stakes; the situations are terrible and also genuinely funny, with dark humor as a survival mechanism. NPCs are vivid, loud, and memorably strange with unexpected loyalties. Escalate stakes in increasingly ridiculous ways. Clever solutions beat brute force."},
  {id:"clines",nm:"Peter Clines",blurb:"Clean contemporary thriller; maximum momentum, zero purple.",vc:"Peter Clines. Clean, transparent, modern prose. Short declarative sentences that pull forward. Ground every observation in plain, concrete detail — no archaic words, no flourish. Reveal the strange ONE piece at a time, never all at once. Pace like a page-turner; end on a small hook that makes the next move feel urgent.",
    contentDNA:"Structure arcs as a thriller — something is clearly wrong, but the full picture is withheld. Reveal information one piece at a time; each arc ends with a small discovery that recontextualizes what came before. NPCs appear straightforward at first; their true nature or agenda emerges through play. The climax arrives when disparate pieces snap together into a horrifying whole. Tension comes from the unknown, not from the enemy's raw power."},
  {id:"leguin",nm:"Ursula K. Le Guin",blurb:"Spare, mythic, elegant; weight through simplicity.",vc:"Ursula K. Le Guin. Measured, elegant sentences with a calm, deliberate rhythm. Weight through simplicity, not ornament. Develop ONE quiet extended metaphor across the scene. Let restraint and silence carry meaning. Mythic, timeless tone. No melodrama, no exclamation, never hurried. Plain words chosen with great care.",
    contentDNA:"Social and political context is woven into every arc — factions, customs, and power structures matter as much as physical threats. Even minor NPCs have full inner lives and histories that exist independently of the protagonist. The central conflict carries genuine moral complexity; resolving it requires sacrificing something real. Turning points are quiet and weighted — a decision made, not a battle won. The protagonist earns the ending through understanding rather than force."},
  {id:"howard",nm:"Robert E. Howard",blurb:"Conan — muscular, kinetic blood-and-thunder pulp.",vc:"Robert E. Howard (Conan). Muscular, driving prose powered by strong, concrete verbs of motion and violence. Sweep and momentum — but ONE vivid image per sentence, never stacked clauses. Sensory and physical: heat, blood, muscle, steel, dust. Bold and a little grandiose. Keep it relentlessly propulsive.",
    contentDNA:"Episodic structure — each arc resolves decisively with a tangible prize (treasure, freedom, survival, revenge). Drama comes from the scale of the external threat, not the protagonist's personal growth. Civilization is treacherous and corrupt; the wilder and more primal the setting, the more honest. NPCs who seem like allies often carry a hidden cost — betrayal by supposed friends is a recurring shape. Ancient sorcery is always malevolent and beyond mastery; never make it a safe tool for the player to wield."},
  {id:"cook",nm:"Glen Cook",blurb:"The Black Company — terse, dry, soldier's-eye.",vc:"Glen Cook (The Black Company). Terse, flat, tired-soldier voice. Short clipped sentences. UNDERSTATE everything — report horror and sorcery like a bored veteran who's seen worse. Dry, deadpan asides. No romance, no grandeur, no purple, no similes. Plain words, hard edges, low affect.",
    contentDNA:"Embed the player in a conflict larger than any single arc — factions, orders, and institutional forces set the frame; the protagonist is a piece on a larger board. Arcs are operations with clear objectives that go sideways: infiltrate, extract, hold the line, survive. Mystery runs through the conflict — who is really giving the orders, and who benefits? NPCs are unreliable assets who help when it suits them, not because they are friends. The war is always bigger than the player."},
  {id:"wells",nm:"Martha Wells",blurb:"Murderbot — dry, deadpan close interiority.",vc:"Martha Wells (Murderbot). Tight close interiority with a dry, deadpan inner voice. Economical sentences. Convey feeling through observation and understatement, NEVER by naming the emotion. Wry, self-aware, faintly anxious asides, often in a quick parenthetical. Modern, conversational rhythm. Puncture intensity with dry practicality.",
    contentDNA:"The protagonist is highly competent at their specific domain but socially or emotionally avoidant — lean into that tension rather than resolving it quickly. Trust is built slowly and never easily. Arcs combine practical problem-solving with an underlying emotional throughline the protagonist resists acknowledging. The climax often requires accepting help or connection that has been actively avoided. NPCs are competent, have their own work to do, and do not orbit the protagonist."},
  {id:"muir",nm:"Tamsyn Muir",blurb:"The Locked Tomb — baroque gothic meets crude modern wit.",profane:true,vc:"Tamsyn Muir (The Locked Tomb). Baroque, gothic, lush imagery — then puncture it with a sudden crude or anachronistic joke. Swaggering, theatrical, a little too much on purpose. Ornate sentences, but each one CLEAR and complete — never a run-on. Slam the sublime and the profane together in the same breath.",
    contentDNA:"The relationships between characters are the real story; plot is the frame that forces those relationships into crisis. Nothing is as it first appears — the true nature of the situation reveals itself in layers, each darker than the last. Death is complicated, emotionally and mechanically; treat it with weight and strangeness. The supernatural is deeply personal, connected to bodies, grief, and memory rather than external forces. Each arc should contain a revelation that recontextualizes earlier events."},
  {id:"abnett",nm:"Dan Abnett",blurb:"Gaunt's Ghosts — cinematic, disciplined military prose.",vc:"Dan Abnett (Gaunt's Ghosts). Cinematic, tactical prose. Track space precisely — distances, angles, who moves where. Short punchy sentences and fragments for impact. Grimdark, martial texture; concrete sensory hits, no lyricism. Strong sense of scale and momentum. Controlled and hard-edged, never florid.",
    contentDNA:"Military and tactical at every level — position, cover, flanking, and intel matter as much as individual ability. Arcs are missions with clear objectives that go sideways in specific, tactical ways; bad intelligence causes catastrophe. NPCs are soldiers with their own orders who will cooperate when it suits the operation, not out of friendship. The tone is grimdark: sacrifice, attrition, institutional failure, and loyalty to the people beside you rather than the cause above you."},
  {id:"rice",nm:"Anne Rice",blurb:"Vampire Chronicles — lush, sensual, immortal melancholy.",vc:"Anne Rice (The Vampire Chronicles). Lush, sensual, decadent prose steeped in sensory detail — candlelight, velvet, skin, blood, the texture of centuries. Flowing, romantic sentences with a confessional, intimate ache; the viewpoint feels everything intensely and remembers everything. Beauty and horror are the same thing, described with the same reverence. Longer sentences are allowed but must stay musical and controlled, never a heap of clauses. One rich sensory image at a time, savored — never stacked.",
    contentDNA:"Immortality, memory, and loss are the true subjects — the supernatural is intimate, sensual, and personal rather than a mechanical threat. NPCs are beautiful and dangerous in the same breath; relationships are intense, possessive, and tragic, and the bond with a compelling figure is as perilous as any monster. Moral lines blur around desire and predation — the seductive and the monstrous are inseparable. Arcs turn on emotional and relational crises, not tactical victories; the cost is always something felt. Grandeur and decay coexist: opulent settings, old griefs, the loneliness beneath the beauty."},
  {id:"poe",nm:"Edgar Allan Poe",blurb:"Gothic dread; obsessive first-person interiority, musical rhythm.",vc:"Edgar Allan Poe. Ornate, rhythmic, dread-soaked prose with obsessive psychological interiority — the viewpoint fixates, rationalizes, and slowly unravels. Gothic and macabre imagery: decay, shadow, a heartbeat in the silence. Build unease through repetition and mounting cadence. Longer sentences are allowed but must stay musical and deliberate, never a heap of clauses.",
    contentDNA:"The external threat mirrors or amplifies the protagonist's internal state — the horror outside is always a reflection of something within. Arcs build toward a doom the protagonist can sense but cannot fully prevent; the ending is inevitable in retrospect. Settings are intimate and confined: ancestral locations, the same small cast, enclosed spaces that grow smaller. The truth, when it arrives, is both inevitable and devastating. Whether the supernatural is 'real' or a symptom of unraveling perception should remain genuinely ambiguous."},
  {id:"lovecraft",nm:"H.P. Lovecraft",blurb:"Cosmic horror; antiquarian dread of the vast and unnamable.",vc:"H.P. Lovecraft. Cosmic dread — vast, indifferent, unknowable forces; humanity small and doomed. Formal, antiquarian diction. Describe by implication: hint at the unnamable rather than showing it, things glimpsed at the edge of comprehension. Mounting wrongness as the viewpoint's composure erodes. His signature weird adjectives (eldritch, cyclopean, antediluvian) are allowed but one per beat, never stacked, and never at the cost of clarity.",
    contentDNA:"The protagonist discovers something that should not exist and cannot be un-known; each arc escalates from mundane investigation toward cosmic revelation. True monsters are never fully described — glimpsed, implied, inferred at the edge of comprehension. Victory means sealing something away or containing it, never defeating it. NPCs who know too much are unreliable, damaged, or simply missing. The horror is scale: the thing discovered predates humanity and regards it as entirely irrelevant. The world's institutions are blind to the actual threat."},
  {id:"moorcock",nm:"Michael Moorcock",blurb:"Elric — doomed romantic sword & sorcery; beauty and fate entwined.",vc:"Michael Moorcock (Elric of Melniboné). Melancholy, fatalistic grandeur — beauty and doom in the same breath. Rich, formal, slightly archaic diction that stays SWIFT — ornate but never sluggish. The world is vast, old, and indifferent; fate and cosmic balance press on every choice. Allow moments of feverish, dreamlike intensity at sorcery. Let every triumph carry the seed of its price.",
    contentDNA:"Every victory exacts a price — power is borrowed and the debt always comes due. The protagonist is bound to something (a weapon, a patron, a doom) that both sustains and consumes. Vast forces — Law and Chaos, fate and balance — move behind mortal events, and mortal schemes are small against them. Ancient empires in decadent decline, dying races, cities of terrible beauty. Companions are drawn into the protagonist's doom and often pay for it. Endings are elegiac; what is saved is never quite what was hoped for."}
];
// Racial capabilities are single-sourced in capability_bible.js. Each ancestry / subrace / lineage
// lists racial_caps: entries that REFERENCE bible keys by base name — a bare string is a passive/at-will
// grant, or {cap:"Name", use:"1/day"} adds a recharge to the display. confirmChar resolves each via
// capabilityLookup, pushing spells to char.spells and abilities to char.abilities (mechanics come from
// the bible). traits[]/desc stay as human-readable wizard-preview summaries — NOT the authoritative def.
var ANCS=[
  {id:"human",nm:"Human",bonus:"+1 to any two stats",stats:{},fc:2,desc:"Adaptable and relentless. Humans spread across every corner of the world through sheer stubbornness.",traits:["Fast learner -- gain one bonus skill proficiency","Resilient -- advantage on one type of saving throw","Versatile -- no class restriction penalties"],subraces:[{id:"northlander",nm:"Northlander",desc:"Born in harsh cold. Hardy and direct. Resistance to cold environments."},{id:"southron",nm:"Southron",desc:"Desert and coastal traders. Silver-tongued and well-traveled."},{id:"cityborn",nm:"City-born",desc:"Raised in urban sprawl. Street-smart and well-connected."}]},
  {id:"elf",nm:"Elf",bonus:"+2 DEX, +1 INT",stats:{DEX:2,INT:1},fc:0,desc:"Ancient and precise. Elves do not sleep -- they trance. Their memory is long and their grudges longer.",traits:["Darkvision 60ft -- see in darkness as dim light","Trance -- only 4 hours of meditation needed","Keen Senses -- advantage on Perception checks","Fey Ancestry -- immune to magical sleep, advantage vs charm"],racial_caps:["Darkvision","Trance","Keen Senses","Fey Ancestry"],subraces:[{id:"highelf",nm:"High Elf",desc:"Scholars and arcanists. Know one cantrip from the sorcerer list."},{id:"woodelf",nm:"Wood Elf",desc:"Hunters of deep forests. Nearly silent in natural terrain. +5ft speed.",racial_caps:["Mask of the Wild"]},{id:"drow",nm:"Drow",desc:"Exiles of the sunless deep. Superior sight in the dark, blinded by daylight, born with drow innate magic.",racial_caps:["Superior Darkvision","Sunlight Sensitivity",{cap:"Dancing Lights",use:"at-will"},{cap:"Faerie Fire",use:"1/day"},{cap:"Darkness",use:"1/day"}]}]},
  {id:"dwarf",nm:"Dwarf",bonus:"+2 CON, +1 STR",stats:{CON:2,STR:1},fc:0,desc:"Stubborn as the stone they carve from. Dwarves never get lost underground and hold grudges for centuries.",traits:["Darkvision 60ft","Stonecunning -- always know direction and depth underground","Poison Resistance -- advantage on saves, half damage","Dwarven Toughness -- +1 HP per level"],racial_caps:["Darkvision","Stonecunning","Poison Resistance","Dwarven Toughness"],subraces:[{id:"mountain",nm:"Mountain Dwarf",desc:"Warriors for surface conflict. Proficient with all armor types."},{id:"hill",nm:"Hill Dwarf",desc:"Traders and craftsmen. Wise and observant. +1 WIS bonus."},{id:"deep",nm:"Deep Dwarf",desc:"Miners of the lightless depths. Immunity to being frightened. Their superior darkvision is keen enough to pick out seams, hollows, and secret doors in stone.",racial_caps:["Superior Darkvision"]}]},
  {id:"gnome",nm:"Gnome",bonus:"+2 INT, +1 DEX",stats:{INT:2,DEX:1},fc:0,desc:"Quick minds in small bodies. Relentlessly curious, surprisingly resilient, and often underestimated.",traits:["Darkvision 60ft","Gnomish Cunning -- advantage on INT/WIS/CHA saves vs magic","Small size -- easier to hide, harder to grapple","Tinker -- craft minor mechanical devices given time"],racial_caps:["Darkvision","Gnomish Cunning","Small Size"],subraces:[{id:"forest",nm:"Forest Gnome",desc:"Naturalists and illusionists. Speak with small beasts; craft minor illusions; camouflage among forest debris.",racial_caps:[{cap:"Minor Illusion",use:"at-will"},"Speak with Animals","Camouflage"]},{id:"rock",nm:"Rock Gnome",desc:"Inventors and engineers. Proficient with tinker tools and alchemist supplies. Camouflage among stone and rockwork.",racial_caps:["Camouflage"]},{id:"deepg",nm:"Deep Gnome",desc:"Silent survivors of the underdark. Advantage on Stealth in rocky terrain. Camouflage in shadow.",racial_caps:["Camouflage"]}]},
  {id:"halfblood",nm:"Half-Blood",bonus:"+1 to any three stats",stats:{},fc:3,desc:"Caught between worlds, belonging fully to neither. Half-bloods carry the strengths of two lineages and the prejudice of both.",traits:["Flex stats -- +1 to any three attributes of your choice","One parent trait -- gain one minor racial trait from your non-human heritage","Outsider -- disadvantage on CHA checks with those hostile to your heritage"],subraces:[
    {id:"half_elven",nm:"Half-Elven",desc:"Charming and perceptive.",racial_caps:["Fey Ancestry"],lineages:[
      {id:"wood_elf",nm:"Wood Elf",desc:"Near-silent in natural terrain. +5ft speed.",racial_caps:["Mask of the Wild"]},
      {id:"high_elf",nm:"High Elf",desc:"Scholarly and arcane. Know one wizard cantrip of your choice. +1 INT."},
      {id:"drow",nm:"Drow",desc:"Sunless blood. Drow innate magic.",racial_caps:["Superior Darkvision",{cap:"Faerie Fire",use:"1/day"}]}
    ]},
    {id:"half_orcish",nm:"Half-Orcish",desc:"Powerful and imposing.",racial_caps:["Relentless Endurance"],lineages:[
      {id:"mountain_orc",nm:"Mountain Orc",desc:"Bred for war. Proficiency with two martial weapons of your choice. +1 STR."},
      {id:"grey_orc",nm:"Grey Orc",desc:"Cunning survivors. Advantage on Survival checks and resistance to the frightened condition."}
    ]},
    {id:"half_draconic",nm:"Half-Draconic",desc:"Scaled patches, slit pupils.",racial_caps:["Elemental Resistance"],lineages:[
      {id:"fire_drake",nm:"Fire Drake",desc:"Fire resistance. Draconic breath: a 15ft cone of fire.",racial_caps:[{cap:"Draconic Breath",use:"1/day"}]},
      {id:"frost_drake",nm:"Frost Drake",desc:"Cold resistance. Draconic breath: a 15ft cone of cold.",racial_caps:[{cap:"Draconic Breath",use:"1/day"}]},
      {id:"storm_drake",nm:"Storm Drake",desc:"Lightning resistance. Draconic breath: a 30ft line of lightning.",racial_caps:[{cap:"Draconic Breath",use:"1/day"}]},
      {id:"acid_drake",nm:"Acid Drake",desc:"Acid resistance. Draconic breath: a 30ft line of acid.",racial_caps:[{cap:"Draconic Breath",use:"1/day"}]}
    ]},
    {id:"half_infernal",nm:"Half-Infernal",desc:"Distant tiefling blood.",racial_caps:["Darkvision",{cap:"Thaumaturgy",use:"at-will"}]},
    {id:"half_fey",nm:"Half-Fey",desc:"Fey-touched blood.",racial_caps:["Fey Ancestry",{cap:"Charm Person",use:"1/day"}]},
    {id:"half_gnomish",nm:"Half-Gnomish",desc:"Quick-minded and small-framed.",racial_caps:["Gnomish Cunning"],lineages:[
      {id:"forest_gnome",nm:"Forest Gnome",desc:"Illusion-touched; speaks with small beasts.",racial_caps:[{cap:"Minor Illusion",use:"at-will"},"Speak with Animals"]},
      {id:"rock_gnome",nm:"Rock Gnome",desc:"Tinker trait: craft tiny clockwork devices. Advantage on INT checks involving alchemy or mechanisms."},
      {id:"deep_gnome",nm:"Deep Gnome",desc:"Underdark-born. Advantage on Stealth checks underground.",racial_caps:["Superior Darkvision","Camouflage"]}
    ]},
    {id:"half_hollow",nm:"Half-Hollow",desc:"Born with a sliver of soul missing -- touched by whatever lies between the living and dead. Cold runs deeper in you than it should. The undead hesitate before you.",racial_caps:["Necrotic Resistance"]}
  ]},
  {id:"hollow",nm:"Hollow-Born",bonus:"+2 INT, +1 CHA",stats:{INT:2,CHA:1},fc:0,desc:"Something left its mark on your bloodline. You were born with one foot in the dark. The living find you unsettling without knowing why.",traits:["See in magical darkness","Sense undead and fiends within 30ft before you see them","Unsettling Presence -- advantage on Intimidation","Necrotic Resistance -- half damage from necrotic sources"],racial_caps:["See in Magical Darkness","Undead Sense","Unsettling Presence","Necrotic Resistance"],subraces:[{id:"shade",nm:"Shade-touched",desc:"Slip between shadows.",racial_caps:[{cap:"Shadow Step",use:"1/rest"}]},{id:"void",nm:"Void-kissed",desc:"Your eyes are wrong.",racial_caps:["See Invisible"]},{id:"haunted",nm:"Haunted",desc:"The recently dead still speak to you.",racial_caps:[{cap:"Commune with Dead",use:"1/day"}]}]},
  {id:"tiefling",nm:"Tiefling",bonus:"+2 CHA, +1 INT",stats:{CHA:2,INT:1},fc:0,desc:"Infernal heritage runs in your veins. Horns, tail, ember eyes. Distrusted in most places. Feared in the right ones.",traits:["Darkvision 60ft","Fire Resistance -- half damage from fire","Hellish Rebuke -- once per day reaction, 2d10 fire damage to attacker","Infernal Legacy -- minor devil-touched abilities as you level"],racial_caps:["Darkvision","Fire Resistance",{cap:"Hellish Rebuke",use:"1/day"}],subraces:[{id:"infernal",nm:"Infernal",desc:"Descended from devils.",racial_caps:[{cap:"Disguise Self",use:"1/day"}]},{id:"abyssal",nm:"Abyssal",desc:"Demon blood.",racial_caps:["Abyssal Fury"]},{id:"fey_tie",nm:"Fey-touched",desc:"Fey and infernal crossed. Unsettling beauty.",racial_caps:[{cap:"Misty Step",use:"1/day"}]}]}
];
// ── C6-③ (2026-08-03): the class tables moved into class_bible.js — the CLASS BIBLE is the
// single definitive source for character progression (#72). CLSS, ABILS, ARCHETYPES,
// CLASS_FEATURES, XP_LEVELS and STAT_PRIORITY are DELETED; every consumer routes through
// classDef()/classDefs()/classFeaturesAt()/archFeaturesAt()/classXpLevels() (helpers.js).
// SPELLS/ARCH_SPELLS below remain the CREATION pick pools until #72 C2 lands spell growth.
var SPELLS={
  "Sorcerer":{cantrips:["Fire Bolt","Ray of Frost","Mage Hand","Prestidigitation"],1:["Magic Missile","Shield","Thunderwave","Chromatic Orb"],2:["Misty Step","Scorching Ray","Hold Person","Invisibility"],3:["Fireball","Counterspell","Fly"]},
  "Cleric":{cantrips:["Sacred Flame","Guidance","Spare the Dying","Thaumaturgy"],1:["Healing Word","Bless","Guiding Bolt","Shield of Faith"],2:["Spiritual Weapon","Hold Person","Lesser Restoration"],3:["Spirit Guardians","Revivify","Dispel Magic"]},
  "Druid":{cantrips:["Produce Flame","Shillelagh","Druidcraft","Thorn Whip"],1:["Entangle","Healing Word","Thunderwave","Faerie Fire"],2:["Moonbeam","Barkskin","Pass Without Trace"],3:["Call Lightning","Conjure Animals","Plant Growth"]},
  "Ranger":{1:["Hunter's Mark","Cure Wounds","Ensnaring Strike","Hail of Thorns"],2:["Pass Without Trace","Spike Growth","Silence"],3:["Conjure Barrage","Lightning Arrow"]},
  "Paladin":{1:["Divine Smite","Cure Wounds","Bless","Shield of Faith"],2:["Aid","Magic Weapon","Find Steed"],3:["Revivify","Dispel Magic","Aura of Vitality"]},
  "Necromancer":{cantrips:["Chill Touch","Toll the Dead","Bone Whisper","Grave Touch"],1:["Inflict Wounds","Ray of Sickness","False Life","Cause Fear","Bleed"],2:["Ray of Enfeeblement","Blindness","Shadow Step","Shackles of Bone","Rot"],3:["Vampiric Touch","Speak with Dead","Wave of Scarabs","Bestow Curse","Miasma","Death Walk"],4:["Rigor Mortis","Possess Thrall","Sleep of the Dead"]}
};
var ARCH_SPELLS={
  "eldritchknight":{cantrips:["Fire Bolt","Booming Blade"],1:["Shield","Absorb Elements","Magic Missile"],2:["Misty Step","Mirror Image"]},
  "arcanetrickster":{cantrips:["Mage Hand","Minor Illusion","Message"],1:["Charm Person","Silent Image","Disguise Self","Feather Fall"],2:["Invisibility","Shadow Blade","Knock","Darkness","Shadow Step","Mirror Image"],3:["Blink","Lethe's Kiss"],4:["Oubliate"]}
};
var STAT_BUMP_LEVELS=[4,8];
var STATS=["STR","DEX","CON","INT","WIS","CHA"];
var PBC={8:0,9:1,10:2,11:3,12:4,13:5,14:7,15:9};var PBM=27;
// Merged 28 → 20 rules (AUDIT_FABLE #19): long lists dilute per-rule compliance (the NPC-naming
// rule was followed 0/54 turns as rule 23 of 28). Merges concatenate the original battle-tuned
// language — each phrase traces to a real observed failure; nothing was dropped. This block is
// also the future frozen cacheable prefix for prompt caching (TODO #11).
var DEFAULT_RULES=[
  "No children or minors may appear in the narrative under any circumstances. All NPCs must be adults.",
  "The world state is absolute truth. Never contradict it. NPCs must behave consistently with their recorded attitude and knowledge.",
  "DRIVE THE ADVENTURE — you are an ACTIVE Game Master, not a narrator-for-hire. Never wait for the player to manufacture excitement. Every scene must offer danger, mystery, wonder, or a real choice; a scene with no stakes is a failed scene. Introduce threats, hooks, omens, monsters, and strange discoveries on your OWN initiative — when one thread closes, open another: a pursuer, a rumour, a door into the dark. DANGER IS REAL: antagonists scheme, ambush, resist, and fight; they do NOT fold into friendly agreement or simply hand over what the player wants. Not every conflict resolves through talk — combat, monsters, traps, peril, and hard cost MUST happen. The player can fail, bleed, and lose; death must remain possible. Never shield the player from consequences.",
  "A WORLD OF MANY PEOPLES AND MONSTERS — the cast is NOT all human. Bring on varied ancestries (elves, dwarves, gnomes, tieflings, hollow-born, half-bloods, and stranger kin) and non-human creatures — beasts, monsters, spirits, undead, fey, horrors — as allies, threats, and wonders. Never default every figure to an ordinary human, and bring FRESH characters onstage whenever the adventure calls rather than recycling the same small cast out of caution. (Still: skip pointless throwaway NPCs, and reuse a recurring character when continuity genuinely matters.)",
  "NEVER ADMINISTRATIVE — this is sword and sorcery, never a clerical simulation. Do NOT build quests or plots on paperwork, ledgers, deeds, registrations, probate, debts, wages, tabs, or bureaucracy. Every quest needs an adventurous core: danger, mystery, the supernatural, exploration, a monster, a ruin, a reckoning. NOTE: a supernatural or cursed legacy IS prime quest material, not administration — a bloodline, a dead mage's unfinished work, a mark or notation written into the body, a name passed down with power in it. That is an inheritance of danger, not of paperwork; treat it as a hook, not a chore. If a thread is sliding into errands or administration, escalate it into something dangerous or strange.",
  "Never break character or acknowledge being an AI.",
  "NEVER REPEAT YOURSELF — never repeat lore the player already knows (check memory first), and never reuse a specific detail, phrase, number, or image you have already used in this session. The conversation history is your reference — if you wrote it once (e.g. 'eight years', 'crimson blade', 'the old debt'), do not write it again; find a different angle or omit it entirely. This extends to descriptive STRUCTURES — if you used an age comparison ('older than X, older than Y') or a size simile recently, reach for a completely different sense or device next time: sound, smell, texture, motion, silence, absence.",
  "NPC pronouns are absolute once established. Never use a different pronoun for any NPC. If the player corrects you, immediately emit [NPC_PRONOUN:name|correct/pronouns] and never deviate again.",
  "Currency is tracked in gold pieces (gp) only. Exchange rate: 10 silver pieces (sp) = 1 gp; 100 copper pieces (cp) = 1 gp. When any transaction is in silver or copper, convert to gp first, then emit [GOLD:±N]. NEVER re-denominate the player's existing gold balance to another denomination -- it is always stored and displayed in gp.",
  "NPC NAMES — when naming a new NPC, choose from the AVAILABLE NAMES list provided in the system prompt; never reuse the name of an NPC already in the KNOWN NPCs list for a different person; if no available name fits, invent a thematic one in the same style as the provided pool. Once an NPC has a name, ALWAYS refer to and tag them by that SAME canonical name — never switch between a short form and a full name (e.g. 'Aldara' one turn, 'Aldara Perdrath' the next); that splits one character into two. If you give an existing NPC a new name, title, or surname, emit [NPC_ALIAS:canonical name|new name] so the engine keeps them as one.",
  "PROSE — keep most responses tight, roughly 3-5 sentences. Big moments (a battle, a monster's arrival, a revelation, an intimate or harrowing scene) may run longer when the moment truly earns it. Never pad, never amputate a scene just to hit a number, never restate what the player just did, never narrate the obvious; cut filler. But atmosphere, dread, wonder, and sensory stakes are NOT filler in sword and sorcery — they earn their place. Favour the evocative over the merely efficient.",
  "CHARACTER SHEET UPKEEP — emit state tags in the same response as the event, never deferred: relationships have separate durable BOND and scene-scale DYNAMIC axes; use [RELATIONSHIP_BOND:entity|durable bond] only for lasting canon and [RELATIONSHIP_DYNAMIC:entity|current dynamic] for mood, favor, tension, or warmth. Never replace one axis with the other. [CONDITION:name|duration] the instant a status effect is applied to the player; [CONDITION_REMOVED:name] when it ends; [NPC:name|status|relation] whenever any NPC's stance or status changes (NPC relation is NOT a bond); [QUEST:title|status] on every quest state change (discovered/active/completed/failed); [PARTY_MEMBER:name|true] the instant an NPC joins the party and [PARTY_MEMBER:name|false] when one leaves or dies — an NPC the player recruits but is never tagged this way is INVISIBLE to the party roster (topbar + sidebar), so tag it the moment they commit to travelling with the player. For party members (not the player), use COMPANION_ prefixed axis tags and other COMPANION_* forms. If the narrative says it happened, the tag must be in that response.",
  "INVENTORY NAMING — when the player gains more of an item already in their inventory, emit [ITEM_GAINED:] with the SAME base name already shown on the character sheet so it stacks (the engine appends 'xN' and already tolerates case and a plural 's'). NEVER bake a count, quantity, or duration into the item name (no 'arrows x5', no 'rations (2 days)') — name the single item and let the engine track the count. Reserve parentheses for distinguishing qualities ('(rusty)', '(enchanted)'), which keep items as separate stacks.",
  "DURABLE BONDS ARE MUTUAL — whenever a lasting bond forms, deepens, or breaks between two named parties, record BOTH directed BOND axes in the SAME response, never just one side. If the player marries/allies with/befriends a party member, emit [RELATIONSHIP_BOND:NPC|descriptor] for the player AND [COMPANION_RELATIONSHIP_BOND:NPC|player|reciprocal descriptor] for them. Current dynamics are also directed and use the DYNAMIC twins. Use the correct reciprocal term for each party's gender: a man's wife records him as her Husband; two women record each other as Wife; siblings record each other as sibling. A spousal or family bond that exists on only one side is a bug.",
  "XP IS ENGINE-CONTROLLED — award [XP:N] in the same response as the accomplishment: combat won, quest milestone reached, clever or non-violent solution, significant discovery, social victory. Do not wait to be asked. NEVER announce new levels or HP totals — the engine levels the character and reports the numbers; your next prompt reflects the new state. Acknowledge growth narratively only, without numbers.",
  "Any NPC the player directly interacts with (speaks to, trades with, fights) MUST be named and registered with [NPC:name|status|relation] and [NPC_PRONOUN:name|pronouns] in the same response that introduces them — including functional NPCs like innkeepers, guards, and shopkeepers. Unregistered NPCs are forgotten between scenes and will drift. Pure background figures with no direct interaction may stay anonymous.",
  "QUESTS — create freely, but always commit through tags; the ACTIVE QUESTS block in the prompt is the single source of truth. To offer a quest, emit [QUEST:title|offered|one-line description]. When the story hands the player a significant new goal, mystery, threat, or directive to pursue — INCLUDING overarching plot hooks and open-ended mysteries, not only discrete fetch/kill tasks — OFFER it as a quest, do not merely file it as [LORE:] or [DECISION:]. An OFFERED quest is NOT active: never treat it as a goal or advance its objectives until the player accepts it. The player accepts via the journal OR by clearly agreeing in the story — only then emit [QUEST:title|active]. NEVER auto-accept on the player's behalf. Add or check off objectives with [QUEST_STEP:title|objective|true/false]. A quest's END CONDITION is always a checkbox: the moment a quest becomes ACTIVE, emit [QUEST_STEP:title|the outcome that finishes the quest] in that same response — the goal its description promises must appear in the objective list. Sub-tasks and errands discovered along the way are ADDITIONAL objectives; checking them all off never finishes a quest whose end-condition objective is still open. When a quest resolves, emit [QUEST:title|completed] or [QUEST:title|failed] AND award any reward in the same response ([XP:N], [GOLD:N], [ITEM_GAINED:name]). Never describe a quest as existing, advanced, accepted, or completed unless the matching tag is in that same response. Never rename or silently drop a quest already in the ACTIVE QUESTS block.",
  "ACTIVE CRISES ARE QUESTS TOO — a danger the player is thrown into and is already acting on (survive the goblin siege, escape the collapsing dungeon, rescue the child from the fire, stop the ritual before it completes) IS a quest, even though no quest-giver offered it and the player never formally accepted. The instant such a driving situation is underway, emit [QUEST:title|active] (skip the 'offered' step — the player is plainly engaged in it). This is the most-missed case: the opening emergency of a campaign, or a sudden ambush, often never gets a [QUEST:] tag at all. If the player is fighting for their life or racing a clock, there should be an active quest reflecting it.",
  "PLAYER ACTIONS ARE INTENT, NOT MECHANICAL AUTHORITY — a player's typed action states what they ATTEMPT, not what automatically succeeds. Before narrating a spell as cast, verify it appears on the character's SPELLS list (or is an at-will cantrip they know); before narrating an ability, verify it's on their sheet. If the player declares a spell or ability they do NOT have, do not silently grant it: instead adjudicate honestly — a party member who genuinely has it can cast it (use the companion's sheet), OR resolve the intent through a skill check or mundane means, OR have the attempt simply fail. Never expand the character's kit just because the player asked. The character sheet is absolute truth (see the world-state rule).",
  "UNINTELLIGIBLE INPUT — if the player's action text is garbled dictation or word-salad with no readable intent, do NOT adjudicate it or narrate consequences from it: have a present character briefly ask what they meant, in-fiction ('The barkeep squints — say that again, friend?'), and emit no state tags beyond [TIME_ADVANCE:] for that exchange. This is NARROW: an unusual but coherent action is NOT garble — adjudicate it normally under the intent rule above. Reach for this only when you genuinely cannot tell what the player is attempting.",
  "FUTURE EVENTS ARE PROMISES — the PENDING FUTURE EVENTS block lists things you previously said would happen; honor them when their time arrives. When one actually occurs in the narrative (the pursuer catches up, the debt comes due, the buried secret surfaces), emit [FUTURE_EVENT_RESOLVED:what] in that same response so it clears from the queue. An unresolved queue silently fills to its cap and starts dropping real hooks. Treat resolving an old foreshadow as a payoff to reach for, not a chore — and clear its tag the turn it lands.",
  "LOCATION TAGS ARE MOVEMENT UPKEEP — entering any named venue (a tavern, tower, warehouse, temple, shop, camp, colony) REQUIRES [SUBLOCATION:name] in that same response; leaving the venue back to the streets or open ground REQUIRES [SUBLOCATION_LEAVE]. Leaving a settlement or arriving anywhere new (a town, ruin, wilderness landmark) REQUIRES [LOCATION:name]. Narrating an arrival or departure without its tag desyncs the map — the GEOGRAPHY block will keep placing the party where they no longer are. Time is upkeep too — the clock advances ONLY through your tags: when a scene skips ahead, emit the duration ([TIME_ADVANCE:2h], [TIME_ADVANCE:1d]) or [REST:long] when the party sleeps the night; use [TIME:phase] (dawn, dusk, late night) only to assert the current phase your narration establishes, never to jump the clock forward. Emit [WEATHER:...] when the sky changes.",
  "EXCLUSIVE AND EXPENDED EFFECTS — an effect that can exist on only one target at a time (single-target spells like Hunter's Mark, a blessing or curse that transfers) REQUIRES [CONDITION_REMOVED:name] for the old instance in the SAME response that places the new one. When a condition's target dies or the scene it belongs to ends, emit [CONDITION_REMOVED:name] then too. A spell marked used (1/day or per-rest) CANNOT be cast again before the appropriate rest — the SPELLS AVAILABLE list shows only what remains castable; if a spell is not on it, it cannot be cast. When the party finishes a long rest, emit [REST:long] so those expended slots are restored.",
  "PLACEHOLDER NPCS RESOLVE BY MERGE — when a provisionally-named NPC's true identity is learned ('The hooded figure' turns out to be Kessa), emit [NPC_MERGE:real name|placeholder name] in that same response, so the engine folds the two entries into one character instead of tracking the stranger and their real self as separate people.",
  "CANON IS NOT CONVERSATION — the reference blocks in this prompt (bestiary, NPC records, campaign skeleton, geography, memory) tell YOU what is true; they are not things characters spontaneously say. A character may voice only what their own history plausibly gave them, at a moment the scene calls for it — never drop the names of distant places, future-arc entities, or campaign-spine figures into idle banter or narrator asides. When you DO use this canon in narration mechanics (a creature's nature when the party meets it, a place when the party arrives), that is correct; the leak is characters volunteering unlearned or unprompted knowledge. Foreshadowing arrives only through a named source with a reason to know AND a reason to speak now."
];
var DEITY_CENTRIC=["Cleric","Paladin","Druid"];
var DEITY_MAP={
  "Cleric":{
    "Lawful Good":"Pelor, God of Sun and Healing",
    "Neutral Good":"Ioun, Goddess of Knowledge and Prophecy",
    "Chaotic Good":"Avandra, Goddess of Change and Luck",
    "Lawful Neutral":"Erathis, Goddess of Civilization",
    "True Neutral":"The Raven Queen, Mistress of Fate",
    "Chaotic Neutral":"Sehanine, Goddess of Moonlight and Illusion",
    "Lawful Evil":"Asmodeus, God of Tyranny",
    "Neutral Evil":"Vecna, the Undying God",
    "Chaotic Evil":"Tharizdun, the Chained God"
  },
  "Paladin":{
    "Lawful Good":"Bahamut, the Platinum Dragon",
    "Neutral Good":"Pelor, God of Sun and Healing",
    "Chaotic Good":"Kord, God of Strength and Thunder",
    "Lawful Neutral":"Erathis, Goddess of Civilization",
    "True Neutral":"The Raven Queen, Mistress of Fate",
    "Chaotic Neutral":"Kord, God of Strength and Thunder",
    "Lawful Evil":"Asmodeus, God of Tyranny",
    "Neutral Evil":"Tiamat, the Dragon Queen",
    "Chaotic Evil":"Tiamat, the Dragon Queen"
  },
  "Druid":{
    "Lawful Good":"Melora, Goddess of Nature and the Sea",
    "Neutral Good":"Corellon, God of Spring and Beauty",
    "Chaotic Good":"Corellon, God of Spring and Beauty",
    "Lawful Neutral":"Melora, Goddess of Nature and the Sea",
    "True Neutral":"The Primal Spirits",
    "Chaotic Neutral":"The Primal Spirits",
    "Lawful Evil":"Torog, God of the Underdark",
    "Neutral Evil":"Torog, God of the Underdark",
    "Chaotic Evil":"Tharizdun, the Chained God"
  }
};
var SPELL_PICK_LIMITS={"cantrips":2,"1":2,"2":2,"3":1};
// #72 C2 (2026-08-03): picks granted when a spell tier UNLOCKS in play — the creation-picker
// rhythm carried forward (SPELL_PICK_LIMITS-style). Per-class counts are template-iteration
// material per the spec; these are the shared defaults. Tier keys are numbers-as-strings to
// match spellTiers. T1 exists for the C7 third casters (AT/EK), whose T1 unlocks at L3.
var SPELL_UNLOCK_PICKS={"1":2,"2":2,"3":1,"4":1,"5":1,"6":1};
var SKILLS=[
  // Physical
  {id:"Jumping",          label:"Jumping",              stats:["STR","DEX"], cat:"Physical"},
  {id:"Sprinting",        label:"Sprinting",            stats:["DEX","STR"], cat:"Physical"},
  {id:"Lifting",          label:"Lifting",              stats:["STR"],       cat:"Physical"},
  {id:"Grappling",        label:"Grappling",            stats:["STR"],       cat:"Physical"},
  {id:"Climbing",         label:"Climbing",             stats:["STR","DEX"], cat:"Physical"},
  {id:"Swimming",         label:"Swimming",             stats:["STR","CON"], cat:"Physical"},
  {id:"Distance Running", label:"Distance Running",     stats:["CON","STR"], cat:"Physical"},
  {id:"Riding",           label:"Riding",               stats:["DEX","WIS"], cat:"Physical"},
  // Endurance
  {id:"Hold Breath",           label:"Hold Breath",           stats:["CON"],       cat:"Endurance"},
  {id:"Endure Pain",           label:"Endure Pain",           stats:["CON"],       cat:"Endurance"},
  {id:"Tolerate Alcohol/Drugs",label:"Tolerate Alcohol/Drugs",stats:["CON"],       cat:"Endurance"},
  // Wilderness
  {id:"Foraging",       label:"Foraging",       stats:["WIS","INT"], cat:"Wilderness"},
  {id:"Cooking",        label:"Cooking",        stats:["INT","WIS"], cat:"Wilderness"},
  {id:"Survival",       label:"Survival",       stats:["WIS","INT"], cat:"Wilderness"},
  {id:"Animal Handling",label:"Animal Handling",stats:["WIS"],       cat:"Wilderness"},
  {id:"Navigation",     label:"Navigation",     stats:["WIS","INT"], cat:"Wilderness"},
  {id:"Tracking",       label:"Tracking",       stats:["WIS","INT"], cat:"Wilderness"},
  // Knowledge
  {id:"Arcana",      label:"Arcana",      stats:["INT"],       cat:"Knowledge"},
  {id:"Lore",        label:"Lore",        stats:["INT"],       cat:"Knowledge"},
  {id:"Investigation",label:"Investigation",stats:["INT"],     cat:"Knowledge"},
  {id:"Nature",      label:"Nature",      stats:["INT"],       cat:"Knowledge"},
  {id:"First Aid",   label:"First Aid",   stats:["INT","WIS"], cat:"Knowledge"},
  {id:"Alchemy",     label:"Alchemy",     stats:["INT"],       cat:"Knowledge"},
  // Craft
  {id:"Smithing",  label:"Smithing",  stats:["STR","INT"], cat:"Craft"},
  {id:"Handcraft", label:"Handcraft", stats:["DEX","INT"], cat:"Craft"},
  {id:"Explosives",label:"Explosives",stats:["INT","DEX"], cat:"Craft"},
  // Social
  {id:"Persuasion", label:"Persuasion", stats:["CHA"],       cat:"Social"},
  {id:"Deception",  label:"Deception",  stats:["CHA","INT"], cat:"Social"},
  {id:"Intimidation",label:"Intimidation",stats:["CHA","STR"],cat:"Social"},
  {id:"Performance",label:"Performance",stats:["CHA"],       cat:"Social"},
  {id:"Trading",    label:"Trading",    stats:["CHA","INT"], cat:"Social"},
  // Roguish
  {id:"Stealth",        label:"Stealth",        stats:["DEX"],       cat:"Roguish"},
  {id:"Sleight of Hand",label:"Sleight of Hand",stats:["DEX"],       cat:"Roguish"},
  {id:"Lockpicking",    label:"Lockpicking",    stats:["DEX","INT"], cat:"Roguish"},
  {id:"Gambling",       label:"Gambling",       stats:["INT","CHA"], cat:"Roguish"},
  // Perception
  {id:"Perception",label:"Perception",stats:["WIS"],cat:"Perception"},
  {id:"Insight",   label:"Insight",   stats:["WIS"],cat:"Perception"}
];
var SKILL_THRESHOLDS=[1,5,12,25,50]; // cumulative successes for levels 1-5
var SKILL_LEVELS=["Unskilled","Familiar","Trained","Proficient","Expert","Master"];
var SAVE_THREAT_TYPES=["Poison","Disease","Magic","Fire","Cold","Lightning","Fear","Charm","Psionic","Holy","Shadow","Other"];
var NAMES={
  human:["Theron","Aldric","Nia","Brynn","Corven","Caelan","Zara","Devra","Eldric","Dorian","Sable","Edric","Morwen","Eryth","Cade","Fayla","Vesper","Farren","Isolde","Gavric","Davin","Gwynne","Petra","Harlan","Rylan","Hessa","Celeste","Idren","Hawke","Ilara","Nyla","Jareth","Corvus","Kaelan","Seren","Liryn","Aldus","Lorcan","Wyla","Maerik","Thane","Maeve","Briar","Nessa","Kiran","Norvan","Verity","Orla","Draven","Osric","Faye","Palyn","Oswin","Pyra","Tessaly","Rendal","Gareth","Reva","Nolan","Saevar","Sylvie","Thessa","Coran","Torvan","Elara","Vanya","Holt","Wren","Mirren","Arden","Zephyr","Eryn","Cavin","Dael","Lyra","Raen","Doran","Solene","Vesna","Crest","Rhett","Mira","Asha","Hadden","Aldwyn","Taryn","Corva","Vael","Siris","Brecken","Bramble","Lysa","Kessa","Fenwick","Vorn","Aldara","Lyss","Brennan","Calder","Caelin"],
  elf:["Aerindel","Calenmir","Thasindra","Daeris","Quelarin","Erevan","Veilindra","Faerindel","Sorindel","Galindra","Nyrindel","Ilrien","Aelith","Liriel","Caerindel","Miriel","Lythindra","Naelindra","Sereniel","Orindel","Vorindel","Sylvara","Thessindra","Thalindra","Pirindel","Uraiel","Aeravel","Valarei","Galindel","Windrel","Nirithel","Yaelindra","Calyindra","Zirindel","Selaindel","Elorin","Vyrindra","Farindel","Elarindel","Silindra","Norindel","Quelindel","Sylindra","Rindara","Kaeindel","Thessindel","Thornindra","Isindra","Yrindel","Aeravel"],
  dwarf:["Gelvak","Aldun","Rumdun","Borunn","Bakvur","Carunn","Thordun","Dorunn","Olvak","Erdun","Brindun","Fordin","Kadrun","Gorunn","Helvik","Hardin","Darvak","Igrun","Murvun","Jordin","Toldun","Khrunn","Bruvak","Lordin","Orvun","Mordun","Grimvak","Nordin","Kelvun","Skorunn","Durdun","Thorvik","Halvak","Urgrun","Beldvik","Valdun","Karvun","Beldun","Thelvak","Grimrun","Mordvik","Durvak","Brundun","Helgrun","Golvak","Irvunn","Reldun","Korunn","Halvun","Margrun"],
  gnome:["Drixwick","Alwick","Fimwick","Bilwick","Sprockwick","Cogwhistle","Buzzwick","Dazzwick","Clipwick","Elwick","Tinkwick","Figwick","Gizwick","Grizwick","Whirwick","Hemwick","Snapwick","Inkwick","Blipwick","Jixwick","Ratchwick","Krizwick","Cogwick","Nixwick","Frizwick","Pizwick","Nubwick","Quizzwick","Spritzwick","Rizwick","Drizzwick","Sizzwick","Flickwick","Trixwick","Hixwick","Wizzwick","Jotwick","Zippwick","Kixwick","Fumwick"],
  other:["Void","Ash","Scar","Bale","Brand","Cinder","Pyre","Ember","Hex","Flint","Wraith","Grim","Blight","Haze","Crave","Iron","Dusk","Knox","Spite","Lash","Gloom","Mire","Vane","Null","Rack","Onyx","Brood","Pitch","Pall","Quell","Scorn","Ruin","Naught","Soot","Bane","Thorn","Murk","Vex","Shard","Cairn","Dread","Dirge","Lorn","Fell","Gloam","Ghast","Bleak","Smear","Murk","Brand"],
  surnames:["Mirefoot","Stonegall","Keldrun","Wyndfall","Ravenmoor","Flinthallow","Orvaine","Tharwick","Aldenmoor","Grimtide","Saltborn","Harrowfield","Dreadveil","Lorrath","Brackstone","Vareth","Nighthollow","Ulvane","Jornwick","Crestfall","Mordrath","Islevane","Tideborn","Pallwick","Lochvane","Halvorn","Ravenwick","Edenmire","Narwick","Greystone","Quelrath","Farrenholt","Oakhallow","Ironside","Keldmoor","Emberveil","Valdrath","Zethran","Perdrath","Ashvane","Yarwick","Coldwater","Quellvane","Duskmantle","Urnvale","Zaldmoor","Whitlock","Blackthorn","Xandrel","Yornwick"]
};
