// ─── ITEM BIBLE (TODO #81) ──────────────────────────────────────────────────────────────────
// Curated canon for mechanics-bearing carried items — the spell-bible pattern applied to gear.
// RULED 2026-08-08 (user): GM-injection with curated definitions and PLAYER-CONFIRMED emergent
// items — display-only rejected (zero hardening), model-authored write-once rejected (the first
// hallucination becomes permanent canon).
//
// TYPE vs INSTANCE (the ruled schema constraint): this file defines the TYPE — what an
// "alchemist's fire" IS. Instance state (charges left, provenance, owner, the "x5" count)
// stays on the inventory entry string, never baked into a definition. An entry carrying
// instance fields fails the engine build.
//
// Schema, fixed-attribute discipline (every entry carries the full set, "N/A" where
// inapplicable — injected canon must never query empty):
//   { category: weapon|armor|consumable|tool|quest|treasure|mundane,
//     effect:   what it DOES, mechanically, or "N/A",
//     uses:     usage/recharge model of the TYPE ("single use", "at-will", "1/day", "reusable"),
//     value:    typical price, or "N/A" }
// mundane/treasure NEVER inject (buildItemBibleBlock, api.js) — they exist for the tooltip and
// the viewer only. Keys are itemBaseName() output (helpers.js): lowercased, counts and
// provenance clauses stripped. Reads go through itemLookup() (helpers.js) — the emergent
// per-campaign overlay (worldState.itemBible, player-confirmed via [ITEM_DEF:]) wins over this
// static base.
//
// FORMAT RULES (the editor depends on them):
//  · The data between the >>> <<< markers is machine-REGENERATED by bible_editor.html's
//    exporter — no hand comments inside the markers (they would be lost on export).
//  · Serialization is canonical: JSON.stringify(obj, null, 2). The BIBLE EDITOR CONTRACT
//    (dev/run-tests.js) byte-compares a fresh serialize against this file, so a hand edit
//    that breaks canonical form fails the build instead of silently fighting the editor.
//  · Content curation is the user's pass (the class-bible fill-phase pattern) — this seed set
//    is the t1431 party inventory's clearly mechanics-bearing items plus staple archetypes.
// >>> ITEM BIBLE DATA
var ITEM_BIBLE = {
  "alchemist's fire": {
    "category": "consumable",
    "effect": "Thrown flask that shatters and ignites: 1d4 fire damage on impact and 1d4 more at the start of the target's next turn until doused (an action to extinguish).",
    "uses": "single use — thrown",
    "value": "50 gp"
  },
  "blasting charge": {
    "category": "consumable",
    "effect": "Placed or thrown explosive: 3d6 fire and concussive damage in a 10-ft radius (DEX save DC 13 for half); demolishes doors, thin walls, and rigged supports. Unmistakably loud.",
    "uses": "single use — fuse or trigger",
    "value": "75 gp"
  },
  "healing potion": {
    "category": "consumable",
    "effect": "Drunk as an action: restores 2d4+2 HP.",
    "uses": "single use",
    "value": "50 gp"
  },
  "travel rations": {
    "category": "consumable",
    "effect": "One day of preserved food for one person; a day without food risks exhaustion.",
    "uses": "single use — one day",
    "value": "5 sp"
  },
  "torch": {
    "category": "consumable",
    "effect": "Bright light 20 ft, dim light 20 ft beyond; can ignite flammables or serve as an improvised weapon for 1 fire damage.",
    "uses": "single use — burns about an hour",
    "value": "1 cp"
  },
  "lockpicks": {
    "category": "tool",
    "effect": "Enable Lockpicking attempts on mechanical locks; the skill does the work, the picks make it possible. Incriminating if found during a search.",
    "uses": "reusable",
    "value": "25 gp"
  },
  "lockpick roll": {
    "category": "tool",
    "effect": "A full set of picks and tension bars: enables Lockpicking attempts and grants the working room to retry a failed lock once without breaking a pick.",
    "uses": "reusable",
    "value": "40 gp"
  },
  "trip-wire cord": {
    "category": "tool",
    "effect": "Rigged across a path: a creature crossing must save (DEX DC 12) or fall prone; pairs with a bell or a blasting charge as an alarm or trap trigger.",
    "uses": "reusable once recovered",
    "value": "1 gp"
  },
  "rope": {
    "category": "tool",
    "effect": "50 ft of hemp line for climbing, binding, and hauling. A bound creature escapes only with STR DC 15 or an Escape Artistry success.",
    "uses": "reusable",
    "value": "1 gp"
  },
  "crossbow": {
    "category": "weapon",
    "effect": "Ranged: 1d8 piercing, range 80/320 ft; loading — one shot per action.",
    "uses": "at-will",
    "value": "25 gp"
  },
  "short blade": {
    "category": "weapon",
    "effect": "Light finesse blade: 1d6 piercing or slashing; easily concealed.",
    "uses": "at-will",
    "value": "10 gp"
  },
  "witchlight blade": {
    "category": "weapon",
    "effect": "Short blade that sheds a pale glow on command (dim light 10 ft); counts as magical against resistances; 1d6 piercing.",
    "uses": "at-will",
    "value": "N/A — not commonly sold"
  },
  "bone-handled knife": {
    "category": "weapon",
    "effect": "Small utility blade: 1d4 piercing; doubles as an eating and skinning knife.",
    "uses": "at-will",
    "value": "2 gp"
  },
  "leather armor": {
    "category": "armor",
    "effect": "Light armor: AC 11 + DEX modifier; no penalty to stealth.",
    "uses": "passive while worn",
    "value": "10 gp"
  },
  "veil token pendant": {
    "category": "tool",
    "effect": "Worn iron-and-silver disc: once per day the bearer becomes hard to notice for a scene — advantage on stealth against casual attention; direct scrutiny breaks the effect.",
    "uses": "1/day",
    "value": "N/A — not commonly sold"
  },
  "amber vial": {
    "category": "quest",
    "effect": "Rune-sealed vial recovered from Pale Choir sites; contents unidentified — opening or identifying it is a story action, not a mechanical use.",
    "uses": "N/A — unidentified",
    "value": "N/A"
  },
  "corked vial": {
    "category": "quest",
    "effect": "Unmarked rune-sealed vial; contents unknown until identified in play.",
    "uses": "N/A — unidentified",
    "value": "N/A"
  },
  "bottle of wine": {
    "category": "mundane",
    "effect": "N/A",
    "uses": "single use",
    "value": "2 sp"
  },
  "silver arm": {
    "category": "treasure",
    "effect": "N/A",
    "uses": "N/A",
    "value": "120 gp"
  }
};
// <<< ITEM BIBLE DATA
