// Manual acceptance runner: actual browser, client adapter, authenticated local server and disposable database.
// Never connects an authenticated browser to production; deployment parity is recorded separately.
const fs=require('fs'),path=require('path'),os=require('os'),http=require('http'),net=require('net'),cp=require('child_process'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../..'),serverRoot=process.env.TND_SERVER_REPO||'C:/Projects/traffic-and-dragons-server',out=process.env.TND589_DEPLOYED ? path.join(__dirname,'deployed-browser') : __dirname;
const deployedRef='0de4866f2aec79716029138755e44ada2976e973';
const {chromium}=require(path.join(root,'dev/cdp-browser.js')),engine=require(path.join(root,'dev/load-engine.js'));
const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'tnd-589-acceptance-')),results=[],requests=[],blocked=[],errors=[];let browser,apiProcess,staticServer,serverLogs='';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function port(){const s=net.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const p=s.address().port;await new Promise(r=>s.close(r));return p;}
async function startApi(source,dbName){const p=await port(),base='http://127.0.0.1:'+p;serverLogs='';apiProcess=cp.spawn(process.execPath,['index.js'],{cwd:source,windowsHide:true,env:{...process.env,PORT:String(p),DB_PATH:path.join(scratch,dbName),DEV_LOGIN_SECRET:'synthetic-589',DOTENV_CONFIG_PATH:path.join(scratch,'no-env-file'),ANTHROPIC_API_KEY:'',OPENAI_API_KEY:'',GEMINI_API_KEY:''},stdio:['ignore','pipe','pipe']});apiProcess.stdout.on('data',d=>serverLogs+=d);apiProcess.stderr.on('data',d=>serverLogs+=d);for(let i=0;i<100;i++){try{if((await fetch(base+'/health')).ok){const r=await fetch(base+'/auth/dev-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({secret:'synthetic-589'})});const j=await r.json();assert.equal(r.status,200);assert(j.sessionId);return{base,token:j.sessionId};}}catch{}await sleep(100);}throw Error('Local server failed to become ready: '+serverLogs);}
async function stopApi(){if(apiProcess&&apiProcess.exitCode===null){const p=apiProcess;await new Promise(r=>{p.once('exit',r);p.kill();});}apiProcess=null;}
async function startStatic(){const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png'};staticServer=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),f=path.resolve(root,'.'+decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));if(!f.startsWith(root+path.sep)||u.pathname.includes('/.')){res.writeHead(403).end();return;}const send=(e,b)=>{if(e){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':mime[path.extname(f)]||'application/octet-stream','Cache-Control':'no-store'}).end(b);};if(process.env.TND589_DEPLOYED){try{send(null,cp.execFileSync('git',['show',deployedRef+':'+path.relative(root,f).replace(/\\/g,'/')],{cwd:root,maxBuffer:16*1024*1024,stdio:['ignore','pipe','ignore']}));}catch(e){send(e);}}else fs.readFile(f,send);});await new Promise(r=>staticServer.listen(0,'127.0.0.1',r));return 'http://127.0.0.1:'+staticServer.address().port;}
async function newPage(site,api){const context=await browser.newContext({serviceWorkers:'block',viewport:{width:1000,height:900}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>{const req=route.request(),u=new URL(req.url());if(u.origin===site&&req.method()==='GET')return route.continue();if(u.origin===api.base&&(/^\/api\/characters(?:\/[^/]+)?$/.test(u.pathname)||u.pathname==='/api/account')){requests.push({method:req.method(),path:u.pathname});return route.continue();}blocked.push({origin:u.origin,path:u.pathname,method:req.method()});return route.abort();});await page.goto(site+'/index.html');await page.waitForFunction(()=>typeof showLibraryReplaceModal==='function'&&typeof storageAdapter!=='undefined');await page.evaluate('('+engine.makeTestWorld.toString()+')()');await page.evaluate(({base,token})=>{storageAdapter.setServer(base,token);worldState.campId='test-589';worldState.campName='Synthetic #589';window.saveAll=()=>true;window.__toasts589=[];const orig=showToast;window.showToast=function(s){__toasts589.push(String(s));orig.apply(this,arguments);};store.set('tnd_sound_v1','0');},api);return{context,page};}
async function seed(page,name){return page.evaluate(async name=>{worldState.character.name=name;worldState.character.level=1;worldState.character.appear='Original local appearance';const c=JSON.parse(JSON.stringify(worldState.character));c.level=7;c.appear='Library appearance '+name;c.inventory=['Library token'];c.sheetVer=10;const saved=await new Promise((resolve,reject)=>storageAdapter.saveCharacterToLibrary(c,(e,r)=>e?reject(Error(e)):resolve(r)));return{slug:saved.slug};},name);}
async function list(page){return page.evaluate(()=>new Promise((resolve,reject)=>storageAdapter.listCharacterLibrary((e,r)=>e?reject(Error(e)):resolve(r))));}
async function waitModal(page,id){await page.waitForFunction(id=>!!document.getElementById(id)||__toasts589.some(t=>t.includes('not in the character library')),id);assert.equal(await page.evaluate(id=>!!document.getElementById(id),id),true,'library lookup must find punctuation/accent name');}
async function click(page,id){const hit=await page.evaluate(id=>{const el=document.querySelector(id),r=el.getBoundingClientRect(),h=document.elementFromPoint(r.left+r.width/2,r.top+r.height/2);return {target:h&&h.id,toast:!!(h&&h.closest('.tnd-toast'))};},id);if(hit.toast){await page.screenshot({path:path.join(out,'toast-overlap.png')});console.log('HARNESS: sticky toast covers '+id+'; dismissing existing toasts through their handlers');await page.evaluate(()=>document.querySelectorAll('.tnd-toast').forEach(t=>t.click()));await page.waitForFunction(()=>document.querySelectorAll('.tnd-toast').length===0);}await page.locator(id).click();}
async function verifyCase(page,name,slug,n){await page.evaluate(()=>{__toasts589=[];for(const id of ['lib-update-modal','lib-replace-modal','char-overwrite-modal','char-export-opts']){const e=document.getElementById(id);if(e)e.remove();}});const saved=await seed(page,name);assert.equal(saved.slug,slug,'server stored slug matches client contract');let rows=await list(page),entry=rows.find(r=>r.slug===slug);assert(entry&&entry.name===name);const original=JSON.stringify(entry.character);
 await page.evaluate(()=>showLibraryUpdateModal(worldState.character));await waitModal(page,'lu-apply');if(n===0)await page.screenshot({path:path.join(out,'update-found.png')});await page.locator('#lu-apply').click();assert.deepEqual(await page.evaluate(()=>({name:worldState.character.name,level:worldState.character.level,appear:worldState.character.appear})),{name,level:1,appear:'Library appearance '+name},'Update found entry and changes identity only');
 await page.evaluate(()=>showLibraryReplaceModal(worldState.character));await waitModal(page,'lr-apply');if(n===0)await page.screenshot({path:path.join(out,'replace-found.png')});await page.locator('#lr-apply').click();assert.deepEqual(await page.evaluate(()=>({name:worldState.character.name,level:worldState.character.level,inventory:worldState.character.inventory})),{name,level:7,inventory:['Library token']},'Replace adopts matching library sheet');assert.equal(JSON.stringify((await list(page)).find(r=>r.slug===slug).character),original,'Update/Replace never writes upstream');
 await page.evaluate(()=>{worldState.character.level=8;_showCharExportOptions(worldState.character);});const postsBefore=requests.filter(r=>r.method==='POST'&&r.path==='/api/characters').length;await page.locator('#ceo-character-library').click();await waitModal(page,'cow-ok');assert.equal(requests.filter(r=>r.method==='POST'&&r.path==='/api/characters').length,postsBefore,'overwrite guard must not write before confirmation');if(n===0)await page.screenshot({path:path.join(out,'overwrite-confirm.png')});await page.locator('#cow-cancel').click();assert.equal(JSON.stringify((await list(page)).find(r=>r.slug===slug).character),original,'Cancel preserves exact server character');
 await page.evaluate(()=>_showCharExportOptions(worldState.character));await page.locator('#ceo-character-library').click();await waitModal(page,'cow-ok');await click(page,'#cow-ok');await page.waitForFunction(()=>!document.getElementById('char-overwrite-modal'));rows=await list(page);assert.equal(rows.filter(r=>r.slug===slug).length,1,'overwrite remains one library row');assert.equal(rows.find(r=>r.slug===slug).level,8,'confirmed overwrite updates intended row');
 await page.evaluate(slug=>new Promise((resolve,reject)=>storageAdapter.deleteCharacterFromLibrary(slug,e=>e?reject(Error(e)):resolve())),slug);assert(!(await list(page)).some(r=>r.slug===slug),'disposable character deleted');results.push({name,slug,update:true,replace:true,upstreamUnchanged:true,confirmBeforeWrite:true,cancelByteIdentical:true,confirmedOverwrite:true,deleted:true});console.log('PASS #589 complete library flow '+name+' -> '+slug);}
(async()=>{const started=new Date().toISOString();fs.mkdirSync(out,{recursive:true});try{const site=await startStatic(),api=await startApi(serverRoot,'positive.db');browser=await chromium.launch();let p=await newPage(site,api);for(const [i,v] of [['(Ammut)','ammut'],['Åsa Lindé','sa_lind'],['--Brann--','brann'],['Plain Control','plain_control']].entries())await verifyCase(p.page,v[0],v[1],i);assert.deepEqual(await list(p.page),[],'local library empty after cleanup');const version=await p.page.evaluate(()=>APP_VERSION);await browser.close();browser=null;await stopApi();
 // A runtime-only counterfactual in a disposable source copy; no checkout byte is changed.
 const mutant=path.join(scratch,'old-server');fs.mkdirSync(mutant);const tracked=cp.execFileSync('git',['ls-files'],{cwd:serverRoot,encoding:'utf8'}).trim().split(/\r?\n/);for(const rel of tracked){const source=path.join(serverRoot,rel);if(!fs.existsSync(source)||!fs.statSync(source).isFile())continue;const target=path.join(mutant,rel);fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(source,target);}fs.symlinkSync(path.join(serverRoot,'node_modules'),path.join(mutant,'node_modules'),'junction');const slugPath=path.join(mutant,'library-slug.cjs'),src=fs.readFileSync(slugPath,'utf8'),needle='.replace(/^_|_$/g,"");}';assert.equal(src.split(needle).length,2,'unique old-slug mutation anchor');fs.writeFileSync(slugPath,src.replace(needle,'.replace(/^_|_$/,"");}'));
 const oldApi=await startApi(mutant,'negative.db');browser=await chromium.launch();p=await newPage(site,oldApi);const stored=await seed(p.page,'(Ammut)');assert.equal(stored.slug,'ammut_');await p.page.evaluate(()=>showLibraryUpdateModal(worldState.character));let caught='';try{await waitModal(p.page,'lu-apply');}catch(e){caught=e.message;}assert(caught.includes('library lookup must find punctuation/accent name'),'old server defect must fail actual UI lookup assertion');const miss=await p.page.evaluate(()=>__toasts589.some(t=>t.includes('not in the character library')));assert(miss);await browser.close();browser=null;await stopApi();assert.deepEqual(errors,[],'no browser page errors');const receipt={started,ended:new Date().toISOString(),version,servedClientRef:process.env.TND589_DEPLOYED?deployedRef:'working tree',clientCommit:cp.execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),serverCommit:cp.execFileSync('git',['rev-parse','HEAD'],{cwd:serverRoot,encoding:'utf8'}).trim(),cases:results,negativeControl:{oldStoredSlug:stored.slug,failedAssertion:'library lookup must find punctuation/accent name',caught:true},requests,blocked,errors,scope:'Actual browser UI and storageAdapter against actual local server HTTP/auth/SQLite; dedicated dev_local and scratch databases. No production authenticated operation. Public deployment code parity is separate.'};fs.writeFileSync(path.join(out,'browser-receipt.json'),JSON.stringify(receipt,null,2)+'\n');console.log('PASS #589 old-server mutation caught by real lookup; 4 complete cases');}finally{if(browser)await browser.close();await stopApi();if(staticServer)await new Promise(r=>staticServer.close(r));const resolved=path.resolve(scratch),tmp=path.resolve(os.tmpdir())+path.sep;if(!resolved.startsWith(tmp)||!path.basename(resolved).startsWith('tnd-589-acceptance-'))throw Error('Unexpected scratch cleanup target');fs.rmSync(resolved,{recursive:true,force:true});}})().catch(e=>{console.error('FAIL #589 acceptance: '+e.stack);process.exitCode=1;});
