// Objective acceptance evidence; synthetic worlds only. Run from any cwd.
// node audits/verification-530-531-2026-10-08/acceptance.cjs
const path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'../..'),L=require(path.join(root,'dev/load-engine.js'));
L.loadEngine();for(const n of ['showToast','syncUI','saveAll','updateInvPanel','addMsg'])global[n]=()=>({});
const QUEEN='Queen Underbough',PRINCESS='Wilhelmina Underbough';let cases=[],warnings=[];
function quiet(f){const w=console.warn,i=console.info;console.warn=(...a)=>warnings.push(a.join(' '));console.info=()=>{};try{return f();}finally{console.warn=w;console.info=i;}}
function person(name){memory.npcs[name]={attitude:'',knowledge:['identity:'+name],events:[],aliases:[],pronouns:'she/her'};worldState.npcs.push({name,status:'present',rel:'neutral',pronouns:'she/her',met:1,partyMember:false,aliases:[]});}
function setup(refs){L.makeTestWorld();worldState.npcs=[];memory.npcs={};memory.map.nodes.Ashfen={firstVisit:1,visits:1,description:null,parent:null,npcs:[],items:[],size:null,travelMins:null};delete worldState.kind;worldState.turn=85;person(PRINCESS);if(refs)sceneRefsEnsure();}
function apply(t){const r=quiet(()=>applyMuts(t));assert.deepStrictEqual(r.errors||[],[],'handler errors '+JSON.stringify(r.errors));return r;}
function alive(){assert.ok(!wsNpcByName(PRINCESS).dead&&!memory.npcs[PRINCESS].dead,'princess killed');}
function provisional(){apply('[NPC:'+QUEEN+'|furious|hostile] [NPC_NOTE:'+QUEEN+'|wedding-objection]');assert.ok(memory.npcs[QUEEN].provisional,'fixture must open a title question');}
function run(name,f){warnings=[];try{const result=f();cases.push({name,ok:true,result,warnings});console.log('PASS '+name);}catch(e){cases.push({name,ok:false,error:e.stack,warnings});console.error('FAIL '+name+' — '+e.message);}}
for(const refs of [false,true]){
 run('#530 ANOTHER lands and stays settled; refs='+refs,()=>{setup(refs);provisional();const before=JSON.stringify(memory.npcs[PRINCESS]);worldState.turn=86;const r=apply('[MERGE:npc|Isolde Underbough|'+QUEEN+']');assert.ok(memory.npcs['Isolde Underbough']&&!memory.npcs['Isolde Underbough'].provisional);assert.ok(!memory.npcs[QUEEN]);assert.strictEqual(resolveNpcName(QUEEN),'Isolde Underbough');assert.strictEqual(JSON.stringify(memory.npcs[PRINCESS]),before);assert.ok(memory.npcs['Isolde Underbough'].events.some(e=>e.note==='wedding-objection'));worldState.turn=150;assert.strictEqual(buildProvisionalNudge(),'');return {names:Object.keys(memory.npcs),muts:r.muts};});
 run('#530 OTHER uses known-key confirmation; refs='+refs,()=>{setup(refs);person('Isolde Marsh');provisional();worldState.turn=86;apply('[NPC_MERGE:Isolde Marsh|'+QUEEN+']');if(refs){assert.ok(memory.npcs[QUEEN].provisional);assert.ok(worldState.pendingMergeHints.some(x=>x.canonical==='Isolde Marsh'&&x.duplicate===QUEEN));worldState.turn=87;const note=buildMergeConfirmNudge();assert.ok(note.includes('[NPC_MERGE:Isolde Marsh|'+QUEEN+']'));worldState.turn=88;apply('[NPC_MERGE:Isolde Marsh|'+QUEEN+']');}assert.ok(!memory.npcs[QUEEN]);assert.strictEqual(resolveNpcName(QUEEN),'Isolde Marsh');alive();return {names:Object.keys(memory.npcs),question:buildProvisionalNudge()};});
 run('#531 reported death actually kills the titled queen; refs='+refs,()=>{setup(refs);const r=apply('[NPC_DEATH_REPORTED:'+QUEEN+'|fever|Elderwood]');alive();assert.ok(wsNpcByName(QUEEN).dead&&memory.npcs[QUEEN].dead,'queen must actually die, not an unrelated refusal');assert.ok(memory.npcs[QUEEN].provisional);return {princessDead:!!wsNpcByName(PRINCESS).dead,queenDead:!!wsNpcByName(QUEEN).dead,muts:r.muts};});
 run('#531 combat presence belongs to title, never relative; refs='+refs,()=>{setup(refs);provisional();worldState.turn=86;const raw='[COMBAT_START:'+QUEEN+'|10|10|1|1d4|low]',r=apply(raw);alive();assert.ok(worldState.combat&&worldState.combat.foes.some(x=>x.name===QUEEN),'positive control: queen foe exists');assert.ok(memory.npcs[PRINCESS].lastSeenTurn==null||memory.npcs[PRINCESS].lastSeenTurn<86,'princess presence stamped');assert.strictEqual(memory.npcs[QUEEN].lastSeenTurn,86,'positive control: queen present');return {foes:worldState.combat.foes.map(x=>x.name),princessSeen:memory.npcs[PRINCESS].lastSeenTurn||null,queenSeen:memory.npcs[QUEEN].lastSeenTurn,muts:r.muts};});
}
for(const reveal of [false,true])for(const subject of [QUEEN,'-'])run('#531 valid scene death with '+(reveal?'reveal':'binding')+' and subject='+subject,()=>{setup(true);provisional();apply(reveal?'[SCENE_REF:queen|?] [SCENE_REVEAL:queen|'+QUEEN+']':'[SCENE_REF:queen|'+QUEEN+']');assert.strictEqual(_sceneRefActor('queen').actor.entity,QUEEN);worldState.turn=86;const r=apply('[CANON_TXN_BEGIN:accept531|npc-death|'+subject+'|queen|-][SCENE_DEATH:queen][CANON_TXN_END:accept531]');alive();assert.ok(wsNpcByName(QUEEN).dead&&memory.npcs[QUEEN].dead,'positive control: valid envelope must kill queen');return {queenDead:!!wsNpcByName(QUEEN).dead,princessDead:!!wsNpcByName(PRINCESS).dead,muts:r.muts,txns:worldState.canonTxns};});
run('#531 same-turn handle cannot authorize a death (negative control)',()=>{setup(true);provisional();const r=apply('[SCENE_REF:queen|'+QUEEN+'][CANON_TXN_BEGIN:too-early|npc-death|'+QUEEN+'|queen|-][SCENE_DEATH:queen][CANON_TXN_END:too-early]');alive();assert.ok(!wsNpcByName(QUEEN).dead);return {queenDead:false,muts:r.muts};});
run('#530 repeated settled keep answer has bounded state',()=>{setup(true);provisional();worldState.turn=86;apply('[MERGE:npc|'+QUEEN+'|'+QUEEN+']');const base={keys:Object.keys(memory.npcs),archive:(memory.archive.identityMerges||[]).length};for(let i=0;i<100;i++){worldState.turn++;apply('[MERGE:npc|'+QUEEN+'|'+QUEEN+']');assert.strictEqual(buildProvisionalNudge(),'');}assert.deepStrictEqual(Object.keys(memory.npcs),base.keys);assert.strictEqual((memory.archive.identityMerges||[]).length,base.archive);return {iterations:100,keys:base.keys,archiveEntries:base.archive};});
console.log(JSON.stringify({appVersion:APP_VERSION,cases,passed:cases.filter(x=>x.ok).length,failed:cases.filter(x=>!x.ok).length},null,2));
process.exitCode=cases.some(x=>!x.ok)?1:0;
