// dev/storage-keys.js — the storage-key census (#523): every `tnd_…` literal in the root .js files, with the file that
// owns it and, when the literal is a prefix (`tnd_store_rescue_v1_`), the mark. Writes the table between the markers in
// DOC/contracts/sync.md with --write; without it, prints the table and exits 1 when the doc's table is stale (run-tests
// calls it that way). The convention it documents: the key's version suffix is per key, not global.
//   node dev/storage-keys.js            check (exit 1 when sync.md's table is stale)
//   node dev/storage-keys.js --write    regenerate the table in sync.md
var fs = require("fs"), path = require("path"), cp = require("child_process"), root = path.resolve(__dirname, "..");
var BEGIN = "<!-- storage-keys:begin (generated by dev/storage-keys.js — do not edit by hand) -->", END = "<!-- storage-keys:end -->";
function census() {
  var files = cp.execSync("git ls-files", { cwd: root }).toString("utf8").split("\n").filter(function (f) { return /^[^/]+\.js$/.test(f); }), keys = {};
  files.forEach(function (f) {
    var src = fs.readFileSync(path.join(root, f), "utf8"), re = /["'](tnd_[A-Za-z0-9_]*)["']/g, m;
    while ((m = re.exec(src))) { var k = m[1]; if (!keys[k]) keys[k] = {}; keys[k][f] = (keys[k][f] || 0) + 1; }
  });
  return Object.keys(keys).sort().map(function (k) {
    var owners = Object.keys(keys[k]).sort(), suffix = (k.match(/_v(\d+)_?$/) || [])[1] || null, prefix = /_$/.test(k);
    return { key: k, owners: owners, suffix: suffix, prefix: prefix };
  });
}
function table(rows) {
  var byV = {}; rows.forEach(function (r) { var v = r.suffix ? "_v" + r.suffix : "(none)"; byV[v] = (byV[v] || 0) + 1; });
  var out = [BEGIN, "", "**" + rows.length + " `tnd_…` literals in the root .js files** — suffix census: " + Object.keys(byV).sort().map(function (v) { return v + " ×" + byV[v]; }).join(", ") + ". A row ending in `_` is a PREFIX (the full key carries a campaign id or a rescue stamp after it).", "", "| Key | Where | Version suffix |", "|---|---|---|"];
  rows.forEach(function (r) { out.push("| `" + r.key + "`" + (r.prefix ? " (prefix)" : "") + " | " + r.owners.join(", ") + " | " + (r.suffix ? "`_v" + r.suffix + "`" : "—") + " |"); });
  out.push("", END);
  return out.join("\n");
}
var rows = census(), fresh = table(rows), doc = path.join(root, "DOC/contracts/sync.md"), s = fs.readFileSync(doc, "utf8"), a = s.indexOf(BEGIN), b = s.indexOf(END);
if (process.argv.indexOf("--write") >= 0) {
  if (a < 0 || b < 0) throw new Error("sync.md has no storage-keys markers");
  fs.writeFileSync(doc, s.slice(0, a) + fresh + s.slice(b + END.length));
  console.log("storage-keys: " + rows.length + " keys written to DOC/contracts/sync.md");
} else {
  var cur = (a >= 0 && b >= 0) ? s.slice(a, b + END.length) : null;
  if (cur === fresh) { console.log("STORAGE KEYS OK — " + rows.length + " keys, DOC/contracts/sync.md's table matches the tree"); }
  else { console.error("STORAGE KEYS STALE — DOC/contracts/sync.md's table does not match the tree (" + rows.length + " keys); run: node dev/storage-keys.js --write"); process.exit(1); }
}
