const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../..'),engine=require(root+'/dev/load-engine.js');engine.loadEngine();
for(const n of ['syncUI','saveAll','saveCore','saveMem','updateCampMeta','updateInvPanel','updateAbPanel','updateSpPanel','showToast'])global[n]=()=>{};global.addMsg=()=>({appendChild(){},remove(){},style:{}});
const results=[];function check(rows,name,fn){try{const x=fn();results.push({rows,name,...x});}catch(e){results.push({rows,name,result:'ERROR',error:e.stack});}}
function village(){engine.makeTestWorld({kind:'village',campId:'astra-original',clock:{min:12*1440+600}});worldState.character.name='Silas';worldState.world.location='The Village';memory.map={nodes:{'The Village':{firstVisit:1,visits:1,parent:null,npcs:[],items:[]}},edges:[]};importVillageResidents([{name:'Frizwick',gender:'F',cls:'Rogue',inventory:[],coreMemories:[]}]);villageHouseEnsure('Silas',null);worldState.world.sublocation="Silas's house";worldState.stashMoves=[];return memory.map.nodes[villageHouseKey('Silas')];}
function companion(inv=[]){worldState.npcs.push({name:'Bram',status:'ally',rel:'companion',partyMember:true,charSheet:{name:'Bram',inventory:inv}});memory.npcs.Bram={knowledge:[],events:[],aliases:[],partyMember:true};}
function shop(){village();const key='The Village|the trading post';worldState.world.sublocation='the trading post';memory.map.nodes[key]={firstVisit:1,visits:1,parent:'The Village',npcs:[],items:[],shop:true,wares:[],wanted:[]};memory.npcs.Frizwick.lastSeenAt=key;return memory.map.nodes[key];}
function verdict(ok,details){return {result:ok?'PASS':'FAIL',...details};}
check([511,560],'trade block arrives before wares are filed; footer preserves sublocation',()=>{const old=shop(),next='The Village|The Iron Cauldron';memory.map.nodes[next]={parent:'The Village',items:[],npcs:[],wares:[],shop:true};const r=applyMuts('[WARES:Brass comb|3 gp|Frizwick][SUBLOCATION:The Iron Cauldron][LOCATION:The Village]');return verdict(!old.wares.some(w=>w.item==='Brass comb')&&memory.map.nodes[next].wares.some(w=>w.item==='Brass comb')&&worldState.world.sublocation==='The Iron Cauldron',{oldWares:old.wares,newWares:memory.map.nodes[next].wares,world:worldState.world,muts:r.muts});});
check([512,560],'description before move files on town',()=>{village();worldState.world.sublocation=null;const r=applyMuts('[LOCATION_DESC:Mud streets and smoke.][SUBLOCATION:The Silk and Steam Bathhouse]');return verdict(memory.map.nodes['The Village'].description==='Mud streets and smoke.'&&!memory.map.nodes['The Village|The Silk and Steam Bathhouse'].description,{town:memory.map.nodes['The Village'].description,bathhouse:memory.map.nodes['The Village|The Silk and Steam Bathhouse'],muts:r.muts});});
check([574],'stow, hero swap, refuse undo; swap back and restore',()=>{const h=village();worldState.character.inventory=['Sihedron ritual spear'];applyMuts('[ITEM_LOST:Sihedron ritual spear][LOCATION_ITEM:Sihedron ritual spear|placed]');assert(swapPlayerCharacter('Frizwick').ok);const refused=undoLastItemMove();assert(swapPlayerCharacter('Silas').ok);const restored=undoLastItemMove();return verdict(!refused.ok&&restored.ok&&worldState.character.inventory.includes('Sihedron ritual spear'),{refused,restored,chest:h.items,inventory:worldState.character.inventory});});
check([574],'unpaired placement undo must not claim an item was returned',()=>{const h=village();worldState.character.inventory=[];applyMuts('[LOCATION_ITEM:Sihedron ritual spear|placed]');const undo=undoLastItemMove();return verdict(undo.ok&&undo.pack===false&&!/back with you/.test(undo.said)&&/nobody.s pack held it/.test(undo.said),{undo,hero:worldState.character.inventory,chest:h.items});});
check([575,576],'empty companion reverse transfer conserves zero torches',()=>{engine.makeTestWorld();worldState.character.inventory=[];companion();const r=applyMuts('[COMPANION_ITEM_LOST:Bram|Torch x3][ITEM_GAINED:Torch x3]');return verdict(worldState.character.inventory.length===0,{hero:worldState.character.inventory,companion:findCompanionChar('Bram').inventory,muts:r.muts});});
check([575,576],'gift from pack leaves identical chest copy alone',()=>{const h=village();worldState.character.inventory=['Healing potion'];h.items=[{name:'Healing potion',placed:1,taken:false,qty:1,by:'Silas',min:0}];companion();const r=applyMuts('[ITEM_LOST:Healing potion][COMPANION_ITEM_GAINED:Bram|Healing potion]');return verdict(!h.items[0].taken&&h.items[0].qty===1&&findCompanionChar('Bram').inventory.includes('Healing potion'),{hero:worldState.character.inventory,companion:findCompanionChar('Bram').inventory,chest:h.items,muts:r.muts});});
check([575,576],'independent loot survives missing companion throw',()=>{engine.makeTestWorld();worldState.character.inventory=[];companion();const r=applyMuts('You loot a dagger. [ITEM_GAINED:Dagger] Bram throws his dagger. [COMPANION_ITEM_LOST:Bram|Dagger]');return verdict(worldState.character.inventory.includes('Dagger'),{hero:worldState.character.inventory,muts:r.muts});});
check([577,591],'discard without coin keeps wanted offer',()=>{const n=shop();n.wanted=[{item:'Warded ring',offer:'40 gp',by:'Frizwick',t:1,min:clockNow()}];worldState.character.inventory=['Warded ring'];const r=applyMuts('You discard the ring. [ITEM_LOST:Warded ring]');return verdict(n.wanted.length===1&&!r.muts.some(m=>/Want met/.test(m)),{wanted:n.wanted,muts:r.muts});});
check([577,591],'unrelated coin receipt must not make a discarded ring a sale',()=>{const n=shop();n.wanted=[{item:'Warded ring',offer:'40 gp',by:'Frizwick',t:1,min:clockNow()}];worldState.character.inventory=['Warded ring'];const r=applyMuts('Frizwick gives you one copper in change. [SAY:Frizwick]Your change.[/SAY][GOLD:+1 cp] You throw the broken ring into the fire. [ITEM_LOST:Warded ring]');return verdict(n.wanted.length===1,{coin:worldState.character.coin,wanted:n.wanted,muts:r.muts});});
check([577],'one wanted offer pays once across three decorated names',()=>{const n=shop();n.wanted=[{item:'Warded ring',offer:'40 gp',by:'Frizwick',t:1,min:clockNow()}];worldState.character.inventory=['Warded ring','Warded ring — taken from the crypt','Warded ring (cracked)'];const cat=shopTradeCatalog(),marks={};cat.sell.forEach(s=>marks[s.name.toLowerCase()]=1);const before=worldState.character.coin,r=shopTradeApply({sell:marks});return verdict(worldState.character.coin-before<=4000,{deltaCp:worldState.character.coin-before,trade:r,inventory:worldState.character.inventory});});
check([578],'plural coin units debit copper exactly',()=>{engine.makeTestWorld();const before=worldState.character.coin,r=applyMuts('[GOLD:-3 coppers]');return verdict(worldState.character.coin===before-3,{before,after:worldState.character.coin,parsed:parseCoin('3 coppers'),muts:r.muts});});
check([578],'mixed sale and buy preserve fractional gold value',()=>{const p=shopTradePlan({coin:1000,sell:[{name:'Carved whistle',qty:2,sellCp:30}],buy:[{name:'Rope',cp:100,per:1}]},{sell:{'carved whistle':2},buy:{rope:1}});return verdict(p.ok&&p.netCp===40&&p.coinAfter===960,{plan:p});});
check([578],'compound and bundle price forms are accurate or refused',()=>{const inputs=[['20 for 1 gp',100,20],['5 gp per dozen',500,12],['1 gp 5 sp',150,1]];const prices=inputs.map(([input,total,per])=>({input,expected:{total,per},parsed:parseCoin(input)}));return verdict(prices.every(p=>p.parsed&&p.parsed.cp===p.expected.total&&p.parsed.per===p.expected.per),{prices});});
check([578,575],'counted ware purchased as twenty yields twenty arrows',()=>{shop();worldState.character.inventory=[];applyMuts('[WARES:Arrow x20|1 gp]');const cat=shopTradeCatalog(),r=shopTradeApply({buy:{'arrow x20':20}});return verdict(worldState.character.inventory.join()==='Arrow x20',{buy:cat.buy,trade:r,hero:worldState.character.inventory});});
check([581],'exported stash mark prevents double replay after campaign id changes',()=>{village();worldState.heroLibraryAt=1000;worldState.character.inventory=['Blasting charge x5'];stashTradeApply({stow:{'blasting charge':1}});const lib=portableSheet(worldState.character);const before=lib.inventory.slice(),marks=JSON.parse(JSON.stringify(lib.stashMarks));worldState.campId='astra-imported';const r=villageRefreshFromLibrary([{character:lib,updatedAt:Date.now()+5000}]);return verdict(worldState.character.inventory.join()==='Blasting charge x4',{before,after:worldState.character.inventory,marks,replay:r});});
fs.writeFileSync(path.join(__dirname,'independent-results.json'),JSON.stringify(results,null,2));for(const r of results)console.log(r.result+' #'+r.rows.join(',')+' '+r.name);if(results.some(r=>r.result==='ERROR'))process.exitCode=1;
