const fs=require('fs'),p=require('path'),vm=require('vm'),root='C:/Projects/traffic-and-dragons';const g=require(root+'/dev/class-guards.js'),L=require(root+'/dev/load-engine.js');L.loadEngine();global.showToast=()=>{};global.syncUI=()=>{};global.saveAll=()=>{};
const run=fs.readFileSync(root+'/dev/run-tests.js','utf8'),f=g.functionsOf(run).find(f=>f.name==='_frozenFailureDetail');let diagnostics=vm.runInNewContext('('+run.slice(run.lastIndexOf('function ',f.open),f.close+1)+')',{__dirname:root+'/dev',_frozenGolden:{failureDiff:(...a)=>'DIFF '+a[1]},_CT_TAGS:{source:'x'},buildStateTagsDoc:()=>''});
const names=['derived cleanTxt strip regex is byte-identical to the frozen literal','derived STATE TAGS doc block frozen (the money-tested prompt text, byte-level)'];let titleCases=names.map(name=>({title:name,matched:diagnostics(name),renamed:diagnostics(name+' renamed')}));
let replays=[];for(const ver of ['v1238','v1258','v1271','v1276']){const file='dev/corpus_playtest_'+ver+'.json.endstate.json',o=JSON.parse(fs.readFileSync(root+'/'+file,'utf8')),arr=[];function walk(x,at){if(!x||typeof x!=='object')return;for(const k of Object.keys(x)){if(k==='inventory'||k==='worn')arr.push({path:at+'.'+k,value:x[k]});walk(x[k],at+'.'+k);}}walk(o,'root');replays.push({file,fields:arr});}
L.makeTestWorld();let calls=0,orig=relationshipMigrateSheet;global.relationshipMigrateSheet=function(sheet,...args){calls++;if(sheet===worldState.character)sheet.inventory=['HEAL_SENTINEL'];return orig(sheet,...args);};let prompt=buildSysPrompt();global.relationshipMigrateSheet=orig;
let healOrder={calls,inventoryLine:prompt.volatile.split('\n').find(s=>s.startsWith('Inventory:'))};
const oldInv=['Axe','Shield','Torch x3'],oldWorn=['Shield','Axe'],expected='Inventory: Axe, Shield, Torch x3\nEquipped: Axe, Shield';function projectionCheck(proposed){return proposed===expected;}
let projection=[{name:'allowed equipped pack-order',observed:projectionCheck(expected),expected:true},{name:'drop equipped',observed:projectionCheck('Inventory: Axe, Shield, Torch x3\nEquipped: '),expected:false},{name:'reorder inventory',observed:projectionCheck('Inventory: Torch x3, Shield, Axe\nEquipped: Axe, Shield'),expected:false},{name:'unexpected other byte',observed:projectionCheck(expected+' '),expected:false}];
let dictionaries=Object.create(null);for(const name of ['__proto__','constructor','toString']){let d=keyedDict();d[name]={qty:1};dictionaries[name]={nullPrototype:Object.getPrototypeOf(d)===null,own:Object.prototype.hasOwnProperty.call(d,name),json:JSON.stringify(d)};}
let base={name:'Torch',qty:3,equipped:false},live=[base],sim=live.slice();sim[0].qty--;let shallow={kind:'reference illustration only; invRemove not implemented',liveQtyAfterCopyMutation:live[0].qty,simSharesRow:sim[0]===live[0],sourceSites:['game.js:380','tag_table.js:540','game.js:4394']};
const result={titleCases,replays,healOrder,projectionChecker:'scratch model only; §8.2 gate 8 not implemented',projection,dictionaries,shallow};fs.writeFileSync(p.join(__dirname,'infrastructure.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
