const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../..'),out=path.join(os.tmpdir(),'tnd-known-issues');fs.mkdirSync(out,{recursive:true});
const engine=require(root+'/dev/load-engine.js');engine.loadEngine('game.js');
for(const name of ['syncUI','saveAll','saveCore','saveMem','updateCampMeta','updateInvPanel','updateAbPanel','updateSpPanel','showToast'])global[name]=()=>{};
global.addMsg=()=>({appendChild(){},remove(){},style:{}});
const results=[];
function probe(id,name,fn){try{results.push({id,name,...fn()});}catch(e){results.push({id,name,result:'ERROR',error:e.stack});}}
function village(){engine.makeTestWorld({kind:'village',campId:'verification-only',clock:{min:12*1440+10*60}});worldState.character.name='Silas';worldState.world.location='The Village';worldState.world.sublocation=null;memory.map={nodes:{'The Village':{firstVisit:1,visits:1,parent:null,npcs:[],items:[]}},edges:[]};importVillageResidents([{name:'Frizwick',gender:'F',cls:'Rogue',inventory:[],coreMemories:[]}]);villageHouseEnsure('Silas',null);worldState.world.sublocation="Silas's house";worldState.stashMoves=[];return memory.map.nodes[villageHouseKey('Silas')];}
probe(519,'stow, swap hero, undo',()=>{const house=village();worldState.character.inventory=['Sihedron ritual spear'];applyMuts('[ITEM_LOST:Sihedron ritual spear][LOCATION_ITEM:Sihedron ritual spear|placed]');const swap=swapPlayerCharacter('Frizwick');assert(swap.ok);const undo=undoLastItemMove();const old=wsNpcByName('Silas');const inventories=[worldState.character.inventory,old&&old.charSheet&&old.charSheet.inventory];const left=house.items.filter(i=>!i.taken&&i.qty>0);return {result:undo.ok&&!JSON.stringify(inventories).includes('Sihedron')&&!left.some(i=>/Sihedron/.test(i.name))?'STILL BROKEN':'inspect',undo,inventories,chest:left,turn:worldState.turn};});
probe(518,'one torch pays for gift of three',()=>{engine.makeTestWorld();worldState.character.inventory=['Torch'];worldState.npcs.push({name:'Bram',status:'ally',rel:'companion',partyMember:true,charSheet:{name:'Bram',inventory:[]}});const r=applyMuts('[ITEM_LOST:Torch x3][COMPANION_ITEM_GAINED:Bram|Torch x3]');const inventory=findCompanionChar('Bram').inventory;return {result:inventory.join()==='Torch x3'?'STILL BROKEN':'inspect',inventory,muts:r.muts,turn:worldState.turn};});
probe(511,'same-world footer after sublocation',()=>{village();applyMuts('[SUBLOCATION:the tavern][LOCATION:The Village]');return {result:worldState.world.sublocation===null?'STILL BROKEN':'inspect',world:worldState.world,turn:worldState.turn};});
probe(517,'sale bundled with purchase',()=>{const cat={gold:10,sell:[{name:'Carved whistle',qty:2,sellGp:.3}],buy:[{name:'Rope',buyGp:1,per:1}]};const combined=shopTradePlan(cat,{sell:{'carved whistle':2},buy:{rope:1}}),buy=shopTradePlan(cat,{buy:{rope:1}});return {result:combined.netGp===buy.netGp?'STILL BROKEN':'inspect',combined,buy,turn:5};});
probe(517,'plural copper units',()=>{engine.makeTestWorld();const before=worldState.character.gold;const r=applyMuts('[GOLD:-3 coppers]');return {result:worldState.character.gold===before-3?'STILL BROKEN':'inspect',before,after:worldState.character.gold,muts:r.muts,turn:worldState.turn};});
probe(527,'lead 26: wanted item consumed without sale',()=>{village();worldState.world.sublocation='the trading post';const key='The Village|the trading post';memory.map.nodes[key]={parent:'The Village',firstVisit:1,visits:1,npcs:[],items:[],shop:true,wares:[],wanted:[{item:'Carved whistle',offer:'3 gp',by:'Frizwick',t:1,min:clockNow()}]};memory.npcs.Frizwick.lastSeenAt=key;worldState.character.inventory=['Carved whistle'];const g=worldState.character.gold;const r=applyMuts('You throw the whistle away. [ITEM_LOST:Carved whistle]');return {result:nodeWantedLive(memory.map.nodes[key]).length===0?'STILL BROKEN':'inspect',goldChange:worldState.character.gold-g,wanted:memory.map.nodes[key].wanted,muts:r.muts,turn:worldState.turn};});
probe(503,'Princess t89 read-only save; replay King tags with separate princess fixture',()=>{const f=root+'/Campaigns/The_Princess_Is_Not_In_Danger__Ammut_/saves/The_Princess_Is_Not_In_Danger__Ammut__Ammut_t89.tnd';const raw=JSON.parse(fs.readFileSync(f,'utf8'));worldState=inflateWorldStateSnapshot(raw.worldState);memory=raw.memory;sessionLog=raw.sessionLog||[];const p=wsNpcByName('Wilhelmina Underbough');assert(p);p.pronouns='she/her';memory.npcs[p.name].pronouns='she/her';worldState.npcs=worldState.npcs.filter(n=>n.name!=='King Underbough');delete memory.npcs['King Underbough'];const r=applyMuts('[NPC:King Underbough|hungover, asleep|acquaintance][NPC_PRONOUN:King Underbough|he/him]');assert.equal(wsNpcByName('Wilhelmina Underbough').pronouns,'she/her');assert.equal(wsNpcByName('King Underbough').pronouns,'he/him');return {result:'PASS',fixture:path.relative(root,f),note:'in-memory reconstruction of pre-fusion pronouns; historical damage is not repaired',muts:r.muts};});
probe(563,'Village t218 return note and history stability',()=>{const f=root+'/Campaigns/The_Village__Ammut_/saves/The_Village__Ammut__Ammut_t218.tnd';const raw=JSON.parse(fs.readFileSync(f,'utf8'));worldState=inflateWorldStateSnapshot(raw.worldState);memory=raw.memory;sessionLog=raw.sessionLog||[];const before=JSON.stringify(memory.map);const fact=villageReturnFact();worldState.returnPing={awayMs:3*3600000,fact,change:'it is night now',turn:worldState.turn};const note=buildReturnNote();assert(!/soul.tax lien/i.test(note));assert(!/LOCATION_STATE|FILE it|so it persists/.test(note));assert.equal(JSON.stringify(memory.map),before);assert(/never through a window/i.test(note));return {result:'PASS',also:[564],fixture:path.relative(root,f),fact,note};});
fs.writeFileSync(path.join(out,'probes.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
