const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../..'),engine=require(root+'/dev/load-engine.js');engine.loadEngine('game.js');
for(const n of ['syncUI','saveAll','saveCore','saveMem','updateCampMeta','updateInvPanel','updateAbPanel','updateSpPanel','showToast'])global[n]=()=>{};global.addMsg=()=>({appendChild(){},remove(){},style:{}});
const results=[];function check(row,caseName,fn){try{results.push({row,caseName,turn:5,...fn()});}catch(e){results.push({row,caseName,result:'PROBE ERROR',error:e.stack});}}
function village(){engine.makeTestWorld({kind:'village',campId:'quartet-verification',clock:{min:12*1440+10*60}});worldState.character.name='Silas';worldState.world.location='The Village';memory.map={nodes:{'The Village':{firstVisit:1,visits:1,parent:null,npcs:[],items:[]}},edges:[]};importVillageResidents([{name:'Frizwick',gender:'F',cls:'Rogue',inventory:[],coreMemories:[]}]);villageHouseEnsure('Silas',null);worldState.world.sublocation="Silas's house";worldState.stashMoves=[];return memory.map.nodes[villageHouseKey('Silas')];}
function companion(inv=[]){worldState.npcs.push({name:'Bram',status:'ally',rel:'companion',partyMember:true,charSheet:{name:'Bram',inventory:inv}});memory.npcs.Bram={knowledge:[],events:[],aliases:[],partyMember:true};}
function shop(){village();const key='The Village|the trading post';worldState.world.sublocation='the trading post';memory.map.nodes[key]={firstVisit:1,visits:1,parent:'The Village',npcs:[],items:[],shop:true,wares:[],wanted:[]};memory.npcs.Frizwick.lastSeenAt=key;return memory.map.nodes[key];}
check(511,'fixed: same-world footer',()=>{village();const r=applyMuts('[SUBLOCATION:the tavern][LOCATION:The Village]');assert.equal(worldState.world.sublocation,'the tavern');return {result:'FIXED',sublocation:worldState.world.sublocation,muts:r.muts};});
check(517,'fixed: mixed sale and purchase',()=>{const p=shopTradePlan({gold:10,sell:[{name:'Carved whistle',qty:2,sellGp:.3}],buy:[{name:'Rope',buyGp:1,per:1}]},{sell:{'carved whistle':2},buy:{rope:1}});assert(p.ok);assert.equal(p.netGp,0);return {result:'FIXED',plan:p};});
check(517,'fixed: coppers parsed as cp and refused, not charged as gp',()=>{engine.makeTestWorld();const before=worldState.character.gold,r=applyMuts('[GOLD:-3 coppers]');assert.equal(parseCoin('3 coppers').unit,'cp');assert.equal(worldState.character.gold,before);assert(r.muts.some(m=>/Gold refused.*cp/.test(m)));return {result:'FIXED',before,after:worldState.character.gold,muts:r.muts};});
check(518,'fixed: one-unit gift cap; two-unit boundary',()=>{const observed=[];for(const n of [1,2,3]){engine.makeTestWorld();worldState.character.inventory=[n===1?'Torch':'Torch x'+n];companion();const r=applyMuts('[ITEM_LOST:Torch x3][COMPANION_ITEM_GAINED:Bram|Torch x3]');const inv=findCompanionChar('Bram').inventory;assert.equal(inv.join(),n===1?'Torch':'Torch x'+n);observed.push({held:n,received:inv,muts:r.muts});}return {result:'FIXED',observed};});
check(519,'fixed: hero-swap undo preserves spear; returning hero can undo',()=>{const house=village();worldState.character.inventory=['Sihedron ritual spear'];applyMuts('[ITEM_LOST:Sihedron ritual spear][LOCATION_ITEM:Sihedron ritual spear|placed]');assert(swapPlayerCharacter('Frizwick').ok);const blocked=undoLastItemMove();assert.equal(blocked.ok,false);assert.match(blocked.reason,/Silas is no longer/);assert(house.items.some(i=>i.name==='Sihedron ritual spear'&&!i.taken&&i.qty===1));assert(swapPlayerCharacter('Silas').ok);const retry=undoLastItemMove();assert(retry.ok);assert(worldState.character.inventory.includes('Sihedron ritual spear'));return {result:'FIXED',blocked,retry,inventory:worldState.character.inventory};});
check(511,'remaining: trade tag block before arrival',()=>{const old=shop(),next='The Village|The Iron Cauldron';memory.map.nodes[next]={firstVisit:1,visits:1,parent:'The Village',npcs:[],items:[],shop:true,wares:[]};const r=applyMuts('[WARES:Brass comb|3 gp|Frizwick][SUBLOCATION:The Iron Cauldron]');return {result:old.wares.some(w=>w.item==='Brass comb')?'STILL BROKEN':'INSPECT',oldShopWares:old.wares,newShopWares:memory.map.nodes[next].wares,muts:r.muts};});
check(518,'remaining: empty companion reverse transfer creates units',()=>{engine.makeTestWorld();worldState.character.inventory=[];companion();const r=applyMuts('[COMPANION_ITEM_LOST:Bram|Torch x3][ITEM_GAINED:Torch x3]');return {result:worldState.character.inventory.length?'STILL BROKEN':'NOT REPRODUCED',hero:worldState.character.inventory,companion:findCompanionChar('Bram').inventory,muts:r.muts};});
check(518,'remaining: gift at home also consumes chest copy',()=>{const h=village();worldState.character.inventory=['Healing potion'];h.items=[{name:'Healing potion',placed:1,taken:false,qty:1,by:'Silas',min:0}];companion();const r=applyMuts('[ITEM_LOST:Healing potion][COMPANION_ITEM_GAINED:Bram|Healing potion]');return {result:h.items[0].taken||h.items[0].qty===0?'STILL BROKEN':'NOT REPRODUCED',hero:worldState.character.inventory,companion:findCompanionChar('Bram').inventory,chest:h.items,muts:r.muts};});
check(518,'remaining: independent loot collides with missing companion throw',()=>{engine.makeTestWorld();worldState.character.inventory=[];companion();const r=applyMuts('You loot a dagger. [ITEM_GAINED:Dagger] Bram throws his dagger. [COMPANION_ITEM_LOST:Bram|Dagger]');return {result:worldState.character.inventory.length===0?'STILL BROKEN':'NOT REPRODUCED',hero:worldState.character.inventory,muts:r.muts};});
check(519,'remaining: unpaired placement undo destroys item',()=>{const h=village();worldState.character.inventory=[];applyMuts('[LOCATION_ITEM:Sihedron ritual spear|placed]');const undo=undoLastItemMove();return {result:undo.ok&&worldState.character.inventory.length===0&&h.items.every(i=>i.taken||i.qty===0)?'STILL BROKEN':'INSPECT',undo,hero:worldState.character.inventory,chest:h.items};});
check(517,'remaining: unsupported price forms',()=>{const forms=['20 for 1 gp','5 gp per dozen','1 gp 5 sp'];return {result:'STILL BROKEN',prices:forms.map(s=>({input:s,parsed:parseCoin(s)}))};});
check(517,'remaining: repeated wanted base names',()=>{const n=shop();n.wanted=[{item:'Warded ring',offer:'40 gp',by:'Frizwick',t:1,min:clockNow()}];worldState.character.inventory=['Warded ring','Warded ring — taken from the crypt','Warded ring (cracked)'];const cat=shopTradeCatalog();assert(cat.ok);const marks={};cat.sell.forEach(s=>marks[s.name.toLowerCase()]=1);const plan=shopTradePlan(cat,{sell:marks});return {result:plan.sellGp===120?'STILL BROKEN':'INSPECT',sell:cat.sell,plan};});
check(517,'remaining: counted ware name doubles bundle',()=>{const n=shop();worldState.character.inventory=[];applyMuts('[WARES:Arrow x20|1 gp]');const cat=shopTradeCatalog();assert(cat.ok);const result=shopTradeApply({buy:{'arrow x20':20}});return {result:worldState.character.inventory.join()!=='Arrow x20'?'STILL BROKEN':'NOT REPRODUCED',buy:cat.buy,trade:result,hero:worldState.character.inventory};});
check(517,'remaining: per-five wanted offer cannot select a payable bundle',()=>{const n=shop();n.wanted=[{item:'Iron ore',offer:'1 gp per 5',by:'Frizwick',t:1,min:clockNow()}];worldState.character.inventory=['Iron ore x5'];const cat=shopTradeCatalog();assert(cat.ok);const rows=shopLedgerRows(cat),p=shopTradePlan(cat,{sell:{'iron ore':1}});return {result:rows.left[0].max===1&&!p.ok?'STILL BROKEN':'INSPECT',rows:rows.left,plan:p};});
check(517,'remaining: adventure wrong-unit coin has no GM ping',()=>{engine.makeTestWorld();delete worldState.tradeRefusedPing;const r=applyMuts('[GOLD:-5 sp]');return {result:!worldState.tradeRefusedPing?'STILL BROKEN':'INSPECT',gold:worldState.character.gold,ping:worldState.tradeRefusedPing||null,muts:r.muts};});
check(517,'remaining: paid empty companion take says nothing moved',()=>{engine.makeTestWorld();worldState.character.inventory=[];companion();const before=worldState.character.gold,r=applyMuts('[GOLD:-2][COMPANION_ITEM_LOST:Bram|Torch][ITEM_GAINED:Torch]');return {result:worldState.character.gold===before-2&&worldState.character.inventory.length===0?'STILL BROKEN':'INSPECT',before,after:worldState.character.gold,hero:worldState.character.inventory,muts:r.muts};});
const out=path.join(os.tmpdir(),'tnd-quartet-2026-10-03');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));for(const r of results)console.log(r.row+' '+r.result+' '+r.caseName);if(results.some(r=>r.result==='PROBE ERROR'))process.exitCode=1;
