const fs=require('fs'),path=require('path'),assert=require('assert/strict');const root=path.resolve('C:/Projects/traffic-and-dragons'),out=__dirname,source=process.argv[2]||path.join(out,'tts-baseline.js'),mode='patched-recovery-final';const {chromium}=require(path.join(root,'dev/cdp-browser.js'));
(async()=>{const start=Date.now(),browser=await chromium.launch({headless:true});try{const context=await browser.newContext({serviceWorkers:'block',viewport:{width:800,height:600}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname!=='voice404.test')return route.abort();if(u.pathname==='/piper-host.html')return route.fulfill({status:200,contentType:'text/html',body:'<!doctype html><script>parent.postMessage({tnd:"ready"},location.origin)</script>'});let f=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!f.startsWith(root+path.sep))return route.abort();try{let body=fs.readFileSync(f);if(u.pathname==='/tts.js'){body=fs.readFileSync(source,'utf8').replace('settings: { models: VOICE_MODELS','_review404:{spawn:_piperSpawnFrame}, settings: { models: VOICE_MODELS');body='window.__readyTimers=new Set();window.__realSetTimeout=window.setTimeout;window.__realClearTimeout=window.clearTimeout;window.setTimeout=function(fn,ms){var id=__realSetTimeout(function(){__readyTimers.delete(id);fn();},ms);if(ms===30000)__readyTimers.add(id);return id;};window.clearTimeout=function(id){__readyTimers.delete(id);return __realClearTimeout(id);};\n'+body;}
return route.fulfill({status:200,contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'application/json',body});}catch(e){return route.fulfill({status:404,body:'Not found'});}});
await page.goto('http://voice404.test/index.html');await page.waitForFunction(()=>!!window.TTS&&!!TTS._review404);
const before=await page.evaluate(()=>{const d=TTS.settings.draft();d.primary='speechify';d.keys.speechify='synthetic';d.models.speechify.voices=[{id:'warm',label:'Warm reader',g:'female',note:'accent:british,pitch:low,timbre:rich resonant',language:'en-US'},{id:'deep',label:'Deep reader',g:'male',note:'Warm',language:'en-US'}];d.models.speechify.narrator='warm';store.set(TTS.settings._keys.settings,JSON.stringify({primary:d.primary,models:d.models}));store.set(TTS.settings._keys.credentials,JSON.stringify({speechify:'synthetic'}));TTS.showSettingsModal();return {labels:Array.from(document.getElementById('tts-narrator').options).map(x=>x.textContent),note:document.getElementById('tts-tab-panel').textContent};});
await page.evaluate(()=>{const n=document.getElementById('tts-narrator');n.value='deep';n.dispatchEvent(new Event('change'));document.querySelectorAll('.tnd-toast').forEach(t=>t.click());});await page.waitForFunction(()=>!document.querySelector('.tnd-toast'));
await page.screenshot({path:path.join(out,mode+'-settings.png')});
const lifecycle=await page.evaluate(async()=>{const started=performance.now(),checkpoints=[];for(let i=0;i<0;i++){const a=await TTS._review404.spawn();a.destroy();if(i%10===0)checkpoints.push({cycle:i+1,ms:Math.round(performance.now()-started),timers:__readyTimers.size,frames:document.querySelectorAll('iframe').length});await new Promise(r=>__realSetTimeout(r,500));}return{elapsedMs:Math.round(performance.now()-started),cycles:70,timers:__readyTimers.size,frames:document.querySelectorAll('iframe').length,checkpoints};});

const invalid=await page.evaluate(()=>{const d=TTS.settings.draft();d.primary='local';d.models.inworld.voices=Array.from({length:4001},(_,i)=>({id:'actor-'+i,label:'Actor '+i,g:'male'}));d.models.inworld.narrator='actor-0';d.models.inworld.cast={legacy:'actor-4000'};store.set(TTS.settings._keys.settings,JSON.stringify({primary:d.primary,models:d.models}));store.set(TTS.settings._keys.credentials,JSON.stringify({inworld:'synthetic',speechify:'synthetic'}));providerKeys.openai='synthetic-gm';window.__invalidRaw=store.get(TTS.settings._keys.settings);window.__invalidKeys=store.get(TTS.settings._keys.credentials);TTS.showSettingsModal();return {open:!!document.getElementById('tts-modal'),alerts:Array.from(document.querySelectorAll('#tts-modal [role=alert]')).map(x=>x.textContent)};});
assert(invalid.open);assert(invalid.alerts.some(x=>/Inworld/.test(x)&&/Refresh/.test(x)));
await page.screenshot({path:path.join(out,'patched-recovery.png')});
await page.locator('#tts-cancel-btn').click();assert(await page.evaluate(()=>store.get(TTS.settings._keys.settings)===__invalidRaw&&store.get(TTS.settings._keys.credentials)===__invalidKeys));
await page.evaluate(()=>{TTS.showSettingsModal();const n=document.getElementById('tts-model');n.value='inworld';n.dispatchEvent(new Event('change'));window.fetch=async()=>({ok:true,json:async()=>({voices:[{voiceId:'actor-0',displayName:'Actor 0',gender:'male',description:'Warm',langCode:'en-US'}]})});});
await page.locator('#tts-load-voices').click();await page.waitForFunction(()=>document.getElementById('tts-catalog-status').textContent.includes('1 actors'));
await page.locator('#tts-save-btn').click();await page.waitForFunction(()=>!document.getElementById('tts-modal'));
const repaired=await page.evaluate(()=>{const d=TTS.settings.draft();return{primary:d.primary,ids:d.models.inworld.voices.map(v=>v.id),cast:d.models.inworld.cast,issue:d.models.inworld._catalogIssue||'',gm:providerKeys.openai};});
assert.deepEqual(repaired,{primary:'inworld',ids:['actor-0'],cast:{legacy:'actor-4000'},issue:'',gm:'synthetic-gm'});


const dismiss=async()=>{await page.evaluate(()=>document.querySelectorAll('.tnd-toast').forEach(t=>t.click()));await page.waitForFunction(()=>!document.querySelector('.tnd-toast'));};await dismiss();
await page.evaluate(()=>{const d=TTS.settings.draft();d.primary='local';d.models.inworld.voices=[null];d.models.inworld.narrator='keep-narrator';d.models.inworld.cast={legacy:'keep-pin'};store.set(TTS.settings._keys.settings,JSON.stringify({primary:d.primary,models:d.models}));store.set(TTS.settings._keys.credentials,'{}');window.__keylessRaw=store.get(TTS.settings._keys.settings);TTS.showSettingsModal();});
await page.locator('#tts-clear-catalog-inworld').click();assert.equal(await page.evaluate(()=>store.get(TTS.settings._keys.settings)===__keylessRaw),true);await page.screenshot({path:path.join(out,'keyless-clear-draft.png')});await page.locator('#tts-cancel-btn').click();assert.equal(await page.evaluate(()=>store.get(TTS.settings._keys.settings)===__keylessRaw),true);
await page.evaluate(()=>TTS.showSettingsModal());await page.locator('#tts-clear-catalog-inworld').click();await page.locator('#tts-save-btn').click();await page.waitForFunction(()=>!document.getElementById('tts-modal'));const keyless=await page.evaluate(()=>{const d=TTS.settings.draft();return{primary:d.primary,voices:d.models.inworld.voices,narrator:d.models.inworld.narrator,cast:d.models.inworld.cast,key:d.keys.inworld};});assert.deepEqual(keyless,{primary:'local',voices:[],narrator:'keep-narrator',cast:{legacy:'keep-pin'},key:''});await dismiss();
await page.evaluate(()=>{const d=TTS.settings.draft();d.primary='local';for(const id of ['inworld','speechify']){d.models[id].voices=Array.from({length:4000},(_,i)=>({id:id+i+'x'.repeat(80),label:'Actor '+i,g:'M',note:'Warm'}));d.models[id].narrator=d.models[id].voices[0].id;d.models[id].cast={legacy:d.models[id].voices[3999].id};}store.set(TTS.settings._keys.settings,JSON.stringify({primary:d.primary,models:d.models}));window.__budgetRaw=store.get(TTS.settings._keys.settings);window.__budgetPins={inworld:d.models.inworld.cast,speechify:d.models.speechify.cast};TTS.showSettingsModal();});
await page.locator('#tts-save-btn').click();assert.match(await page.evaluate(()=>document.getElementById('tts-status').textContent),/too large to save.*Clear an unused cached catalog/);assert.equal(await page.evaluate(()=>store.get(TTS.settings._keys.settings)===__budgetRaw),true);await page.screenshot({path:path.join(out,'aggregate-refusal.png')});
await page.evaluate(()=>{const n=document.getElementById('tts-model');n.value='inworld';n.dispatchEvent(new Event('change'));});await page.locator('#tts-clear-catalog-inworld').click();await page.evaluate(()=>{const n=document.getElementById('tts-model');n.value='local';n.dispatchEvent(new Event('change'));});await page.locator('#tts-save-btn').click();await page.waitForFunction(()=>!document.getElementById('tts-modal'));const aggregate=await page.evaluate(()=>{const d=TTS.settings.draft();return{primary:d.primary,inworld:d.models.inworld.voices.length,speechify:d.models.speechify.voices.length,pinsSame:JSON.stringify(d.models.inworld.cast)===JSON.stringify(__budgetPins.inworld)&&JSON.stringify(d.models.speechify.cast)===JSON.stringify(__budgetPins.speechify),size:store.get(TTS.settings._keys.settings).length};});assert.equal(aggregate.primary,'local');assert.equal(aggregate.inworld,0);assert.equal(aggregate.speechify,4000);assert.equal(aggregate.pinsSame,true);assert(aggregate.size<=1048576);await dismiss();


await page.evaluate(()=>{const d=TTS.settings.draft();d.primary='inworld';d.keys.inworld='synthetic';d.models.inworld.voices=[{id:'before',label:'Before',g:'M'}];d.models.inworld.narrator='before';d.models.inworld.cast={legacy:'saved-pin'};TTS.settings.save(d);TTS.showSettingsModal();window.__lateAborted=false;window.fetch=(u,o)=>{o.signal.addEventListener('abort',()=>{__lateAborted=true;});return new Promise(r=>{window.__resolveLate=r;});};});
await page.locator('#tts-load-voices').click();await page.waitForFunction(()=>typeof __resolveLate==='function');await page.locator('#tts-clear-catalog-inworld').click();await page.waitForFunction(()=>__lateAborted);await page.evaluate(async()=>{__resolveLate({ok:true,json:async()=>({voices:[{voiceId:'late',displayName:'Late'}]})});await Promise.resolve();await Promise.resolve();const n=document.getElementById('tts-model');n.value='local';n.dispatchEvent(new Event('change'));});await page.locator('#tts-save-btn').click();await page.waitForFunction(()=>!document.getElementById('tts-modal'));const late=await page.evaluate(()=>({voices:TTS.settings.draft().models.inworld.voices,cast:TTS.settings.draft().models.inworld.cast,aborted:__lateAborted}));assert.deepEqual(late,{voices:[],cast:{legacy:'saved-pin'},aborted:true});

const result={late,keyless,aggregate,invalid,repaired,mode,wallMs:Date.now()-start,before,lifecycle,errors,limits:'Actual Chrome clock and lifecycle handles; synthetic ready iframe, no synthesis or heap/GC measurement. All external requests aborted.'};fs.writeFileSync(path.join(out,mode+'-browser.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));assert.deepEqual(errors,[]);}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
