// Actual browser doors, disposable storage, local assets, and intercepted remote reads only.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),os=require('os');
const {chromium}=require(path.join(process.argv[2]||process.cwd(),'dev/cdp-browser.js'));
const root=path.resolve(process.argv[2]||process.cwd()),out=path.join(os.tmpdir(),'tnd-545-browser');fs.mkdirSync(out,{recursive:true});
const bp={format:'tnd-blueprint-v1',name:'Reserved Names',tone:'high',startingLocation:'constructor',premise:'Find the bell.',acts:[{title:'Act One',goal:'Find it.',arcs:[{title:'Arc 1: Constructor',objective:'Find the bell.'}]}],npcs:[{name:'__proto__',role:'ally',notes:'Keeps a blue lantern.'}],locations:[{name:'constructor',description:'A stone yard.'}],rules:[]};
const file=path.join(out,'reserved.blueprint');fs.writeFileSync(file,JSON.stringify(bp));
(async()=>{const browser=await chromium.launch({headless:true});try{const context=await browser.newContext({serviceWorkers:'block',viewport:{width:800,height:600}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.pathname==='/catalog/blueprints')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify([{id:'reserved',name:bp.name,blurb:'A reserved-name fixture.',revision:1,blueprint:bp}])});if(u.hostname!=='stores.test')return route.abort();const f=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!f.startsWith(root+path.sep))return route.abort();try{return route.fulfill({status:200,contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'application/json',body:fs.readFileSync(f)});}catch(e){return route.fulfill({status:404,body:'Not found'});}});
await page.goto('http://stores.test/index.html');await page.waitForFunction(()=>typeof showBlueprintBrowser==='function');
await page.evaluate(()=>{window.testHero545={name:'toString',gender:'F',cls:'Warrior',level:1,hp:14,maxHp:14,coin:2500,stats:{STR:15,DEX:12,CON:14,INT:10,WIS:10,CHA:10},inventory:[],abilities:[],spells:[],coreMemories:[]};beginAdventure=()=>{busy=false;};initCampaignFolderForGame=()=>{};storageAdapter.syncToServer=()=>{};storageAdapter.isServerMode=()=>true;storageAdapter.hasToken=()=>true;goStep=()=>{};window.accept545=()=>{var b=pendingBlueprint,h=JSON.parse(JSON.stringify(testHero545));h._startLoc=b.startingLocation;pendingCompanions=[];startGame(h,'High','', '');applyMuts('[NPC_NOTE:__proto__|Keeps the bell.][LOCATION_DESC:A stone yard.]');var p=buildSysPrompt();return {npc:Object.prototype.hasOwnProperty.call(memory.npcs,'__proto__'),node:Object.prototype.hasOwnProperty.call(memory.map.nodes,'constructor'),hero:worldState.character.name,prompt:!!p.volatile,poison:Object.prototype.hasOwnProperty.call(Object.prototype,'knowledge')};};});
for(const door of ['catalog','library','file']){
 await page.evaluate(()=>{busy=false;showBlueprintBrowser();});
 if(door==='catalog'){await page.waitForSelector('[data-bpcat]');await page.locator('[data-bpcat]').click();}
 if(door==='library'){await page.evaluate(bp=>{storageAdapter.isServerMode=()=>true;storageAdapter.listBlueprintLibrary=cb=>cb(null,[{name:bp.name,slug:'reserved',blueprint:bp}]);},bp);await page.locator('[data-seg=library]').click();await page.waitForSelector('[data-bpidx]');await page.locator('[data-bpidx]').click();}
 if(door==='file'){await page.locator('[data-seg=local]').click();await page.locator('#bp-file-inp').setInputFiles(file);}
 await page.waitForSelector('#bp-use');
 // Sticky notifications can cover the trusted click target after the previous campaign starts.
 await page.evaluate(()=>document.querySelectorAll('.tnd-toast').forEach(t=>t.click()));
 await page.waitForFunction(()=>!document.querySelector('.tnd-toast'));
 assert.equal(await page.evaluate(()=>pendingBlueprint),null,door+' retained a previous blueprint');
 assert.equal(await page.evaluate(()=>{const e=document.getElementById('bp-use');e.scrollIntoView({block:'center',inline:'center'});const r=e.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return e===hit||e.contains(hit);}),true,door+' blueprint button is occluded');
 await page.screenshot({path:path.join(out,door+'-ready.png')});
 await page.locator('#bp-use').click();
 await page.waitForFunction(()=>pendingBlueprint!==null);
 assert.deepEqual(await page.evaluate(()=>({name:pendingBlueprint.name,place:pendingBlueprint.startingLocation,npc:pendingBlueprint.npcs[0].name,arc:pendingBlueprint.acts[0].arcs[0].title})),{name:bp.name,place:bp.startingLocation,npc:bp.npcs[0].name,arc:bp.acts[0].arcs[0].title},door+' selected the wrong blueprint');
 assert.deepEqual(await page.evaluate(()=>accept545()),{npc:true,node:true,hero:'toString',prompt:true,poison:false},door+' actual start failed');console.log('PASS actual '+door+' blueprint selection → start → tag → prompt');
}
await page.evaluate(bp=>{localStorage.setItem(HOME_PENDING_BP_K,JSON.stringify({bp,at:Date.now()}));if(!consumeHomeBlueprint())throw Error('home refused');},bp);assert.equal((await page.evaluate(()=>accept545())).node,true,'home node lost');
await page.evaluate(bp=>{busy=false;worldState=null;localStorage.setItem(HOME_PENDING_QS_K,JSON.stringify({bp,char:testHero545,at:Date.now()}));if(!consumeHomeQuickStart())throw Error('quick start refused');},bp);assert.equal(await page.evaluate(()=>Object.prototype.hasOwnProperty.call(memory.npcs,'__proto__')),true,'quick start NPC lost');
await page.screenshot({path:path.join(out,'game-reserved.png')});console.log('PASS actual home handoff and quick start');
await page.goto('http://stores.test/blueprint-designer.html');await page.waitForFunction(()=>!!window.__bpdTest);const round=await page.evaluate(bp=>{__bpdTest.load(bp);return {bp:__bpdTest.getBp(),error:__bpdTest.validate()};},bp);assert.equal(round.bp.startingLocation,'constructor');assert.equal(round.bp.npcs[0].name,'__proto__');assert(!round.error,'Designer validation failed: '+round.error);await page.screenshot({path:path.join(out,'designer-reserved.png')});console.log('PASS actual Designer load/render/validate');await page.goto('http://stores.test/character_editor.html');await page.waitForFunction(()=>!!window.__ceTest);const editor=await page.evaluate(()=>{var c=__ceTest.blank();c.name='constructor';c.itemDefs=JSON.parse('{"__proto__":{"category":"tool","effect":"A bell"}}');__ceTest.load(c);var got=__ceTest.get();return {name:got.name,own:Object.prototype.hasOwnProperty.call(got.itemDefs,'__proto__'),nullPrototype:Object.getPrototypeOf(got.itemDefs)===null};});assert.deepEqual(editor,{name:'constructor',own:true,nullPrototype:true},'editor admission regained dictionary prototype');console.log('PASS actual character editor reserved name and own definition');assert.deepEqual(errors,[]);console.log('PASS all reserved-name browser doors; isolated storage, no live provider/save calls');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
